In [ ]:
Calculando el Estadístico Chi-Cuadrado Para el Primer Dígito 

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/15unNCvztiQfNtll4xRzNRfR5sBTpFLsM/export?format=csv")
df

PL     PN  LIBRE-PINU  TOTAL
0  8946  17976       30485  57937
1  1254   2830        3644   7808
2  1534   2409        2895   6892
3  1491   6205        6799  14550
4  1441   4697        6230  12417
5   347   1841        3596   5817
6  4085  12488       15006  31882
7  1096   4004        5006  10167

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[8946, 1254, 1534, 1491, 1441, 347, 4085, 1096]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[17976, 2830, 2409, 6205, 4697, 1841, 12488, 4004]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[30485, 3644, 2895, 6799, 6230, 3596, 15006, 5006]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[57937, 7808, 6892, 14550, 12417, 5817, 31882, 10167]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([5, 0, 1, 1, 0, 0, 0, 1, 0])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.01 , 0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.002, 0.   ])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

8

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([2.408 , 1.4088, 0.9992, 0.7752, 0.6336, 0.5352, 0.464 , 0.4096,
       0.3664])

In [15]:
fe.sum()

7.999999999999999

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.291 , -0.1761, -0.1229, -0.0949, -0.0792, -0.0669, -0.058 ,
       -0.0492, -0.0458])

In [17]:
diferencia.sum()

-0.9839999999999999

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.79005980e+00, 1.40880000e+00, 6.40512410e-07, 6.51896801e-02,
       6.33600000e-01, 5.35200000e-01, 4.64000000e-01, 8.51006250e-01,
       3.66400000e-01])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

7.114256371259421

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([3, 2, 0, 2, 0, 1, 0, 0, 0])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.006, 0.004, 0.   , 0.004, 0.   , 0.002, 0.   , 0.   , 0.   ])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

8

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([2.408 , 1.4088, 0.9992, 0.7752, 0.6336, 0.5352, 0.464 , 0.4096,
       0.3664])

In [29]:
fe.sum()

7.999999999999999

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.295 , -0.1721, -0.1249, -0.0929, -0.0792, -0.0649, -0.058 ,
       -0.0512, -0.0458])

In [31]:
diferencia.sum()

-0.9839999999999999

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.14554153, 0.24809585, 0.9992    , 1.93515872, 0.6336    ,
       0.40366039, 0.464     , 0.4096    , 0.3664    ])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

5.605256491837253

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([1, 1, 3, 0, 1, 2, 0, 0, 0])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.002, 0.006, 0.   , 0.002, 0.004, 0.   , 0.   , 0.   ])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

8

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([2.408 , 1.4088, 0.9992, 0.7752, 0.6336, 0.5352, 0.464 , 0.4096,
       0.3664])

In [43]:
fe.sum()

7.999999999999999

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.299 , -0.1741, -0.1189, -0.0969, -0.0772, -0.0629, -0.058 ,
       -0.0512, -0.0458])

In [45]:
diferencia.sum()

-0.9839999999999999

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [48]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.82328239, 0.11862396, 4.00640576, 0.7752    , 0.21188283,
       4.00904155, 0.464     , 0.4096    , 0.3664    ])

# Partido Libre

In [49]:
x_2 = f0_fe_2_fe.sum()
x_2 

11.184436503137151

In [50]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [51]:
f0 = np.array(f0)
f0

array([3, 0, 1, 0, 2, 1, 1, 0, 0])

In [52]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.006, 0.   , 0.002, 0.   , 0.004, 0.002, 0.002, 0.   , 0.   ])

In [53]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [54]:
f0_tot=f0.sum()
f0_tot

8

In [55]:
fe = benford*f0_tot

In [56]:
fe 

array([2.408 , 1.4088, 0.9992, 0.7752, 0.6336, 0.5352, 0.464 , 0.4096,
       0.3664])

In [57]:
fe.sum()

7.999999999999999

In [58]:
diferencia = fre_relativa - benford
diferencia 

array([-0.295 , -0.1761, -0.1229, -0.0969, -0.0752, -0.0649, -0.056 ,
       -0.0512, -0.0458])

In [59]:
diferencia.sum()

-0.9839999999999999

In [60]:
f0_fe= (f0-fe)

In [61]:
f0_fe_2 = f0_fe*f0_fe

In [62]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.45541528e-01, 1.40880000e+00, 6.40512410e-07, 7.75200000e-01,
       2.94673131e+00, 4.03660389e-01, 6.19172414e-01, 4.09600000e-01,
       3.66400000e-01])

# Total

In [63]:
x_2 = f0_fe_2_fe.sum()
x_2 

7.0751062843157895