In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1zuU8MkVl8U3G7h5xz18XE3IUumEMog1b/export?format=csv")
df

PL     PN  LIBRE-PINU  TOTAL
0   6344  23173       32813  62598
1    874   2407        2043   5378
2   1059   6035        3197  10378
3    262   1295         743   2318
4   1155   4753        3142   9241
5   3204  10377        8058  21782
6   3491   7003        9004  19661
7   1230   1686         710   3645
8   2178   5990        6571  14820
9   1295   4733        3175   9250
10  1390   6258        5045  12777
11   713   2223         868   3820
12   516   1332         637   2492
13   645   1377         635   2689
14  2094   6777        4437  13384
15  1513   3105        3488   8138

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[6344,
 874,
 1059,
 262,
 1155,
 3204,
 3491,
 1230,
 2178,
 1295,
 1390,
 713,
 516,
 645,
 2094,
 1513]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[23173,
 2407,
 6035,
 1295,
 4753,
 10377,
 7003,
 1686,
 5990,
 4733,
 6258,
 2223,
 1332,
 1377,
 6777,
 3105]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[32813,
 2043,
 3197,
 743,
 3142,
 8058,
 9004,
 710,
 6571,
 3175,
 5045,
 868,
 637,
 635,
 4437,
 3488]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[62598,
 5378,
 10378,
 2318,
 9241,
 21782,
 19661,
 3645,
 14820,
 9250,
 12777,
 3820,
 2492,
 2689,
 13384,
 8138]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([6, 3, 2, 0, 1, 2, 1, 1, 0])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.012, 0.006, 0.004, 0.   , 0.002, 0.004, 0.002, 0.002, 0.   ])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

16

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([4.816 , 2.8176, 1.9984, 1.5504, 1.2672, 1.0704, 0.928 , 0.8192,
       0.7328])

In [15]:
fe.sum()

15.999999999999998

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.289 , -0.1701, -0.1209, -0.0969, -0.0772, -0.0629, -0.056 ,
       -0.0492, -0.0458])

In [17]:
diferencia.sum()

-0.9679999999999999

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.91083056e-01, 1.18078365e-02, 1.28102482e-06, 1.55040000e+00,
       5.63414141e-02, 8.07320777e-01, 5.58620690e-03, 3.99031250e-02,
       7.32800000e-01])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

3.495243697277272

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([5, 3, 1, 2, 1, 3, 1, 0, 0])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.01 , 0.006, 0.002, 0.004, 0.002, 0.006, 0.002, 0.   , 0.   ])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

16

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([4.816 , 2.8176, 1.9984, 1.5504, 1.2672, 1.0704, 0.928 , 0.8192,
       0.7328])

In [29]:
fe.sum()

15.999999999999998

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.291 , -0.1701, -0.1229, -0.0929, -0.0772, -0.0609, -0.056 ,
       -0.0512, -0.0458])

In [31]:
diferencia.sum()

-0.9679999999999999

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.0070299 , 0.01180784, 0.49880032, 0.13037936, 0.05634141,
       3.47847175, 0.00558621, 0.8192    , 0.7328    ])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

5.740416787126998

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([0, 1, 5, 1, 1, 3, 2, 2, 1])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.002, 0.01 , 0.002, 0.002, 0.006, 0.004, 0.004, 0.002])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

16

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([4.816 , 2.8176, 1.9984, 1.5504, 1.2672, 1.0704, 0.928 , 0.8192,
       0.7328])

In [43]:
fe.sum()

15.999999999999998

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.301 , -0.1741, -0.1149, -0.0949, -0.0772, -0.0609, -0.054 ,
       -0.0472, -0.0438])

In [45]:
diferencia.sum()

-0.9679999999999999

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [48]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([4.816     , 1.17251198, 4.50840801, 0.19539484, 0.05634141,
       3.47847175, 1.23834483, 1.7020125 , 0.09742882])

# Partido Libre

In [49]:
x_2 = f0_fe_2_fe.sum()
x_2 

17.26491413984215

In [50]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [51]:
f0 = np.array(f0)
f0

array([5, 4, 2, 0, 1, 1, 0, 1, 2])

In [52]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.01 , 0.008, 0.004, 0.   , 0.002, 0.002, 0.   , 0.002, 0.004])

In [53]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [54]:
f0_tot=f0.sum()
f0_tot

16

In [55]:
fe = benford*f0_tot

In [56]:
fe 

array([4.816 , 2.8176, 1.9984, 1.5504, 1.2672, 1.0704, 0.928 , 0.8192,
       0.7328])

In [57]:
fe.sum()

15.999999999999998

In [58]:
diferencia = fre_relativa - benford
diferencia 

array([-0.291 , -0.1681, -0.1209, -0.0969, -0.0772, -0.0649, -0.058 ,
       -0.0492, -0.0418])

In [59]:
diferencia.sum()

-0.968

In [60]:
f0_fe= (f0-fe)

In [61]:
f0_fe_2 = f0_fe*f0_fe

In [62]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([7.02990033e-03, 4.96191709e-01, 1.28102482e-06, 1.55040000e+00,
       5.63414141e-02, 4.63019432e-03, 9.28000000e-01, 3.99031250e-02,
       2.19131528e+00])

# Total

In [63]:
x_2 = f0_fe_2_fe.sum()
x_2 

5.273812907917239