In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1HZCThrsZly6HJceEVUIZaOTjVTegqT9w/export?format=csv")
df

PL    PN  LIBRE-PINU  TOTAL
0  2149  8109       10141  20509
1   492  2060        1539   4113
2   706  1735        1299   3802
3   507  1270        1528   3341
4  1026  4062        8821  14003
5   323  1221         614   2198
6   244  1157         770   2190
7  1129  6620        9477  17329
8  3445  7948       16843  28407
9   735  5120        5947  11891

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[2149, 492, 706, 507, 1026, 323, 244, 1129, 3445, 735]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[8109, 2060, 1735, 1270, 4062, 1221, 1157, 6620, 7948, 5120]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[10141, 1539, 1299, 1528, 8821, 614, 770, 9477, 16843, 5947]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[20509, 4113, 3802, 3341, 14003, 2198, 2190, 17329, 28407, 11891]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([2, 2, 2, 1, 1, 0, 2, 0, 0])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.004, 0.004, 0.004, 0.002, 0.002, 0.   , 0.004, 0.   , 0.   ])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

10

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([3.01 , 1.761, 1.249, 0.969, 0.792, 0.669, 0.58 , 0.512, 0.458])

In [15]:
fe.sum()

10.0

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.297 , -0.1721, -0.1209, -0.0949, -0.0772, -0.0669, -0.054 ,
       -0.0512, -0.0458])

In [17]:
diferencia.sum()

-0.9799999999999999

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([3.38903654e-01, 3.24366837e-02, 4.51562050e-01, 9.91744066e-04,
       5.46262626e-02, 6.69000000e-01, 3.47655172e+00, 5.12000000e-01,
       4.58000000e-01])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

5.994072118657445

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([4, 1, 0, 1, 1, 1, 1, 1, 0])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.008, 0.002, 0.   , 0.002, 0.002, 0.002, 0.002, 0.002, 0.   ])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

10

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([3.01 , 1.761, 1.249, 0.969, 0.792, 0.669, 0.58 , 0.512, 0.458])

In [29]:
fe.sum()

10.0

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.293 , -0.1741, -0.1249, -0.0949, -0.0772, -0.0649, -0.056 ,
       -0.0492, -0.0458])

In [31]:
diferencia.sum()

-0.9799999999999999

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([3.25614618e-01, 3.28859171e-01, 1.24900000e+00, 9.91744066e-04,
       5.46262626e-02, 1.63768311e-01, 3.04137931e-01, 4.65125000e-01,
       4.58000000e-01])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

3.350123037504411

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([5, 0, 0, 0, 1, 1, 1, 1, 1])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.01 , 0.   , 0.   , 0.   , 0.002, 0.002, 0.002, 0.002, 0.002])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

10

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([3.01 , 1.761, 1.249, 0.969, 0.792, 0.669, 0.58 , 0.512, 0.458])

In [43]:
fe.sum()

10.0

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.291 , -0.1761, -0.1249, -0.0969, -0.0772, -0.0649, -0.056 ,
       -0.0492, -0.0438])

In [45]:
diferencia.sum()

-0.9799999999999999

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [48]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.31564784, 1.761     , 1.249     , 0.969     , 0.05462626,
       0.16376831, 0.30413793, 0.465125  , 0.64140611])

# Partido Libre

In [49]:
x_2 = f0_fe_2_fe.sum()
x_2 

6.923711458641234

In [50]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [51]:
f0 = np.array(f0)
f0

array([3, 4, 2, 1, 0, 0, 0, 0, 0])

In [52]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.006, 0.008, 0.004, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ])

In [53]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [54]:
f0_tot=f0.sum()
f0_tot

10

In [55]:
fe = benford*f0_tot

In [56]:
fe 

array([3.01 , 1.761, 1.249, 0.969, 0.792, 0.669, 0.58 , 0.512, 0.458])

In [57]:
fe.sum()

10.0

In [58]:
diferencia = fre_relativa - benford
diferencia 

array([-0.295 , -0.1681, -0.1209, -0.0949, -0.0792, -0.0669, -0.058 ,
       -0.0512, -0.0458])

In [59]:
diferencia.sum()

-0.9799999999999999

In [60]:
f0_fe= (f0-fe)

In [61]:
f0_fe_2 = f0_fe*f0_fe

In [62]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([3.32225914e-05, 2.84674673e+00, 4.51562050e-01, 9.91744066e-04,
       7.92000000e-01, 6.69000000e-01, 5.80000000e-01, 5.12000000e-01,
       4.58000000e-01])

# Total

In [63]:
x_2 = f0_fe_2_fe.sum()
x_2 

6.310333751106888