In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1Q7hsUIfweYgBPBSBDYpedZhuGPt0E7GU/export?format=csv")
df

PL     PN  LIBRE-PINU  TOTAL
0   7722  21309       20172  49570
1    368   3093        2563   6043
2    893   5618        3283   9858
3    713   3626        1541   5950
4     87    686         375   1150
5   1407   4722        3506   9676
6    252   1620        1618   3501
7    333   1036         800   2196
8    220   1912        1823   3970
9    571   2264        1390   4258
10  1958   2457        1205   5652
11   587   2639        1901   5165
12   715   5110        3470   9337
13  1131   1523        1033   3715
14   902    660         916   2489
15  1088   2389        1768   5272
16   171    943         765   1882
17  5752  15114       13326  34492
18   893   4238        3717   8919
19  2237   2764        1142   6177
20  1302   4834        4721  10930

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[7722,
 368,
 893,
 713,
 87,
 1407,
 252,
 333,
 220,
 571,
 1958,
 587,
 715,
 1131,
 902,
 1088,
 171,
 5752,
 893,
 2237,
 1302]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[21309,
 3093,
 5618,
 3626,
 686,
 4722,
 1620,
 1036,
 1912,
 2264,
 2457,
 2639,
 5110,
 1523,
 660,
 2389,
 943,
 15114,
 4238,
 2764,
 4834]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[20172,
 2563,
 3283,
 1541,
 375,
 3506,
 1618,
 800,
 1823,
 1390,
 1205,
 1901,
 3470,
 1033,
 916,
 1768,
 765,
 13326,
 3717,
 1142,
 4721]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[49570,
 6043,
 9858,
 5950,
 1150,
 9676,
 3501,
 2196,
 3970,
 4258,
 5652,
 5165,
 9337,
 3715,
 2489,
 5272,
 1882,
 34492,
 8919,
 6177,
 10930]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([6, 3, 2, 0, 3, 0, 3, 3, 1])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.012, 0.006, 0.004, 0.   , 0.006, 0.   , 0.006, 0.006, 0.002])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

21

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([6.321 , 3.6981, 2.6229, 2.0349, 1.6632, 1.4049, 1.218 , 1.0752,
       0.9618])

In [15]:
fe.sum()

21.0

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.289 , -0.1701, -0.1209, -0.0969, -0.0732, -0.0669, -0.052 ,
       -0.0452, -0.0438])

In [17]:
diferencia.sum()

-0.9579999999999999

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.63013764e-02, 1.31782161e-01, 1.47929547e-01, 2.03490000e+00,
       1.07445541e+00, 1.40490000e+00, 2.60716256e+00, 3.44573571e+00,
       1.51719692e-03])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

10.864683968961655

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([5, 6, 2, 3, 2, 2, 0, 0, 1])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.01 , 0.012, 0.004, 0.006, 0.004, 0.004, 0.   , 0.   , 0.002])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

21

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([6.321 , 3.6981, 2.6229, 2.0349, 1.6632, 1.4049, 1.218 , 1.0752,
       0.9618])

In [29]:
fe.sum()

21.0

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.291 , -0.1641, -0.1209, -0.0909, -0.0752, -0.0629, -0.058 ,
       -0.0512, -0.0438])

In [31]:
diferencia.sum()

-0.9579999999999999

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.2760704 , 1.43282864, 0.14792955, 0.45772176, 0.06820241,
       0.25207774, 1.218     , 1.0752    , 0.0015172 ])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

4.929547689417657

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([10,  2,  5,  1,  0,  0,  1,  1,  1])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.02 , 0.004, 0.01 , 0.002, 0.   , 0.   , 0.002, 0.002, 0.002])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

21

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([6.321 , 3.6981, 2.6229, 2.0349, 1.6632, 1.4049, 1.218 , 1.0752,
       0.9618])

In [43]:
fe.sum()

21.0

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.281 , -0.1721, -0.1149, -0.0949, -0.0792, -0.0669, -0.056 ,
       -0.0492, -0.0438])

In [45]:
diferencia.sum()

-0.9579999999999999

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [48]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.14128160e+00, 7.79736516e-01, 2.15433467e+00, 5.26324640e-01,
       1.66320000e+00, 1.40490000e+00, 3.90180624e-02, 5.25952381e-03,
       1.51719692e-03])

# Partido Libre

In [49]:
x_2 = f0_fe_2_fe.sum()
x_2 

8.715572211768826

In [50]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [51]:
f0 = np.array(f0)
f0

array([3, 2, 4, 2, 4, 2, 0, 1, 3])

In [52]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.006, 0.004, 0.008, 0.004, 0.008, 0.004, 0.   , 0.002, 0.006])

In [53]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [54]:
f0_tot=f0.sum()
f0_tot

21

In [55]:
fe = benford*f0_tot

In [56]:
fe 

array([6.321 , 3.6981, 2.6229, 2.0349, 1.6632, 1.4049, 1.218 , 1.0752,
       0.9618])

In [57]:
fe.sum()

21.0

In [58]:
diferencia = fre_relativa - benford
diferencia 

array([-0.295 , -0.1721, -0.1169, -0.0929, -0.0712, -0.0629, -0.058 ,
       -0.0492, -0.0398])

In [59]:
diferencia.sum()

-0.958

In [60]:
f0_fe= (f0-fe)

In [61]:
f0_fe_2 = f0_fe*f0_fe

In [62]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.74482534e+00, 7.79736516e-01, 7.23018190e-01, 5.98560126e-04,
       3.28320962e+00, 2.52077735e-01, 1.21800000e+00, 5.25952381e-03,
       4.31925477e+00])

# Total

In [63]:
x_2 = f0_fe_2_fe.sum()
x_2 

12.325980261246826