In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1cItIweRj42zsfDCCLtBWVaXGOEcMmnUK/export?format=csv")
df

PL    PN  LIBRE-PINU  TOTAL
0   2540  6788       12172  21679
1   2913  2623         928   6497
2    234  1787         994   3043
3   7113  7339        3587  18210
4    423  3194        2662   6317
5   1265  4201        3548   9055
6    476  1326        1296   3122
7    365  1477        1550   3414
8   1459  4373        2367   8260
9   3045  3521        2913   9539
10   523  2148        1423   4115
11   503  3508        4082   8249
12  2739  6319        7428  16569
13   180  1646        1147   3008
14   259  3095        1497   4890
15   939   980        1301   3237
16   158  2245        1478   3900
17   190  2346        2112   4685
18  1205  1351        1316   3899
19  1206  1522        1311   4061
20  2622  4402        3013  10154
21   339  1817        1173   3353
22   271   979         849   2110

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[2540,
 2913,
 234,
 7113,
 423,
 1265,
 476,
 365,
 1459,
 3045,
 523,
 503,
 2739,
 180,
 259,
 939,
 158,
 190,
 1205,
 1206,
 2622,
 339,
 271]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[6788,
 2623,
 1787,
 7339,
 3194,
 4201,
 1326,
 1477,
 4373,
 3521,
 2148,
 3508,
 6319,
 1646,
 3095,
 980,
 2245,
 2346,
 1351,
 1522,
 4402,
 1817,
 979]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[12172,
 928,
 994,
 3587,
 2662,
 3548,
 1296,
 1550,
 2367,
 2913,
 1423,
 4082,
 7428,
 1147,
 1497,
 1301,
 1478,
 2112,
 1316,
 1311,
 3013,
 1173,
 849]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[21679,
 6497,
 3043,
 18210,
 6317,
 9055,
 3122,
 3414,
 8260,
 9539,
 4115,
 8249,
 16569,
 3008,
 4890,
 3237,
 3900,
 4685,
 3899,
 4061,
 10154,
 3353,
 2110]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([7, 7, 3, 2, 2, 0, 1, 0, 1])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.014, 0.014, 0.006, 0.004, 0.004, 0.   , 0.002, 0.   , 0.002])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

23

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([6.923 , 4.0503, 2.8727, 2.2287, 1.8216, 1.5387, 1.334 , 1.1776,
       1.0534])

In [15]:
fe.sum()

23.0

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.287 , -0.1621, -0.1189, -0.0929, -0.0752, -0.0669, -0.056 ,
       -0.0512, -0.0438])

In [17]:
diferencia.sum()

-0.9539999999999998

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([8.56420627e-04, 2.14816929e+00, 5.64113552e-03, 2.34682505e-02,
       1.74717611e-02, 1.53870000e+00, 8.36251874e-02, 1.17760000e+00,
       2.70700589e-03])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

4.998239054707376

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([7, 4, 4, 3, 0, 2, 1, 0, 2])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.014, 0.008, 0.008, 0.006, 0.   , 0.004, 0.002, 0.   , 0.004])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

23

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([6.923 , 4.0503, 2.8727, 2.2287, 1.8216, 1.5387, 1.334 , 1.1776,
       1.0534])

In [29]:
fe.sum()

23.0

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.287 , -0.1681, -0.1169, -0.0909, -0.0792, -0.0629, -0.056 ,
       -0.0512, -0.0418])

In [31]:
diferencia.sum()

-0.954

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([8.56420627e-04, 6.24667309e-04, 4.42373130e-01, 2.66928564e-01,
       1.82160000e+00, 1.38297062e-01, 8.36251874e-02, 1.17760000e+00,
       8.50628024e-01])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

4.782533054884822

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([11,  4,  3,  1,  0,  0,  1,  1,  2])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.022, 0.008, 0.006, 0.002, 0.   , 0.   , 0.002, 0.002, 0.004])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

23

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([6.923 , 4.0503, 2.8727, 2.2287, 1.8216, 1.5387, 1.334 , 1.1776,
       1.0534])

In [43]:
fe.sum()

23.0

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.279 , -0.1681, -0.1189, -0.0949, -0.0792, -0.0669, -0.056 ,
       -0.0492, -0.0418])

In [45]:
diferencia.sum()

-0.954

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [48]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.40097198e+00, 6.24667309e-04, 5.64113552e-03, 6.77392063e-01,
       1.82160000e+00, 1.53870000e+00, 8.36251874e-02, 2.67847826e-02,
       8.50628024e-01])

# Partido Libre

In [49]:
x_2 = f0_fe_2_fe.sum()
x_2 

7.405967836487338

In [50]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [51]:
f0 = np.array(f0)
f0

array([3, 2, 8, 4, 0, 2, 0, 2, 2])

In [52]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.006, 0.004, 0.016, 0.008, 0.   , 0.004, 0.   , 0.004, 0.004])

In [53]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [54]:
f0_tot=f0.sum()
f0_tot

23

In [55]:
fe = benford*f0_tot

In [ ]:
fe 

In [ ]:
fe.sum()

In [ ]:
diferencia = fre_relativa - benford
diferencia 

In [ ]:
diferencia.sum()

In [ ]:
f0_fe= (f0-fe)

In [ ]:
f0_fe_2 = f0_fe*f0_fe

In [ ]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

# Total

In [ ]:
x_2 = f0_fe_2_fe.sum()
x_2 