In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1yfDyVKJeRiSLsxhyY0lCcHa3bHP5Bv7X/export?format=csv")
df

PL     PN  LIBRE-PINU   TOTAL
0   22010  73088      122234  219685
1    5922  20363       38592   65345
2    1117   9134        5884   16254
3     360   3400        3208    7081
4    1154   4289        4420    9927
5   10022  12814       23754   47002
6     698   4231        4202    9201
7    1318   3310        4252    8961
8    1218   3551        9041   13911
9    4262   9999       13711   28160
10   4375  11062       22567   38289
11   3384   5882       19182   28957

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[22010, 5922, 1117, 360, 1154, 10022, 698, 1318, 1218, 4262, 4375, 3384]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[73088, 20363, 9134, 3400, 4289, 12814, 4231, 3310, 3551, 9999, 11062, 5882]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[122234, 38592, 5884, 3208, 4420, 23754, 4202, 4252, 9041, 13711, 22567, 19182]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[219685,
 65345,
 16254,
 7081,
 9927,
 47002,
 9201,
 8961,
 13911,
 28160,
 38289,
 28957]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([5, 1, 2, 2, 1, 1, 0, 0, 0])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.01 , 0.002, 0.004, 0.004, 0.002, 0.002, 0.   , 0.   , 0.   ])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

12

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([3.612 , 2.1132, 1.4988, 1.1628, 0.9504, 0.8028, 0.696 , 0.6144,
       0.5496])

In [15]:
fe.sum()

12.000000000000002

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.291 , -0.1741, -0.1209, -0.0929, -0.0772, -0.0649, -0.058 ,
       -0.0512, -0.0458])

In [17]:
diferencia.sum()

-0.9759999999999999

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.5333732 , 0.58641598, 0.16760171, 0.60277248, 0.00258855,
       0.04844026, 0.696     , 0.6144    , 0.5496    ])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

3.801192175749287

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([2, 1, 3, 2, 1, 0, 1, 0, 2])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.004, 0.002, 0.006, 0.004, 0.002, 0.   , 0.002, 0.   , 0.004])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

12

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([3.612 , 2.1132, 1.4988, 1.1628, 0.9504, 0.8028, 0.696 , 0.6144,
       0.5496])

In [29]:
fe.sum()

12.000000000000002

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.297 , -0.1741, -0.1189, -0.0929, -0.0772, -0.0669, -0.056 ,
       -0.0512, -0.0418])

In [31]:
diferencia.sum()

-0.976

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([7.19419712e-01, 5.86415976e-01, 1.50360384e+00, 6.02772480e-01,
       2.58855219e-03, 8.02800000e-01, 1.32781609e-01, 6.14400000e-01,
       3.82762038e+00])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

8.792402550977851

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([3, 2, 2, 3, 1, 0, 0, 0, 1])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.006, 0.004, 0.004, 0.006, 0.002, 0.   , 0.   , 0.   , 0.002])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

12

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([3.612 , 2.1132, 1.4988, 1.1628, 0.9504, 0.8028, 0.696 , 0.6144,
       0.5496])

In [43]:
fe.sum()

12.000000000000002

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.295 , -0.1721, -0.1209, -0.0909, -0.0772, -0.0669, -0.058 ,
       -0.0512, -0.0438])

In [45]:
diferencia.sum()

-0.9759999999999999

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [48]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.03694352e-01, 6.06390309e-03, 1.67601708e-01, 2.90273808e+00,
       2.58855219e-03, 8.02800000e-01, 6.96000000e-01, 6.14400000e-01,
       3.69105095e-01])

# Partido Libre

In [49]:
x_2 = f0_fe_2_fe.sum()
x_2 

5.664991690576103

In [50]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [51]:
f0 = np.array(f0)
f0

array([2, 3, 1, 1, 0, 1, 1, 1, 2])

In [52]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.004, 0.006, 0.002, 0.002, 0.   , 0.002, 0.002, 0.002, 0.004])

In [53]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [54]:
f0_tot=f0.sum()
f0_tot

12

In [55]:
fe = benford*f0_tot

In [56]:
fe 

array([3.612 , 2.1132, 1.4988, 1.1628, 0.9504, 0.8028, 0.696 , 0.6144,
       0.5496])

In [57]:
fe.sum()

12.000000000000002

In [58]:
diferencia = fre_relativa - benford
diferencia 

array([-0.297 , -0.1701, -0.1229, -0.0949, -0.0792, -0.0649, -0.056 ,
       -0.0492, -0.0418])

In [59]:
diferencia.sum()

-0.976

In [60]:
f0_fe= (f0-fe)

In [61]:
f0_fe_2 = f0_fe*f0_fe

In [62]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.71941971, 0.37214378, 0.16600043, 0.02279312, 0.9504    ,
       0.04844026, 0.13278161, 0.24200417, 3.82762038])

# Total

In [ ]:
x_2 = f0_fe_2_fe.sum()
x_2 

6.481603454488569