In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1bviWBACEUUG9cXOLQd0cFYXtROj570cJ/export?format=csv")
df

PL     PN  LIBRE-PINU  TOTAL
0    1062   4419        1969   7519
1     938   3091        1916   5973
2   13589  29725       26887  70714
3    4749   9644        5603  20120
4     888   2395        1322   4641
5     717   1440        1105   3276
6    1920   3189        1701   6832
7    1401   3544        1765   6760
8     369   2142        1414   3943
9     460    883         580   1935
10    728   2102         820   3666
11   1638   2172         674   4531
12    819   1394         832   3068
13   1378   1955        2210   5588
14   4283   6855        4944  16237
15   1821   2574         937   5371
16   1013   1143         390   2554
17    175    669         324   1175
18   3561  10293        6575  20642

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[1062,
 938,
 13589,
 4749,
 888,
 717,
 1920,
 1401,
 369,
 460,
 728,
 1638,
 819,
 1378,
 4283,
 1821,
 1013,
 175,
 3561]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[4419,
 3091,
 29725,
 9644,
 2395,
 1440,
 3189,
 3544,
 2142,
 883,
 2102,
 2172,
 1394,
 1955,
 6855,
 2574,
 1143,
 669,
 10293]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[1969,
 1916,
 26887,
 5603,
 1322,
 1105,
 1701,
 1765,
 1414,
 580,
 820,
 674,
 832,
 2210,
 4944,
 937,
 390,
 324,
 6575]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[7519,
 5973,
 70714,
 20120,
 4641,
 3276,
 6832,
 6760,
 3943,
 1935,
 3666,
 4531,
 3068,
 5588,
 16237,
 5371,
 2554,
 1175,
 20642]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([9, 0, 2, 3, 0, 0, 2, 2, 1])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.018, 0.   , 0.004, 0.006, 0.   , 0.   , 0.004, 0.004, 0.002])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

19

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([5.719 , 3.3459, 2.3731, 1.8411, 1.5048, 1.2711, 1.102 , 0.9728,
       0.8702])

In [15]:
fe.sum()

19.0

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.283 , -0.1761, -0.1209, -0.0909, -0.0792, -0.0669, -0.054 ,
       -0.0472, -0.0438])

In [17]:
diferencia.sum()

-0.9619999999999999

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.88231526, 3.3459    , 0.05865897, 0.72948195, 1.5048    ,
       1.2711    , 0.73176407, 1.08464211, 0.01936111])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

10.628023466963919

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([5, 6, 3, 1, 0, 2, 0, 1, 1])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.01 , 0.012, 0.006, 0.002, 0.   , 0.004, 0.   , 0.002, 0.002])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

19

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([5.719 , 3.3459, 2.3731, 1.8411, 1.5048, 1.2711, 1.102 , 0.9728,
       0.8702])

In [29]:
fe.sum()

19.0

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.291 , -0.1641, -0.1189, -0.0949, -0.0792, -0.0629, -0.058 ,
       -0.0492, -0.0438])

In [31]:
diferencia.sum()

-0.9619999999999999

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([9.03936003e-02, 2.10533692e+00, 1.65607690e-01, 3.84253550e-01,
       1.50480000e+00, 4.17980655e-01, 1.10200000e+00, 7.60526316e-04,
       1.93611124e-02])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

5.7904940562069935

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([7, 2, 2, 1, 2, 2, 0, 2, 1])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.014, 0.004, 0.004, 0.002, 0.004, 0.004, 0.   , 0.004, 0.002])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

19

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([5.719 , 3.3459, 2.3731, 1.8411, 1.5048, 1.2711, 1.102 , 0.9728,
       0.8702])

In [43]:
fe.sum()

19.0

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.287 , -0.1721, -0.1209, -0.0949, -0.0752, -0.0629, -0.058 ,
       -0.0472, -0.0438])

In [45]:
diferencia.sum()

-0.9619999999999999

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [48]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.28693146, 0.54139299, 0.05865897, 0.38425355, 0.16296055,
       0.41798065, 1.102     , 1.08464211, 0.01936111])

# Partido Libre

In [49]:
x_2 = f0_fe_2_fe.sum()
x_2 

4.058181396073403

In [ ]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [ ]:
f0 = np.array(f0)
f0

In [ ]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

In [ ]:
benford = np.array(benford)
benford

In [ ]:
f0_tot=f0.sum()
f0_tot

In [ ]:
fe = benford*f0_tot

In [ ]:
fe 

In [ ]:
fe.sum()

In [ ]:
diferencia = fre_relativa - benford
diferencia 

In [ ]:
diferencia.sum()

In [ ]:
f0_fe= (f0-fe)

In [ ]:
f0_fe_2 = f0_fe*f0_fe

In [ ]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

# Total

In [ ]:
x_2 = f0_fe_2_fe.sum()
x_2 