In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1HeOZdGl5aMSIMShkHirP3s2xpCv3oxkx/export?format=csv")
df

PL   PN  LIBRE-PINU  TOTAL
0  18  108         246    379
1  25  171         229    430
2  74  304         311    694
3  22   75         179    280
4  31   90         184    332
5  23  129         173    330
6   6   14          54     76

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[18, 25, 74, 22, 31, 23, 6]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[108, 171, 304, 75, 90, 129, 14]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[246, 229, 311, 179, 184, 173, 54]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[379, 430, 694, 280, 332, 330, 76]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([1, 3, 1, 0, 0, 1, 1, 0, 0])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.006, 0.002, 0.   , 0.   , 0.002, 0.002, 0.   , 0.   ])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

7

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([2.107 , 1.2327, 0.8743, 0.6783, 0.5544, 0.4683, 0.406 , 0.3584,
       0.3206])

In [15]:
fe.sum()

6.999999999999999

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.299 , -0.1701, -0.1229, -0.0969, -0.0792, -0.0649, -0.056 ,
       -0.0512, -0.0458])

In [17]:
diferencia.sum()

-0.9859999999999999

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.58160845, 2.53374648, 0.01807216, 0.6783    , 0.5544    ,
       0.6036833 , 0.86905419, 0.3584    , 0.3206    ])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

6.517864580439965

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([4, 0, 1, 0, 0, 0, 1, 0, 1])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.008, 0.   , 0.002, 0.   , 0.   , 0.   , 0.002, 0.   , 0.002])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

7

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([2.107 , 1.2327, 0.8743, 0.6783, 0.5544, 0.4683, 0.406 , 0.3584,
       0.3206])

In [29]:
fe.sum()

6.999999999999999

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.293 , -0.1761, -0.1229, -0.0969, -0.0792, -0.0669, -0.056 ,
       -0.0512, -0.0438])

In [31]:
diferencia.sum()

-0.9859999999999999

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.70073517, 1.2327    , 0.01807216, 0.6783    , 0.5544    ,
       0.4683    , 0.86905419, 0.3584    , 1.43975159])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

7.31971310703104

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([3, 2, 1, 0, 1, 0, 0, 0, 0])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.006, 0.004, 0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

7

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([2.107 , 1.2327, 0.8743, 0.6783, 0.5544, 0.4683, 0.406 , 0.3584,
       0.3206])

In [43]:
fe.sum()

6.999999999999999

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.295 , -0.1721, -0.1229, -0.0969, -0.0772, -0.0669, -0.058 ,
       -0.0512, -0.0458])

In [45]:
diferencia.sum()

-0.9859999999999999

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [48]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.37847603, 0.47760955, 0.01807216, 0.6783    , 0.3581518 ,
       0.4683    , 0.406     , 0.3584    , 0.3206    ])

# Partido Libre

In [49]:
x_2 = f0_fe_2_fe.sum()
x_2 

3.4639095447571346

In [50]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [51]:
f0 = np.array(f0)
f0

array([0, 1, 3, 1, 0, 1, 1, 0, 0])

In [52]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.002, 0.006, 0.002, 0.   , 0.002, 0.002, 0.   , 0.   ])

In [53]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [54]:
f0_tot=f0.sum()
f0_tot

7

In [55]:
fe = benford*f0_tot

In [56]:
fe 

array([2.107 , 1.2327, 0.8743, 0.6783, 0.5544, 0.4683, 0.406 , 0.3584,
       0.3206])

In [57]:
fe.sum()

6.999999999999999

In [58]:
diferencia = fre_relativa - benford
diferencia 

array([-0.301 , -0.1741, -0.1189, -0.0949, -0.0792, -0.0649, -0.056 ,
       -0.0512, -0.0458])

In [59]:
diferencia.sum()

-0.9859999999999999

In [60]:
f0_fe= (f0-fe)

In [61]:
f0_fe_2 = f0_fe*f0_fe

In [62]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.107     , 0.04392739, 5.16824945, 0.15257392, 0.5544    ,
       0.6036833 , 0.86905419, 0.3584    , 0.3206    ])

# Total

In [63]:
x_2 = f0_fe_2_fe.sum()
x_2 

10.177888240896147