In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1qBodT6OuwCASM5HnehlvoQcll7Mb-Cpd/export?format=csv")
df

PL      PN  LIBRE-PINU   TOTAL
0   64996  200482      185099  456964
1     949    1605         305    2875
2    2722    4520        3187   10512
3    3425    4234         700    8411
4     409    3870        3773    8099
5    2287    5737        5562   13684
6     387    1050        1021    2481
7     703    1792         744    3266
8    2944    4201         751    7978
9     870    1960         971    3843
10    312    1763        1469    3609
11    615     993        1202    2908
12   1953    3092        1397    6486
13    324    3090        3285    6745
14   2248    2553         699    5517
15   2106    4067        2788    9012
16   1475    3079        1791    6419
17   1509     882         355    2766
18   1319    2343        1762    5448
19   2544    3737        1381    7702
20    565     828         413    1818
21   2581    2237        2546    7514
22   1433    2873        1477    5869
23   2387    6477        5844   14863
24    988    2427         768    4209
25   1559    4885        2349    8875
26   1369    2140        2331    5891
27   1079    1707         974    3814

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[64996,
 949,
 2722,
 3425,
 409,
 2287,
 387,
 703,
 2944,
 870,
 312,
 615,
 1953,
 324,
 2248,
 2106,
 1475,
 1509,
 1319,
 2544,
 565,
 2581,
 1433,
 2387,
 988,
 1559,
 1369,
 1079]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[200482,
 1605,
 4520,
 4234,
 3870,
 5737,
 1050,
 1792,
 4201,
 1960,
 1763,
 993,
 3092,
 3090,
 2553,
 4067,
 3079,
 882,
 2343,
 3737,
 828,
 2237,
 2873,
 6477,
 2427,
 4885,
 2140,
 1707]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[185099,
 305,
 3187,
 700,
 3773,
 5562,
 1021,
 744,
 751,
 971,
 1469,
 1202,
 1397,
 3285,
 699,
 2788,
 1791,
 355,
 1762,
 1381,
 413,
 2546,
 1477,
 5844,
 768,
 2349,
 2331,
 974]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[456964,
 2875,
 10512,
 8411,
 8099,
 13684,
 2481,
 3266,
 7978,
 3843,
 3609,
 2908,
 6486,
 6745,
 5517,
 9012,
 6419,
 2766,
 5448,
 7702,
 1818,
 7514,
 5869,
 14863,
 4209,
 8875,
 5891,
 3814]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([8, 8, 4, 1, 1, 2, 1, 1, 2])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.016, 0.016, 0.008, 0.002, 0.002, 0.004, 0.002, 0.002, 0.004])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

28

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([8.428 , 4.9308, 3.4972, 2.7132, 2.2176, 1.8732, 1.624 , 1.4336,
       1.2824])

In [15]:
fe.sum()

27.999999999999996

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.285 , -0.1601, -0.1169, -0.0949, -0.0772, -0.0629, -0.056 ,
       -0.0492, -0.0418])

In [17]:
diferencia.sum()

-0.9440000000000002

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.02173517, 1.91043819, 0.07228864, 1.08176848, 0.66853795,
       0.0085833 , 0.23976355, 0.13114464, 0.40155159])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

4.5358115161004315

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([6, 7, 5, 5, 1, 1, 0, 2, 1])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.012, 0.014, 0.01 , 0.01 , 0.002, 0.002, 0.   , 0.004, 0.002])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

28

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([8.428 , 4.9308, 3.4972, 2.7132, 2.2176, 1.8732, 1.624 , 1.4336,
       1.2824])

In [29]:
fe.sum()

27.999999999999996

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.289 , -0.1621, -0.1149, -0.0869, -0.0772, -0.0649, -0.058 ,
       -0.0472, -0.0438])

In [31]:
diferencia.sum()

-0.9439999999999998

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.69947603, 0.86833549, 0.645776  , 1.927412  , 0.66853795,
       0.40704583, 1.624     , 0.22377857, 0.0621879 ])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

7.126549773105333

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([9, 4, 5, 1, 2, 1, 4, 0, 2])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.018, 0.008, 0.01 , 0.002, 0.004, 0.002, 0.008, 0.   , 0.004])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

28

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([8.428 , 4.9308, 3.4972, 2.7132, 2.2176, 1.8732, 1.624 , 1.4336,
       1.2824])

In [43]:
fe.sum()

27.999999999999996

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.283 , -0.1681, -0.1149, -0.0949, -0.0752, -0.0649, -0.05  ,
       -0.0512, -0.0418])

In [45]:
diferencia.sum()

-0.944

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [48]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.03882107, 0.17570955, 0.645776  , 1.08176848, 0.0213518 ,
       0.40704583, 3.47621675, 1.4336    , 0.40155159])

# Partido Libre

In [49]:
x_2 = f0_fe_2_fe.sum()
x_2 

7.681841073058331

In [50]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [51]:
f0 = np.array(f0)
f0

array([4, 4, 4, 2, 4, 3, 3, 3, 1])

In [52]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.008, 0.008, 0.008, 0.004, 0.008, 0.006, 0.006, 0.006, 0.002])

In [53]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [54]:
f0_tot=f0.sum()
f0_tot

28

In [ ]:
fe = benford*f0_tot

In [ ]:
fe 

In [ ]:
fe.sum()

In [ ]:
diferencia = fre_relativa - benford
diferencia 

In [ ]:
diferencia.sum()

In [ ]:
f0_fe= (f0-fe)

In [ ]:
f0_fe_2 = f0_fe*f0_fe

In [ ]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

# Total

In [ ]:
x_2 = f0_fe_2_fe.sum()
x_2 