In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1g2rWOCPFg-A3Aws7x35_06FPevHvPyWF/export?format=csv")
df

PL    PN  LIBRE-PINU  TOTAL
0  1345  4575        4152  10551
1   823  1625         793   3335
2   188  1713         534   2484
3   106   807         778   1711
4   336  1274        1704   3365
5   676  1050         412   2173

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[1345, 823, 188, 106, 336, 676]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[4575, 1625, 1713, 807, 1274, 1050]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[4152, 793, 534, 778, 1704, 412]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[10551, 3335, 2484, 1711, 3365, 2173]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([3, 0, 1, 0, 0, 1, 0, 1, 0])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.006, 0.   , 0.002, 0.   , 0.   , 0.002, 0.   , 0.002, 0.   ])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

6

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([1.806 , 1.0566, 0.7494, 0.5814, 0.4752, 0.4014, 0.348 , 0.3072,
       0.2748])

In [15]:
fe.sum()

6.000000000000001

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.295 , -0.1761, -0.1229, -0.0969, -0.0792, -0.0649, -0.058 ,
       -0.0492, -0.0458])

In [17]:
diferencia.sum()

-0.9879999999999999

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.7893887 , 1.0566    , 0.08380085, 0.5814    , 0.4752    ,
       0.89268052, 0.348     , 1.56240833, 0.2748    ])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

6.064278409855165

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([4, 0, 0, 1, 0, 0, 0, 1, 0])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.008, 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.002, 0.   ])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

6

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([1.806 , 1.0566, 0.7494, 0.5814, 0.4752, 0.4014, 0.348 , 0.3072,
       0.2748])

In [29]:
fe.sum()

6.000000000000001

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.293 , -0.1761, -0.1249, -0.0949, -0.0792, -0.0669, -0.058 ,
       -0.0492, -0.0458])

In [31]:
diferencia.sum()

-0.9879999999999999

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.6653577 , 1.0566    , 0.7494    , 0.30138624, 0.4752    ,
       0.4014    , 0.348     , 1.56240833, 0.2748    ])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

7.834552270010411

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([1, 0, 0, 2, 1, 0, 2, 0, 0])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.   , 0.   , 0.004, 0.002, 0.   , 0.004, 0.   , 0.   ])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

6

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([1.806 , 1.0566, 0.7494, 0.5814, 0.4752, 0.4014, 0.348 , 0.3072,
       0.2748])

In [43]:
fe.sum()

6.000000000000001

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.299 , -0.1761, -0.1249, -0.0929, -0.0772, -0.0669, -0.054 ,
       -0.0512, -0.0458])

In [45]:
diferencia.sum()

-0.9879999999999999

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [48]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.35970986, 1.0566    , 0.7494    , 3.46134496, 0.5795771 ,
       0.4014    , 7.84225287, 0.3072    , 0.2748    ])

# Partido Libre

In [49]:
x_2 = f0_fe_2_fe.sum()
x_2 

15.032284794416075

In [50]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [51]:
f0 = np.array(f0)
f0

array([2, 2, 2, 0, 0, 0, 0, 0, 0])

In [52]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.004, 0.004, 0.004, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [53]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [54]:
f0_tot=f0.sum()
f0_tot

6

In [55]:
fe = benford*f0_tot

In [56]:
fe 

array([1.806 , 1.0566, 0.7494, 0.5814, 0.4752, 0.4014, 0.348 , 0.3072,
       0.2748])

In [57]:
fe.sum()

6.000000000000001

In [58]:
diferencia = fre_relativa - benford
diferencia 

array([-0.297 , -0.1721, -0.1209, -0.0969, -0.0792, -0.0669, -0.058 ,
       -0.0512, -0.0458])

In [59]:
diferencia.sum()

-0.9879999999999999

In [60]:
f0_fe= (f0-fe)

In [61]:
f0_fe_2 = f0_fe*f0_fe

In [62]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.02083942, 0.84232781, 2.08700342, 0.5814    , 0.4752    ,
       0.4014    , 0.348     , 0.3072    , 0.2748    ])

# Total

In [63]:
x_2 = f0_fe_2_fe.sum()
x_2 

5.338170646378672