In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1A_nJLWUA9iVtUslZhHGcYjYjfVBz6C6o/export?format=csv")
df

PL     PN  LIBRE-PINU  TOTAL
0   1260   3218        1932   6452
1    137   2042        1520   3724
2    250   3368        3460   7135
3    310   2526        1783   4660
4    792   1448         314   2582
5   5032  11280        4614  21187
6   1425   6484        3977  11959
7    106   1301         660   2089
8   1069   4013        1242   6417
9     59   1568        1715   3346
10   244   1238         535   2035
11  2047   3396        1627   7121
12   476   2000        1014   3551
13  1373   1876         344   3623
14    77   1509         783   2382
15  1949   5195        1412   8653
16   705   1894        1640   4315

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[1260,
 137,
 250,
 310,
 792,
 5032,
 1425,
 106,
 1069,
 59,
 244,
 2047,
 476,
 1373,
 77,
 1949,
 705]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[3218,
 2042,
 3368,
 2526,
 1448,
 11280,
 6484,
 1301,
 4013,
 1568,
 1238,
 3396,
 2000,
 1876,
 1509,
 5195,
 1894]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[1932,
 1520,
 3460,
 1783,
 314,
 4614,
 3977,
 660,
 1242,
 1715,
 535,
 1627,
 1014,
 344,
 783,
 1412,
 1640]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[6452,
 3724,
 7135,
 4660,
 2582,
 21187,
 11959,
 2089,
 6417,
 3346,
 2035,
 7121,
 3551,
 3623,
 2382,
 8653,
 4315]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([7, 3, 1, 1, 2, 0, 3, 0, 0])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.014, 0.006, 0.002, 0.002, 0.004, 0.   , 0.006, 0.   , 0.   ])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

17

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([5.117 , 2.9937, 2.1233, 1.6473, 1.3464, 1.1373, 0.986 , 0.8704,
       0.7786])

In [15]:
fe.sum()

17.0

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.287 , -0.1701, -0.1229, -0.0949, -0.0752, -0.0669, -0.052 ,
       -0.0512, -0.0458])

In [17]:
diferencia.sum()

-0.9659999999999999

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([6.92923393e-01, 1.32578415e-05, 5.94265007e-01, 2.54353967e-01,
       3.17285324e-01, 1.13730000e+00, 4.11378905e+00, 8.70400000e-01,
       7.78600000e-01])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

8.758929995331602

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([8, 3, 3, 1, 1, 1, 0, 0, 0])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.016, 0.006, 0.006, 0.002, 0.002, 0.002, 0.   , 0.   , 0.   ])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

17

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([5.117 , 2.9937, 2.1233, 1.6473, 1.3464, 1.1373, 0.986 , 0.8704,
       0.7786])

In [29]:
fe.sum()

17.0

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.285 , -0.1701, -0.1189, -0.0949, -0.0772, -0.0649, -0.058 ,
       -0.0512, -0.0458])

In [31]:
diferencia.sum()

-0.9659999999999999

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.62432851e+00, 1.32578415e-05, 3.61985066e-01, 2.54353967e-01,
       8.91213310e-02, 1.65754770e-02, 9.86000000e-01, 8.70400000e-01,
       7.78600000e-01])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

4.981377611402801

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([9, 0, 4, 1, 1, 1, 1, 0, 0])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.018, 0.   , 0.008, 0.002, 0.002, 0.002, 0.002, 0.   , 0.   ])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

17

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([5.117 , 2.9937, 2.1233, 1.6473, 1.3464, 1.1373, 0.986 , 0.8704,
       0.7786])

In [43]:
fe.sum()

17.0

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.283 , -0.1761, -0.1169, -0.0949, -0.0772, -0.0649, -0.056 ,
       -0.0512, -0.0458])

In [45]:
diferencia.sum()

-0.9659999999999999

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [ ]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

# Partido Libre

In [1]:
x_2 = f0_fe_2_fe.sum()
x_2 

NameError: name 'f0_fe_2_fe' is not defined

In [ ]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [ ]:
f0 = np.array(f0)
f0

In [ ]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

In [ ]:
benford = np.array(benford)
benford

In [ ]:
f0_tot=f0.sum()
f0_tot

In [ ]:
fe = benford*f0_tot

In [ ]:
fe 

In [ ]:
fe.sum()

In [ ]:
diferencia = fre_relativa - benford
diferencia 

In [ ]:
diferencia.sum()

In [ ]:
f0_fe= (f0-fe)

In [ ]:
f0_fe_2 = f0_fe*f0_fe

In [ ]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

# Total

In [ ]:
x_2 = f0_fe_2_fe.sum()
x_2 