In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1VA4yihruttcj_lAHd-RMrIzFJ8HnOipm/export?format=csv")
df

PL    PN  LIBRE-PINU  TOTAL
0  2427  4387        6245  13174
1   815  1138         722   2688
2  1348  1372        1360   4111
3   451   955         676   2105

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[2427, 815, 1348, 451]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[4387, 1138, 1372, 955]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[6245, 722, 1360, 676]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[13174, 2688, 4111, 2105]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([1, 1, 0, 1, 0, 0, 0, 1, 0])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.002, 0.   ])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

4

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([1.204 , 0.7044, 0.4996, 0.3876, 0.3168, 0.2676, 0.232 , 0.2048,
       0.1832])

In [15]:
fe.sum()

3.9999999999999996

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.299 , -0.1741, -0.1249, -0.0949, -0.0792, -0.0669, -0.058 ,
       -0.0492, -0.0458])

In [17]:
diferencia.sum()

-0.9919999999999999

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.03456478, 0.12404793, 0.4996    , 0.96757936, 0.3168    ,
       0.2676    , 0.232     , 3.0876125 , 0.1832    ])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

5.713004571532301

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([2, 0, 0, 1, 0, 0, 0, 0, 1])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.004, 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.002])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

4

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([1.204 , 0.7044, 0.4996, 0.3876, 0.3168, 0.2676, 0.232 , 0.2048,
       0.1832])

In [29]:
fe.sum()

3.9999999999999996

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.297 , -0.1761, -0.1249, -0.0949, -0.0792, -0.0669, -0.058 ,
       -0.0512, -0.0438])

In [31]:
diferencia.sum()

-0.9919999999999999

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.52625914, 0.7044    , 0.4996    , 0.96757936, 0.3168    ,
       0.2676    , 0.232     , 0.2048    , 3.64171528])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

7.360753780220538

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([1, 0, 0, 0, 0, 2, 1, 0, 0])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.   , 0.   , 0.   , 0.   , 0.004, 0.002, 0.   , 0.   ])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

4

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([1.204 , 0.7044, 0.4996, 0.3876, 0.3168, 0.2676, 0.232 , 0.2048,
       0.1832])

In [43]:
fe.sum()

3.9999999999999996

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.299 , -0.1761, -0.1249, -0.0969, -0.0792, -0.0629, -0.056 ,
       -0.0512, -0.0458])

In [45]:
diferencia.sum()

-0.9919999999999999

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [48]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.03456478,  0.7044    ,  0.4996    ,  0.3876    ,  0.3168    ,
       11.21528311,  2.54234483,  0.2048    ,  0.1832    ])

# Partido Libre

In [49]:
x_2 = f0_fe_2_fe.sum()
x_2 

16.088592720757447

In [50]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [51]:
f0 = np.array(f0)
f0

array([1, 2, 0, 1, 0, 0, 0, 0, 0])

In [52]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.004, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ])

In [53]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [54]:
f0_tot=f0.sum()
f0_tot

4

In [55]:
fe = benford*f0_tot

In [ ]:
fe 

In [ ]:
fe.sum()

In [ ]:
diferencia = fre_relativa - benford
diferencia 

In [ ]:
diferencia.sum()

In [ ]:
f0_fe= (f0-fe)

In [ ]:
f0_fe_2 = f0_fe*f0_fe

In [ ]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

# Total

In [ ]:
x_2 = f0_fe_2_fe.sum()
x_2 