In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1CfI-HjqE2wp51lWUJuBH6wSN1l0kQfvq/export?format=csv")
df

PL    PN  LIBRE-PINU  TOTAL
0   3274  6600        8141  18099
1    640  1712         638   3011
2    191  1165         318   1689
3    655   573         989   2230
4    884  1800         668   3380
5   1956  3534         408   5927
6    921   602         357   1883
7   2254  5961        3799  12103
8    249   421          93    776
9   1131  2057         709   3921
10   210   872         305   1397
11  1183  2018        1098   4331
12   388   464         277   1145
13   624  1891         913   3448
14  1638  2710         444   4835
15  1031  3145         746   4990
16  1561  2699         699   5051
17  2723  4604        1066   8427
18   845  2714         250   3842

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[3274,
 640,
 191,
 655,
 884,
 1956,
 921,
 2254,
 249,
 1131,
 210,
 1183,
 388,
 624,
 1638,
 1031,
 1561,
 2723,
 845]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[6600,
 1712,
 1165,
 573,
 1800,
 3534,
 602,
 5961,
 421,
 2057,
 872,
 2018,
 464,
 1891,
 2710,
 3145,
 2699,
 4604,
 2714]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[8141,
 638,
 318,
 989,
 668,
 408,
 357,
 3799,
 93,
 709,
 305,
 1098,
 277,
 913,
 444,
 746,
 699,
 1066,
 250]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[18099,
 3011,
 1689,
 2230,
 3380,
 5927,
 1883,
 12103,
 776,
 3921,
 1397,
 4331,
 1145,
 3448,
 4835,
 4990,
 5051,
 8427,
 3842]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([7, 4, 2, 0, 0, 3, 0, 2, 1])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.014, 0.008, 0.004, 0.   , 0.   , 0.006, 0.   , 0.004, 0.002])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

19

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([5.719 , 3.3459, 2.3731, 1.8411, 1.5048, 1.2711, 1.102 , 0.9728,
       0.8702])

In [15]:
fe.sum()

19.0

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.287 , -0.1681, -0.1209, -0.0969, -0.0792, -0.0609, -0.058 ,
       -0.0472, -0.0438])

In [17]:
diferencia.sum()

-0.9619999999999999

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.28693146, 0.12787197, 0.05865897, 1.8411    , 1.5048    ,
       2.35158147, 1.102     , 1.08464211, 0.01936111])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

8.376947086123545

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([4, 5, 2, 3, 2, 2, 0, 1, 0])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.008, 0.01 , 0.004, 0.006, 0.004, 0.004, 0.   , 0.002, 0.   ])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

19

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([5.719 , 3.3459, 2.3731, 1.8411, 1.5048, 1.2711, 1.102 , 0.9728,
       0.8702])

In [29]:
fe.sum()

19.0

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.293 , -0.1661, -0.1209, -0.0909, -0.0752, -0.0629, -0.058 ,
       -0.0492, -0.0458])

In [31]:
diferencia.sum()

-0.9619999999999999

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([5.16691904e-01, 8.17731196e-01, 5.86589735e-02, 7.29481946e-01,
       1.62960553e-01, 4.17980655e-01, 1.10200000e+00, 7.60526316e-04,
       8.70200000e-01])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

4.6764657534036225

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([2, 2, 4, 2, 0, 3, 2, 1, 3])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.004, 0.004, 0.008, 0.004, 0.   , 0.006, 0.004, 0.002, 0.006])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

19

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([5.719 , 3.3459, 2.3731, 1.8411, 1.5048, 1.2711, 1.102 , 0.9728,
       0.8702])

In [43]:
fe.sum()

19.0

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.297 , -0.1721, -0.1169, -0.0929, -0.0792, -0.0609, -0.054 ,
       -0.0492, -0.0398])

In [45]:
diferencia.sum()

-0.962

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [48]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.41842298e+00, 5.41392991e-01, 1.11533589e+00, 1.37141980e-02,
       1.50480000e+00, 2.35158147e+00, 7.31764065e-01, 7.60526316e-04,
       5.21265001e+00])

# Partido Libre

In [49]:
x_2 = f0_fe_2_fe.sum()
x_2 

13.890422135362524

In [50]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [51]:
f0 = np.array(f0)
f0

array([6, 1, 5, 3, 2, 0, 1, 1, 0])

In [52]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.012, 0.002, 0.01 , 0.006, 0.004, 0.   , 0.002, 0.002, 0.   ])

In [53]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [54]:
f0_tot=f0.sum()
f0_tot

19

In [55]:
fe = benford*f0_tot

In [56]:
fe 

array([5.719 , 3.3459, 2.3731, 1.8411, 1.5048, 1.2711, 1.102 , 0.9728,
       0.8702])

In [57]:
fe.sum()

19.0

In [58]:
diferencia = fre_relativa - benford
diferencia 

array([-0.289 , -0.1741, -0.1149, -0.0909, -0.0752, -0.0669, -0.056 ,
       -0.0492, -0.0458])

In [59]:
diferencia.sum()

-0.9619999999999999

In [60]:
f0_fe= (f0-fe)

In [61]:
f0_fe_2 = f0_fe*f0_fe

In [62]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.38067844e-02, 1.64477325e+00, 2.90784358e+00, 7.29481946e-01,
       1.62960553e-01, 1.27110000e+00, 9.44101633e-03, 7.60526316e-04,
       8.70200000e-01])

# Total

In [63]:
x_2 = f0_fe_2_fe.sum()
x_2 

7.610367657722747