In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1HCvzhYjTDoj04gFf14v09zri_ZcSogTe/export?format=csv")
df

PL     PN  LIBRE-PINU  TOTAL
0   1887  13367        4992  20364
1    903   2235         893   4069
2     36   1853        1886   3800
3    151   2303         757   3241
4    839   4340        2988   8212
5    415   2887         966   4333
6    753   2092         912   3783
7    857   2226         534   3633
8   1459   6169        2514  10254
9    243   2714        1895   4873
10   372   3767        2910   7085
11    32   2251        1625   3918
12   420   9552        6145  16216
13   178   1159        1263   2624
14   132   3078        1359   4638
15   365   3947        1748   6187
16   118   2260        1935   4342
17   263    730         363   1378
18  1290   4399        1186   6911
19   328   3561        2411   6369
20   457   2874        1107   4494
21  1316   1861         417   3605
22   154   2279        1512   3973
23    37   1153         445   1752
24    48   2415         929   3407
25    39   1719         395   2165
26    24    812         971   1822
27   439   1153        1386   2998

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[1887,
 903,
 36,
 151,
 839,
 415,
 753,
 857,
 1459,
 243,
 372,
 32,
 420,
 178,
 132,
 365,
 118,
 263,
 1290,
 328,
 457,
 1316,
 154,
 37,
 48,
 39,
 24,
 439]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[13367,
 2235,
 1853,
 2303,
 4340,
 2887,
 2092,
 2226,
 6169,
 2714,
 3767,
 2251,
 9552,
 1159,
 3078,
 3947,
 2260,
 730,
 4399,
 3561,
 2874,
 1861,
 2279,
 1153,
 2415,
 1719,
 812,
 1153]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[4992,
 893,
 1886,
 757,
 2988,
 966,
 912,
 534,
 2514,
 1895,
 2910,
 1625,
 6145,
 1263,
 1359,
 1748,
 1935,
 363,
 1186,
 2411,
 1107,
 417,
 1512,
 445,
 929,
 395,
 971,
 1386]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[20364,
 4069,
 3800,
 3241,
 8212,
 4333,
 3783,
 3633,
 10254,
 4873,
 7085,
 3918,
 16216,
 2624,
 4638,
 6187,
 4342,
 1378,
 6911,
 6369,
 4494,
 3605,
 3973,
 1752,
 3407,
 2165,
 1822,
 2998]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([9, 3, 7, 5, 0, 0, 1, 2, 1])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.018, 0.006, 0.014, 0.01 , 0.   , 0.   , 0.002, 0.004, 0.002])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

28

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([8.428 , 4.9308, 3.4972, 2.7132, 2.2176, 1.8732, 1.624 , 1.4336,
       1.2824])

In [15]:
fe.sum()

27.999999999999996

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.283 , -0.1701, -0.1109, -0.0869, -0.0792, -0.0669, -0.056 ,
       -0.0472, -0.0438])

In [17]:
diferencia.sum()

-0.9439999999999998

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.03882107, 0.75606162, 3.50840897, 1.927412  , 2.2176    ,
       1.8732    , 0.23976355, 0.22377857, 0.0621879 ])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

10.847233677129292

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([ 7, 11,  4,  2,  0,  1,  1,  1,  1])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.014, 0.022, 0.008, 0.004, 0.   , 0.002, 0.002, 0.002, 0.002])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

28

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([8.428 , 4.9308, 3.4972, 2.7132, 2.2176, 1.8732, 1.624 , 1.4336,
       1.2824])

In [29]:
fe.sum()

27.999999999999996

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.287 , -0.1541, -0.1169, -0.0929, -0.0792, -0.0649, -0.056 ,
       -0.0492, -0.0438])

In [31]:
diferencia.sum()

-0.9440000000000001

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.24195349, 7.47042846, 0.07228864, 0.18747392, 2.2176    ,
       0.40704583, 0.23976355, 0.13114464, 0.0621879 ])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

11.029886421338272

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([11,  4,  2,  3,  1,  1,  1,  1,  4])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.022, 0.008, 0.004, 0.006, 0.002, 0.002, 0.002, 0.002, 0.008])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

28

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([8.428 , 4.9308, 3.4972, 2.7132, 2.2176, 1.8732, 1.624 , 1.4336,
       1.2824])

In [43]:
fe.sum()

27.999999999999996

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.279 , -0.1681, -0.1209, -0.0909, -0.0772, -0.0649, -0.056 ,
       -0.0492, -0.0378])

In [45]:
diferencia.sum()

-0.944

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [48]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.78490555, 0.17570955, 0.64097216, 0.03031632, 0.66853795,
       0.40704583, 0.23976355, 0.13114464, 5.75900636])

# Partido Libre

In [49]:
x_2 = f0_fe_2_fe.sum()
x_2 

8.83740191085111

In [50]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [51]:
f0 = np.array(f0)
f0

array([5, 4, 8, 6, 0, 3, 1, 1, 0])

In [52]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.01 , 0.008, 0.016, 0.012, 0.   , 0.006, 0.002, 0.002, 0.   ])

In [53]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [54]:
f0_tot=f0.sum()
f0_tot

28

In [55]:
fe = benford*f0_tot

In [56]:
fe 

array([8.428 , 4.9308, 3.4972, 2.7132, 2.2176, 1.8732, 1.624 , 1.4336,
       1.2824])

In [57]:
fe.sum()

27.999999999999996

In [58]:
diferencia = fre_relativa - benford
diferencia 

array([-0.291 , -0.1681, -0.1089, -0.0849, -0.0792, -0.0609, -0.056 ,
       -0.0492, -0.0458])

In [59]:
diferencia.sum()

-0.9439999999999998

In [60]:
f0_fe= (f0-fe)

In [61]:
f0_fe_2 = f0_fe*f0_fe

In [62]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.3943028 , 0.17570955, 5.79755457, 3.98166528, 2.2176    ,
       0.67781243, 0.23976355, 0.13114464, 1.2824    ])

# Total

In [63]:
x_2 = f0_fe_2_fe.sum()
x_2 

15.897952816141139