In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1waXfL5jUCgEbteG-sf1mOPn_8jMDTHDJ/export?format=csv")
df

PL      PN  LIBRE-PINU   TOTAL
0    20194   52450       73661  147470
1    10756   39302       56979  107783
2    29302   88557       71035  190202
3    30967   68987       60147  161366
4    55840  161123      271047  492773
5    27963   88524       84566  202371
6    41509   89629       61968  194545
7   106058  278624      234944  627578
8     3474   11044        8373   23619
9    17311   54356       28572  101231
10    5041    7852        9003   22078
11   22358   45542       21918   90485
12   13555   89156       46444  150446
13   17302   31338       22630   71830
14   26146   90767       81777  200417
15   10739   96205       98135  206163
16   19307   37000       31936   88656
17   26166   79541       95931  203170
18     199     891        1376    2521

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[20194,
 10756,
 29302,
 30967,
 55840,
 27963,
 41509,
 106058,
 3474,
 17311,
 5041,
 22358,
 13555,
 17302,
 26146,
 10739,
 19307,
 26166,
 199]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[52450,
 39302,
 88557,
 68987,
 161123,
 88524,
 89629,
 278624,
 11044,
 54356,
 7852,
 45542,
 89156,
 31338,
 90767,
 96205,
 37000,
 79541,
 891]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[73661,
 56979,
 71035,
 60147,
 271047,
 84566,
 61968,
 234944,
 8373,
 28572,
 9003,
 21918,
 46444,
 22630,
 81777,
 98135,
 31936,
 95931,
 1376]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[147470,
 107783,
 190202,
 161366,
 492773,
 202371,
 194545,
 627578,
 23619,
 101231,
 22078,
 90485,
 150446,
 71830,
 200417,
 206163,
 88656,
 203170,
 2521]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([8, 6, 2, 1, 2, 0, 0, 0, 0])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.016, 0.012, 0.004, 0.002, 0.004, 0.   , 0.   , 0.   , 0.   ])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

19

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([5.719 , 3.3459, 2.3731, 1.8411, 1.5048, 1.2711, 1.102 , 0.9728,
       0.8702])

In [15]:
fe.sum()

19.0

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.285 , -0.1641, -0.1209, -0.0949, -0.0752, -0.0669, -0.058 ,
       -0.0512, -0.0458])

In [17]:
diferencia.sum()

-0.9619999999999999

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.90976762, 2.10533692, 0.05865897, 0.38425355, 0.16296055,
       1.2711    , 1.102     , 0.9728    , 0.8702    ])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

7.837077615417676

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([2, 1, 3, 1, 2, 1, 2, 5, 2])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.004, 0.002, 0.006, 0.002, 0.004, 0.002, 0.004, 0.01 , 0.004])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

19

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([5.719 , 3.3459, 2.3731, 1.8411, 1.5048, 1.2711, 1.102 , 0.9728,
       0.8702])

In [29]:
fe.sum()

19.0

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.297 , -0.1741, -0.1189, -0.0949, -0.0752, -0.0649, -0.054 ,
       -0.0412, -0.0418])

In [31]:
diferencia.sum()

-0.962

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 2.41842298,  1.64477325,  0.16560769,  0.38425355,  0.16296055,
        0.05782016,  0.73176407, 16.67181316,  1.46684445])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

23.704259853089113

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([1, 5, 1, 1, 1, 2, 2, 3, 3])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.01 , 0.002, 0.002, 0.002, 0.004, 0.004, 0.006, 0.006])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

19

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([5.719 , 3.3459, 2.3731, 1.8411, 1.5048, 1.2711, 1.102 , 0.9728,
       0.8702])

In [43]:
fe.sum()

19.0

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.299 , -0.1661, -0.1229, -0.0949, -0.0772, -0.0629, -0.054 ,
       -0.0452, -0.0398])

In [45]:
diferencia.sum()

-0.962

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [48]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([3.89385574, 0.8177312 , 0.79448974, 0.38425355, 0.16934014,
       0.41798065, 0.73176407, 4.22444474, 5.21265001])

# Partido Libre

In [49]:
x_2 = f0_fe_2_fe.sum()
x_2 

16.646509839727887

In [50]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [51]:
f0 = np.array(f0)
f0

array([7, 7, 0, 1, 0, 1, 1, 1, 1])

In [52]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.014, 0.014, 0.   , 0.002, 0.   , 0.002, 0.002, 0.002, 0.002])

In [53]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [54]:
f0_tot=f0.sum()
f0_tot

19

In [55]:
fe = benford*f0_tot

In [56]:
fe 

array([5.719 , 3.3459, 2.3731, 1.8411, 1.5048, 1.2711, 1.102 , 0.9728,
       0.8702])

In [57]:
fe.sum()

19.0

In [58]:
diferencia = fre_relativa - benford
diferencia 

array([-0.287 , -0.1621, -0.1249, -0.0949, -0.0792, -0.0649, -0.056 ,
       -0.0492, -0.0438])

In [59]:
diferencia.sum()

-0.9619999999999999

In [60]:
f0_fe= (f0-fe)

In [61]:
f0_fe_2 = f0_fe*f0_fe

In [62]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.86931457e-01, 3.99068914e+00, 2.37310000e+00, 3.84253550e-01,
       1.50480000e+00, 5.78201636e-02, 9.44101633e-03, 7.60526316e-04,
       1.93611124e-02])

# Total

In [63]:
x_2 = f0_fe_2_fe.sum()
x_2 

8.627156969655909