In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1Qmdl_97d9SUNMvGmyKckK405QL-Mwbjr/export?format=csv")
df

PL    PN  LIBRE-PINU  TOTAL
0   2289  4237        4733  11325
1   2479  4210        1325   8072
2    156  1293        1011   2498
3   1160  1087         170   2430
4    977  1054         486   2526
5    938  1455         782   3182
6    870  2123        1779   4799
7    529  1241        1022   2814
8    258  1756         609   2654
9   2003  1033         372   3433
10   469  2023        1647   4161
11   582  1219         458   2274
12  2436  3846        3047   9369
13   541  1106        1118   2867
14   713  2256        2175   5199
15   902  1399        1896   4227

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[2289,
 2479,
 156,
 1160,
 977,
 938,
 870,
 529,
 258,
 2003,
 469,
 582,
 2436,
 541,
 713,
 902]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[4237,
 4210,
 1293,
 1087,
 1054,
 1455,
 2123,
 1241,
 1756,
 1033,
 2023,
 1219,
 3846,
 1106,
 2256,
 1399]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[4733,
 1325,
 1011,
 170,
 486,
 782,
 1779,
 1022,
 609,
 372,
 1647,
 458,
 3047,
 1118,
 2175,
 1896]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[11325,
 8072,
 2498,
 2430,
 2526,
 3182,
 4799,
 2814,
 2654,
 3433,
 4161,
 2274,
 9369,
 2867,
 5199,
 4227]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([2, 5, 0, 1, 3, 0, 1, 1, 3])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.004, 0.01 , 0.   , 0.002, 0.006, 0.   , 0.002, 0.002, 0.006])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

16

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([4.816 , 2.8176, 1.9984, 1.5504, 1.2672, 1.0704, 0.928 , 0.8192,
       0.7328])

In [15]:
fe.sum()

15.999999999999998

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.297 , -0.1661, -0.1249, -0.0949, -0.0732, -0.0669, -0.056 ,
       -0.0492, -0.0398])

In [17]:
diferencia.sum()

-0.968

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.64656478e+00, 1.69039955e+00, 1.99840000e+00, 1.95394840e-01,
       2.36947273e+00, 1.07040000e+00, 5.58620690e-03, 3.99031250e-02,
       7.01445939e+00])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

16.030580617622665

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([10,  3,  1,  2,  0,  0,  0,  0,  0])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.02 , 0.006, 0.002, 0.004, 0.   , 0.   , 0.   , 0.   , 0.   ])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

16

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([4.816 , 2.8176, 1.9984, 1.5504, 1.2672, 1.0704, 0.928 , 0.8192,
       0.7328])

In [29]:
fe.sum()

15.999999999999998

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.281 , -0.1701, -0.1229, -0.0929, -0.0792, -0.0669, -0.058 ,
       -0.0512, -0.0458])

In [31]:
diferencia.sum()

-0.9679999999999999

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([5.5801196 , 0.01180784, 0.49880032, 0.13037936, 1.2672    ,
       1.0704    , 0.928     , 0.8192    , 0.7328    ])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

11.038707118206785

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [ ]:
f0 = np.array(f0)
f0

In [ ]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

In [ ]:
benford = np.array(benford)
benford

In [ ]:
f0_tot=f0.sum()
f0_tot

In [ ]:
fe = benford*f0_tot

In [ ]:
fe 

In [ ]:
fe.sum()

In [ ]:
diferencia = fre_relativa - benford
diferencia 

In [ ]:
diferencia.sum()

In [ ]:
f0_fe= (f0-fe)

In [ ]:
f0_fe_2 = f0_fe*f0_fe

In [ ]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

# Partido Libre

In [ ]:
x_2 = f0_fe_2_fe.sum()
x_2 

In [ ]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [ ]:
f0 = np.array(f0)
f0

In [ ]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

In [ ]:
benford = np.array(benford)
benford

In [ ]:
f0_tot=f0.sum()
f0_tot

In [ ]:
fe = benford*f0_tot

In [ ]:
fe 

In [ ]:
fe.sum()

In [ ]:
diferencia = fre_relativa - benford
diferencia 

In [ ]:
diferencia.sum()

In [ ]:
f0_fe= (f0-fe)

In [ ]:
f0_fe_2 = f0_fe*f0_fe

In [ ]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

# Total

In [ ]:
x_2 = f0_fe_2_fe.sum()
x_2 