In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1ucG1-hX98WhlsNOkqBAoqpj3WNPcF0dc/export?format=csv")
df

PL     PN  LIBRE-PINU  TOTAL
0   6112  16850       15339  38531
1    886   5786        3291  10023
2   3902  13914       18715  36778
3    508   2314        1602   4458
4   1776   4875        4665  11392
5     52   1528        1421   3029
6   1158   1454        1155   3814
7   1423   3997        2532   7995
8    698   1918        1548   4194
9    621   2990        1870   5514
10    83   2178        3026   5319
11   722   1568        1170   3496
12   516   1684        1620   3876
13   107   1701        1424   3328
14   254   2228        2615   5124
15   271   2242        1564   4093
16  1766   3957        3366   9167
17  1071   2963        1210   5275
18   481   4523        3504   8557
19   207   2226        2888   5345
20   183   2171        2240   4613
21   753   2218        1629   4668
22  2596   5482        3383  11828

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[6112,
 886,
 3902,
 508,
 1776,
 52,
 1158,
 1423,
 698,
 621,
 83,
 722,
 516,
 107,
 254,
 271,
 1766,
 1071,
 481,
 207,
 183,
 753,
 2596]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[16850,
 5786,
 13914,
 2314,
 4875,
 1528,
 1454,
 3997,
 1918,
 2990,
 2178,
 1568,
 1684,
 1701,
 2228,
 2242,
 3957,
 2963,
 4523,
 2226,
 2171,
 2218,
 5482]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[15339,
 3291,
 18715,
 1602,
 4665,
 1421,
 1155,
 2532,
 1548,
 1870,
 3026,
 1170,
 1620,
 1424,
 2615,
 1564,
 3366,
 1210,
 3504,
 2888,
 2240,
 1629,
 3383]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[38531,
 10023,
 36778,
 4458,
 11392,
 3029,
 3814,
 7995,
 4194,
 5514,
 5319,
 3496,
 3876,
 3328,
 5124,
 4093,
 9167,
 5275,
 8557,
 5345,
 4613,
 4668,
 11828]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([7, 4, 1, 1, 3, 3, 2, 2, 0])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.014, 0.008, 0.002, 0.002, 0.006, 0.006, 0.004, 0.004, 0.   ])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

23

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([6.923 , 4.0503, 2.8727, 2.2287, 1.8216, 1.5387, 1.334 , 1.1776,
       1.0534])

In [15]:
fe.sum()

23.0

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.287 , -0.1681, -0.1229, -0.0949, -0.0732, -0.0609, -0.054 ,
       -0.0472, -0.0458])

In [17]:
diferencia.sum()

-0.9539999999999998

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([8.56420627e-04, 6.24667309e-04, 1.22080457e+00, 6.77392063e-01,
       7.62311462e-01, 1.38779339e+00, 3.32500750e-01, 5.74339130e-01,
       1.05340000e+00])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

6.0100224542209455

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([8, 9, 2, 2, 2, 0, 0, 0, 0])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.016, 0.018, 0.004, 0.004, 0.004, 0.   , 0.   , 0.   , 0.   ])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

23

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([6.923 , 4.0503, 2.8727, 2.2287, 1.8216, 1.5387, 1.334 , 1.1776,
       1.0534])

In [29]:
fe.sum()

23.0

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.285 , -0.1581, -0.1209, -0.0929, -0.0752, -0.0669, -0.058 ,
       -0.0512, -0.0458])

In [31]:
diferencia.sum()

-0.9540000000000001

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.16754716, 6.04881863, 0.26511828, 0.02346825, 0.01747176,
       1.5387    , 1.334     , 1.1776    , 1.0534    ])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

11.626124083975737

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([13,  4,  5,  1,  0,  0,  0,  0,  0])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.026, 0.008, 0.01 , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

23

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([6.923 , 4.0503, 2.8727, 2.2287, 1.8216, 1.5387, 1.334 , 1.1776,
       1.0534])

In [43]:
fe.sum()

23.0

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.275 , -0.1681, -0.1149, -0.0949, -0.0792, -0.0669, -0.058 ,
       -0.0512, -0.0458])

In [45]:
diferencia.sum()

-0.9539999999999998

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [48]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([5.33438235e+00, 6.24667309e-04, 1.57531427e+00, 6.77392063e-01,
       1.82160000e+00, 1.53870000e+00, 1.33400000e+00, 1.17760000e+00,
       1.05340000e+00])

# Partido Libre

In [49]:
x_2 = f0_fe_2_fe.sum()
x_2 

14.513013343964072

In [50]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [51]:
f0 = np.array(f0)
f0

array([3, 0, 7, 5, 5, 0, 1, 1, 1])

In [52]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.006, 0.   , 0.014, 0.01 , 0.01 , 0.   , 0.002, 0.002, 0.002])

In [53]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [54]:
f0_tot=f0.sum()
f0_tot

23

In [55]:
fe = benford*f0_tot

In [56]:
fe 

array([6.923 , 4.0503, 2.8727, 2.2287, 1.8216, 1.5387, 1.334 , 1.1776,
       1.0534])

In [57]:
fe.sum()

23.0

In [58]:
diferencia = fre_relativa - benford
diferencia 

array([-0.295 , -0.1761, -0.1109, -0.0869, -0.0692, -0.0669, -0.056 ,
       -0.0492, -0.0438])

In [59]:
diferencia.sum()

-0.9539999999999998

In [60]:
f0_fe= (f0-fe)

In [61]:
f0_fe_2 = f0_fe*f0_fe

In [62]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.22301444e+00, 4.05030000e+00, 5.92982396e+00, 3.44600157e+00,
       5.54579851e+00, 1.53870000e+00, 8.36251874e-02, 2.67847826e-02,
       2.70700589e-03])

# Total

In [63]:
x_2 = f0_fe_2_fe.sum()
x_2 

22.846755453285734