In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1MzgxfBh-cXzeZe-OZBJY1V2-J-jDdK_t/export?format=csv")
df

PL    PN  LIBRE-PINU  TOTAL
0   568  9585       11371  21650
1    93  3425        3389   6926
2   193  4354        3890   8474
3   276  3483        4167   7985
4    67  1613        1824   3515
5   433  5322        5795  11590
6   391  2906        2215   5540
7   683  1620        1978   4302
8   180  1608        1229   3029
9   177  2246        2776   5227
10  721   804        1962   3502
11  288  2793        1493   4590
12  421  5648        7752  13910
13  191  2517        1633   4366
14  296  1754        1688   3763
15  445  2831        2730   6023
16  388  2763        1748   4945
17  959  7457        7042  15554
18  370  2416        1037   3838
19  436  6354        5695  12553
20  660  2582        3488   6786
21  388  3586        3827   7828
22  304  3973        3215   7509
23   51  1375         765   2205
24  223   822        1241   2302
25  601  4344        4891   9897
26  701  5030        5650  11436
27  235  2994        3644   6918

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[568,
 93,
 193,
 276,
 67,
 433,
 391,
 683,
 180,
 177,
 721,
 288,
 421,
 191,
 296,
 445,
 388,
 959,
 370,
 436,
 660,
 388,
 304,
 51,
 223,
 601,
 701,
 235]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[9585,
 3425,
 4354,
 3483,
 1613,
 5322,
 2906,
 1620,
 1608,
 2246,
 804,
 2793,
 5648,
 2517,
 1754,
 2831,
 2763,
 7457,
 2416,
 6354,
 2582,
 3586,
 3973,
 1375,
 822,
 4344,
 5030,
 2994]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[11371,
 3389,
 3890,
 4167,
 1824,
 5795,
 2215,
 1978,
 1229,
 2776,
 1962,
 1493,
 7752,
 1633,
 1688,
 2730,
 1748,
 7042,
 1037,
 5695,
 3488,
 3827,
 3215,
 765,
 1241,
 4891,
 5650,
 3644]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[21650,
 6926,
 8474,
 7985,
 3515,
 11590,
 5540,
 4302,
 3029,
 5227,
 3502,
 4590,
 13910,
 4366,
 3763,
 6023,
 4945,
 15554,
 3838,
 12553,
 6786,
 7828,
 7509,
 2205,
 2302,
 9897,
 11436,
 6918]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([4, 5, 5, 4, 2, 4, 2, 0, 2])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.008, 0.01 , 0.01 , 0.008, 0.004, 0.008, 0.004, 0.   , 0.004])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

28

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([8.428 , 4.9308, 3.4972, 2.7132, 2.2176, 1.8732, 1.624 , 1.4336,
       1.2824])

In [15]:
fe.sum()

27.999999999999996

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.293 , -0.1661, -0.1149, -0.0889, -0.0752, -0.0589, -0.054 ,
       -0.0512, -0.0418])

In [17]:
diferencia.sum()

-0.944

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.32643379e+00, 9.71168979e-04, 6.45776004e-01, 6.10295680e-01,
       2.13518038e-02, 2.41473321e+00, 8.70541872e-02, 1.43360000e+00,
       4.01551591e-01])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

7.941767432059218

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([5, 9, 4, 2, 3, 1, 1, 2, 1])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.01 , 0.018, 0.008, 0.004, 0.006, 0.002, 0.002, 0.004, 0.002])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

28

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([8.428 , 4.9308, 3.4972, 2.7132, 2.2176, 1.8732, 1.624 , 1.4336,
       1.2824])

In [29]:
fe.sum()

27.999999999999996

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.291 , -0.1581, -0.1169, -0.0929, -0.0732, -0.0649, -0.056 ,
       -0.0472, -0.0438])

In [31]:
diferencia.sum()

-0.9440000000000001

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.3943028 , 3.35815459, 0.07228864, 0.18747392, 0.27604156,
       0.40704583, 0.23976355, 0.22377857, 0.0621879 ])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

6.221037349803148

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([11,  3,  6,  2,  3,  0,  3,  0,  0])

In [ ]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

In [ ]:
benford = np.array(benford)
benford

In [ ]:
f0_tot=f0.sum()
f0_tot

In [ ]:
fe = benford*f0_tot

In [ ]:
fe 

In [ ]:
fe.sum()

In [ ]:
diferencia = fre_relativa - benford
diferencia 

In [ ]:
diferencia.sum()

In [ ]:
f0_fe= (f0-fe)

In [ ]:
f0_fe_2 = f0_fe*f0_fe

In [ ]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

# Partido Libre

In [ ]:
x_2 = f0_fe_2_fe.sum()
x_2 

In [ ]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [ ]:
f0 = np.array(f0)
f0

In [ ]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

In [ ]:
benford = np.array(benford)
benford

In [ ]:
f0_tot=f0.sum()
f0_tot

In [ ]:
fe = benford*f0_tot

In [ ]:
fe 

In [ ]:
fe.sum()

In [ ]:
diferencia = fre_relativa - benford
diferencia 

In [ ]:
diferencia.sum()

In [ ]:
f0_fe= (f0-fe)

In [ ]:
f0_fe_2 = f0_fe*f0_fe

In [ ]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

# Total

In [ ]:
x_2 = f0_fe_2_fe.sum()
x_2 