In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1T8hvA2MIH2jYE-ZkLISP37-0domuyVo4/export?format=csv")
df

PL     PN  LIBRE-PINU  TOTAL
0  6432  10367        9051  25996
1  1449   1841        1216   4525
2  2764   3047        1749   7580
3   949   1737         966   3666
4   420   1125         596   2144
5  1363   3472        2912   7774
6  2218   4635        3979  10876
7   616   2613        2448   5731
8  3096   8163        9019  20364

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[6432, 1449, 2764, 949, 420, 1363, 2218, 616, 3096]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[10367, 1841, 3047, 1737, 1125, 3472, 4635, 2613, 8163]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[9051, 1216, 1749, 966, 596, 2912, 3979, 2448, 9019]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[25996, 4525, 7580, 3666, 2144, 7774, 10876, 5731, 20364]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([2, 2, 1, 1, 0, 2, 0, 0, 1])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.004, 0.004, 0.002, 0.002, 0.   , 0.004, 0.   , 0.   , 0.002])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

9

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([2.709 , 1.5849, 1.1241, 0.8721, 0.7128, 0.6021, 0.522 , 0.4608,
       0.4122])

In [15]:
fe.sum()

9.0

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.297 , -0.1721, -0.1229, -0.0949, -0.0792, -0.0629, -0.058 ,
       -0.0512, -0.0438])

In [17]:
diferencia.sum()

-0.9819999999999999

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.18555962, 0.10871854, 0.01370057, 0.01875749, 0.7128    ,
       3.24551472, 0.522     , 0.4608    , 0.83820679])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

6.106057724275355

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([4, 1, 2, 1, 0, 0, 0, 1, 0])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.008, 0.002, 0.004, 0.002, 0.   , 0.   , 0.   , 0.002, 0.   ])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

9

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([2.709 , 1.5849, 1.1241, 0.8721, 0.7128, 0.6021, 0.522 , 0.4608,
       0.4122])

In [29]:
fe.sum()

9.0

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.293 , -0.1741, -0.1209, -0.0949, -0.0792, -0.0669, -0.058 ,
       -0.0492, -0.0458])

In [31]:
diferencia.sum()

-0.9819999999999999

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.61523846, 0.21585463, 0.68250228, 0.01875749, 0.7128    ,
       0.6021    , 0.522     , 0.63093889, 0.4122    ])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

4.412391758412855

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([2, 2, 1, 0, 1, 0, 0, 0, 3])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.004, 0.004, 0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.006])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

9

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([2.709 , 1.5849, 1.1241, 0.8721, 0.7128, 0.6021, 0.522 , 0.4608,
       0.4122])

In [43]:
fe.sum()

9.0

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.297 , -0.1721, -0.1229, -0.0969, -0.0772, -0.0669, -0.058 ,
       -0.0512, -0.0398])

In [45]:
diferencia.sum()

-0.982

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [48]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.85559616e-01, 1.08718537e-01, 1.37005693e-02, 8.72100000e-01,
       1.15718070e-01, 6.02100000e-01, 5.22000000e-01, 4.60800000e-01,
       1.62462611e+01])

# Partido Libre

In [49]:
x_2 = f0_fe_2_fe.sum()
x_2 

19.126957927841936

In [50]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [ ]:
f0 = np.array(f0)
f0

In [ ]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

In [ ]:
benford = np.array(benford)
benford

In [ ]:
f0_tot=f0.sum()
f0_tot

In [ ]:
fe = benford*f0_tot

In [ ]:
fe 

In [ ]:
fe.sum()

In [ ]:
diferencia = fre_relativa - benford
diferencia 

In [ ]:
diferencia.sum()

In [ ]:
f0_fe= (f0-fe)

In [ ]:
f0_fe_2 = f0_fe*f0_fe

In [ ]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

# Total

In [ ]:
x_2 = f0_fe_2_fe.sum()
x_2 