In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}

colours = [ # different shades of green
    '#04ff00',
    '#03e000',
    '#03bf00',
    '#02a300',
    '#028700',
    '#016b00',
    '#015100',
    '#003800',
    '#002100'
]

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1Ao6IVf6n3YlnHLI76WWjvmyTsPEhKdBc/export?format=csv")
df

PL     PN  LIBRE-PINU  TOTAL
0   2773  13145        9122  25382
1     72   1914        1987   4041
2   1077   5701        8028  14907
3   9894  16748       38150  65300
4   1443   2335        1105   4913
5   2518   7756        5220  15566
6   2173  14917       19175  36450
7    972   4573        5965  11547
8   1277   3435        2646   7427
9   2387   5056        2887  10389
10  1580   3961        1646   7248

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[2773, 72, 1077, 9894, 1443, 2518, 2173, 972, 1277, 2387, 1580]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[13145, 1914, 5701, 16748, 2335, 7756, 14917, 4573, 3435, 5056, 3961]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[9122, 1987, 8028, 38150, 1105, 5220, 19175, 5965, 2646, 2887, 1646]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[25382, 4041, 14907, 65300, 4913, 15566, 36450, 11547, 7427, 10389, 7248]

In [7]:
def GenerarFibonacci(n):
    a, b = 0, 1

    l = []

    for i in range(n):
        a, b = b, a + b

        l.append(a)

    return l

In [8]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [9]:
f0 = np.array(f0)
f0

array([4, 4, 0, 0, 0, 0, 1, 0, 2])

In [10]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.008, 0.008, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.004])

In [11]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [12]:
f0_tot=f0.sum()
f0_tot

11

In [13]:
fe = benford*f0_tot

In [14]:
fe 

array([3.311 , 1.9371, 1.3739, 1.0659, 0.8712, 0.7359, 0.638 , 0.5632,
       0.5038])

In [15]:
fe.sum()

11.0

In [16]:
diferencia = fre_relativa - benford
diferencia 

array([-0.293 , -0.1681, -0.1249, -0.0969, -0.0792, -0.0669, -0.056 ,
       -0.0512, -0.0418])

In [17]:
diferencia.sum()

-0.978

In [18]:
f0_fe= (f0-fe)

In [19]:
f0_fe_2 = f0_fe*f0_fe

In [20]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.14337693, 2.19686976, 1.3739    , 1.0659    , 0.8712    ,
       0.7359    , 0.20539812, 0.5632    , 4.44345859])

# Partido Liberal

In [21]:
x_2 = f0_fe_2_fe.sum()
x_2 

11.599203398120837

In [22]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [23]:
f0 = np.array(f0)
f0

array([4, 1, 2, 1, 2, 0, 1, 0, 0])

In [24]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.008, 0.002, 0.004, 0.002, 0.004, 0.   , 0.002, 0.   , 0.   ])

In [25]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [26]:
f0_tot=f0.sum()
f0_tot

11

In [27]:
fe = benford*f0_tot

In [28]:
fe 

array([3.311 , 1.9371, 1.3739, 1.0659, 0.8712, 0.7359, 0.638 , 0.5632,
       0.5038])

In [29]:
fe.sum()

11.0

In [30]:
diferencia = fre_relativa - benford
diferencia 

array([-0.293 , -0.1741, -0.1209, -0.0949, -0.0752, -0.0669, -0.056 ,
       -0.0512, -0.0458])

In [31]:
diferencia.sum()

-0.9779999999999999

In [32]:
f0_fe= (f0-fe)

In [33]:
f0_fe_2 = f0_fe*f0_fe

In [34]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.14337693, 0.45333561, 0.28532005, 0.00407431, 1.46256823,
       0.7359    , 0.20539812, 0.5632    , 0.5038    ])

# Partido Nacional

In [35]:
x_2 = f0_fe_2_fe.sum()
x_2 

4.356973240101002

In [36]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [37]:
f0 = np.array(f0)
f0

array([4, 2, 1, 0, 2, 0, 0, 1, 1])

In [38]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.008, 0.004, 0.002, 0.   , 0.004, 0.   , 0.   , 0.002, 0.002])

In [39]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [40]:
f0_tot=f0.sum()
f0_tot

11

In [41]:
fe = benford*f0_tot

In [42]:
fe 

array([3.311 , 1.9371, 1.3739, 1.0659, 0.8712, 0.7359, 0.638 , 0.5632,
       0.5038])

In [43]:
fe.sum()

11.0

In [44]:
diferencia = fre_relativa - benford
diferencia 

array([-0.293 , -0.1721, -0.1229, -0.0969, -0.0752, -0.0669, -0.058 ,
       -0.0492, -0.0438])

In [45]:
diferencia.sum()

-0.9779999999999999

In [46]:
f0_fe= (f0-fe)

In [47]:
f0_fe_2 = f0_fe*f0_fe

In [48]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.14337693, 0.00204244, 0.10175501, 1.0659    , 1.46256823,
       0.7359    , 0.638     , 0.33876818, 0.48871465])

# Partido Libre

In [49]:
x_2 = f0_fe_2_fe.sum()
x_2 

4.977025434631579

In [50]:
letters = {
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0,
    '6': 0,
    '7': 0,
    '8': 0,
    '9': 0
}
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [51]:
f0 = np.array(f0)
f0

array([4, 1, 1, 2, 0, 1, 2, 0, 0])

In [52]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.008, 0.002, 0.002, 0.004, 0.   , 0.002, 0.004, 0.   , 0.   ])

In [53]:
benford = np.array(benford)
benford

array([0.301 , 0.1761, 0.1249, 0.0969, 0.0792, 0.0669, 0.058 , 0.0512,
       0.0458])

In [54]:
f0_tot=f0.sum()
f0_tot

11

In [55]:
fe = benford*f0_tot

In [56]:
fe 

array([3.311 , 1.9371, 1.3739, 1.0659, 0.8712, 0.7359, 0.638 , 0.5632,
       0.5038])

In [57]:
fe.sum()

11.0

In [58]:
diferencia = fre_relativa - benford
diferencia 

array([-0.293 , -0.1741, -0.1229, -0.0929, -0.0792, -0.0649, -0.054 ,
       -0.0512, -0.0458])

In [59]:
diferencia.sum()

-0.9779999999999999

In [60]:
f0_fe= (f0-fe)

In [61]:
f0_fe_2 = f0_fe*f0_fe

In [62]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.14337693, 0.45333561, 0.10175501, 0.81859725, 0.8712    ,
       0.09478028, 2.90759248, 0.5632    , 0.5038    ])

# Total

In [63]:
x_2 = f0_fe_2_fe.sum()
x_2 

6.457637556899698