In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/15unNCvztiQfNtll4xRzNRfR5sBTpFLsM/export?format=csv")
df

PL     PN  LIBRE-PINU  TOTAL
0  8946  17976       30485  57937
1  1254   2830        3644   7808
2  1534   2409        2895   6892
3  1491   6205        6799  14550
4  1441   4697        6230  12417
5   347   1841        3596   5817
6  4085  12488       15006  31882
7  1096   4004        5006  10167

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[8946, 1254, 1534, 1491, 1441, 347, 4085, 1096]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[17976, 2830, 2409, 6205, 4697, 1841, 12488, 4004]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[30485, 3644, 2895, 6799, 6230, 3596, 15006, 5006]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[57937, 7808, 6892, 14550, 12417, 5817, 31882, 10167]

In [7]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [8]:
f0 = np.array(f0)
f0

array([1, 0, 1, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [9]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.   , 0.002, 0.   , 0.004, 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [10]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [11]:
f0_tot=f0.sum()
f0_tot

8

In [12]:
fe = benford*f0_tot

In [13]:
fe 

array([0.3312, 0.3024, 0.2784, 0.2576, 0.24  , 0.224 , 0.2104, 0.1984,
       0.188 , 0.1784, 0.1696, 0.1616, 0.1544, 0.148 , 0.1416, 0.136 ,
       0.1312, 0.1264, 0.1216, 0.1176, 0.1136, 0.1104, 0.1072, 0.104 ,
       0.1008, 0.0976, 0.0952, 0.0928, 0.0904, 0.088 , 0.0856, 0.084 ,
       0.0816, 0.08  , 0.0784, 0.076 , 0.0744, 0.0728, 0.072 , 0.0704,
       0.0688, 0.0672, 0.0664, 0.0648, 0.064 , 0.0624, 0.0616, 0.0608,
       0.0592, 0.0584, 0.0576, 0.0568, 0.0552, 0.0544, 0.0536, 0.0528,
       0.052 , 0.0512, 0.0504, 0.0496, 0.0496, 0.0488, 0.048 , 0.0472,
       0.0464, 0.0464, 0.0456, 0.0448, 0.044 , 0.044 , 0.0432, 0.0424,
       0.0424, 0.0416, 0.0408, 0.0408, 0.04  , 0.04  , 0.0392, 0.0392,
       0.0384, 0.0376, 0.0376, 0.0368, 0.0368, 0.036 , 0.036 , 0.036 ,
       0.0352, 0.0352])

In [14]:
fe.sum()

7.999199999999999

In [15]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0378, -0.0328, -0.0322, -0.026 , -0.026 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0106, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0087, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0029, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [16]:
diferencia.sum()

-0.9839

In [17]:
f0_fe= (f0-fe)

In [18]:
f0_fe_2 = f0_fe*f0_fe

In [19]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 1.35052367,  0.3024    ,  1.87035402,  0.2576    , 12.90666667,
        2.68828571,  0.2104    ,  0.1984    ,  0.188     ,  0.1784    ,
        0.1696    ,  0.1616    ,  0.1544    ,  0.148     ,  0.1416    ,
        0.136     ,  0.1312    ,  0.1264    ,  0.1216    ,  0.1176    ,
        0.1136    ,  0.1104    ,  0.1072    ,  0.104     ,  8.02143492,
        0.0976    ,  0.0952    ,  0.0928    ,  0.0904    ,  0.088     ,
        9.76784299,  0.084     ,  0.0816    ,  0.08      ,  0.0784    ,
        0.076     ,  0.0744    ,  0.0728    ,  0.072     ,  0.0704    ,
        0.0688    ,  0.0672    ,  0.0664    ,  0.0648    ,  0.064     ,
        0.0624    ,  0.0616    ,  0.0608    ,  0.0592    ,  0.0584    ,
        0.0576    ,  0.0568    ,  0.0552    ,  0.0544    ,  0.0536    ,
        0.0528    ,  0.052     ,  0.0512    ,  0.0504    ,  0.0496    ,
        0.0496    ,  0.0488    ,  0.048     ,  0.0472    ,  0.0464    ,
        0.0464    ,  0.0456    ,  0.0448    ,  0.044     ,  0.04

# Partido Liberal

In [20]:
x_2 = f0_fe_2_fe.sum()
x_2 

66.85451206836026

In [21]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [22]:
f0 = np.array(f0)
f0

array([0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [23]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.002, 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [24]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [25]:
f0_tot=f0.sum()
f0_tot

8

In [26]:
fe = benford*f0_tot

In [27]:
fe 

array([0.3312, 0.3024, 0.2784, 0.2576, 0.24  , 0.224 , 0.2104, 0.1984,
       0.188 , 0.1784, 0.1696, 0.1616, 0.1544, 0.148 , 0.1416, 0.136 ,
       0.1312, 0.1264, 0.1216, 0.1176, 0.1136, 0.1104, 0.1072, 0.104 ,
       0.1008, 0.0976, 0.0952, 0.0928, 0.0904, 0.088 , 0.0856, 0.084 ,
       0.0816, 0.08  , 0.0784, 0.076 , 0.0744, 0.0728, 0.072 , 0.0704,
       0.0688, 0.0672, 0.0664, 0.0648, 0.064 , 0.0624, 0.0616, 0.0608,
       0.0592, 0.0584, 0.0576, 0.0568, 0.0552, 0.0544, 0.0536, 0.0528,
       0.052 , 0.0512, 0.0504, 0.0496, 0.0496, 0.0488, 0.048 , 0.0472,
       0.0464, 0.0464, 0.0456, 0.0448, 0.044 , 0.044 , 0.0432, 0.0424,
       0.0424, 0.0416, 0.0408, 0.0408, 0.04  , 0.04  , 0.0392, 0.0392,
       0.0384, 0.0376, 0.0376, 0.0368, 0.0368, 0.036 , 0.036 , 0.036 ,
       0.0352, 0.0352])

In [28]:
fe.sum()

7.999199999999999

In [29]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0378, -0.0328, -0.0322, -0.03  , -0.028 , -0.0263,
       -0.0228, -0.0215, -0.0223, -0.0212, -0.0202, -0.0193, -0.0185,
       -0.0157, -0.017 , -0.0164, -0.0158, -0.0132, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0087, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0073, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0049, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [30]:
diferencia.sum()

-0.9839

In [31]:
f0_fe= (f0-fe)

In [32]:
f0_fe_2 = f0_fe*f0_fe

In [33]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.3312    ,  0.3024    ,  1.87035402,  0.2576    ,  0.24      ,
        0.224     ,  0.2104    ,  3.23872258,  3.50714894,  0.1784    ,
        0.1696    ,  0.1616    ,  0.1544    ,  0.148     ,  5.20374689,
        0.136     ,  0.1312    ,  0.1264    ,  6.34528421,  0.1176    ,
        0.1136    ,  0.1104    ,  0.1072    ,  0.104     ,  0.1008    ,
        0.0976    ,  0.0952    ,  0.0928    ,  0.0904    ,  0.088     ,
        9.76784299,  0.084     ,  0.0816    ,  0.08      ,  0.0784    ,
        0.076     , 11.51526022,  0.0728    ,  0.072     ,  0.0704    ,
        0.0688    ,  0.0672    ,  0.0664    ,  0.0648    ,  0.064     ,
        0.0624    ,  0.0616    ,  0.0608    ,  0.0592    ,  0.0584    ,
        0.0576    ,  0.0568    , 16.17114203,  0.0544    ,  0.0536    ,
        0.0528    ,  0.052     ,  0.0512    ,  0.0504    ,  0.0496    ,
        0.0496    ,  0.0488    ,  0.048     ,  0.0472    ,  0.0464    ,
        0.0464    ,  0.0456    ,  0.0448    ,  0.044     ,  0.04

# Partido Nacional

In [34]:
x_2 = f0_fe_2_fe.sum()
x_2 

64.47550187767905

In [35]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [36]:
f0 = np.array(f0)
f0

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [37]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.002, 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [38]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [39]:
f0_tot=f0.sum()
f0_tot

8

In [40]:
fe = benford*f0_tot

In [41]:
fe 

array([0.3312, 0.3024, 0.2784, 0.2576, 0.24  , 0.224 , 0.2104, 0.1984,
       0.188 , 0.1784, 0.1696, 0.1616, 0.1544, 0.148 , 0.1416, 0.136 ,
       0.1312, 0.1264, 0.1216, 0.1176, 0.1136, 0.1104, 0.1072, 0.104 ,
       0.1008, 0.0976, 0.0952, 0.0928, 0.0904, 0.088 , 0.0856, 0.084 ,
       0.0816, 0.08  , 0.0784, 0.076 , 0.0744, 0.0728, 0.072 , 0.0704,
       0.0688, 0.0672, 0.0664, 0.0648, 0.064 , 0.0624, 0.0616, 0.0608,
       0.0592, 0.0584, 0.0576, 0.0568, 0.0552, 0.0544, 0.0536, 0.0528,
       0.052 , 0.0512, 0.0504, 0.0496, 0.0496, 0.0488, 0.048 , 0.0472,
       0.0464, 0.0464, 0.0456, 0.0448, 0.044 , 0.044 , 0.0432, 0.0424,
       0.0424, 0.0416, 0.0408, 0.0408, 0.04  , 0.04  , 0.0392, 0.0392,
       0.0384, 0.0376, 0.0376, 0.0368, 0.0368, 0.036 , 0.036 , 0.036 ,
       0.0352, 0.0352])

In [42]:
fe.sum()

7.999199999999999

In [43]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0378, -0.0348, -0.0322, -0.03  , -0.026 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0132, -0.0147, -0.0122,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0102, -0.0099, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0066, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0049, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0044, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [44]:
diferencia.sum()

-0.9839

In [45]:
f0_fe= (f0-fe)

In [46]:
f0_fe_2 = f0_fe*f0_fe

In [47]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.3312    ,  0.3024    ,  0.2784    ,  0.2576    ,  0.24      ,
        2.68828571,  0.2104    ,  0.1984    ,  0.188     ,  0.1784    ,
        0.1696    ,  0.1616    ,  0.1544    ,  0.148     ,  0.1416    ,
        0.136     ,  0.1312    ,  0.1264    ,  6.34528421,  0.1176    ,
        6.9164169 ,  0.1104    ,  0.1072    ,  0.104     ,  0.1008    ,
        8.34350164,  8.59940168,  0.0928    ,  0.0904    ,  0.088     ,
        0.0856    ,  0.084     ,  0.0816    ,  0.08      ,  0.0784    ,
        0.076     ,  0.0744    ,  0.0728    ,  0.072     ,  0.0704    ,
       12.60368372,  0.0672    ,  0.0664    ,  0.0648    ,  0.064     ,
        0.0624    ,  0.0616    ,  0.0608    ,  0.0592    ,  0.0584    ,
        0.0576    ,  0.0568    , 16.17114203,  0.0544    ,  0.0536    ,
        0.0528    ,  0.052     , 17.58245   ,  0.0504    ,  0.0496    ,
        0.0496    ,  0.0488    ,  0.048     ,  0.0472    ,  0.0464    ,
        0.0464    ,  0.0456    ,  0.0448    ,  0.044     ,  0.04

# Partido Libre

In [48]:
x_2 = f0_fe_2_fe.sum()
x_2 

86.42216589615276

In [49]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [50]:
f0 = np.array(f0)
f0

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [51]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.   , 0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [52]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [53]:
f0_tot=f0.sum()
f0_tot

8

In [54]:
fe = benford*f0_tot

In [55]:
fe 

array([0.3312, 0.3024, 0.2784, 0.2576, 0.24  , 0.224 , 0.2104, 0.1984,
       0.188 , 0.1784, 0.1696, 0.1616, 0.1544, 0.148 , 0.1416, 0.136 ,
       0.1312, 0.1264, 0.1216, 0.1176, 0.1136, 0.1104, 0.1072, 0.104 ,
       0.1008, 0.0976, 0.0952, 0.0928, 0.0904, 0.088 , 0.0856, 0.084 ,
       0.0816, 0.08  , 0.0784, 0.076 , 0.0744, 0.0728, 0.072 , 0.0704,
       0.0688, 0.0672, 0.0664, 0.0648, 0.064 , 0.0624, 0.0616, 0.0608,
       0.0592, 0.0584, 0.0576, 0.0568, 0.0552, 0.0544, 0.0536, 0.0528,
       0.052 , 0.0512, 0.0504, 0.0496, 0.0496, 0.0488, 0.048 , 0.0472,
       0.0464, 0.0464, 0.0456, 0.0448, 0.044 , 0.044 , 0.0432, 0.0424,
       0.0424, 0.0416, 0.0408, 0.0408, 0.04  , 0.04  , 0.0392, 0.0392,
       0.0384, 0.0376, 0.0376, 0.0368, 0.0368, 0.036 , 0.036 , 0.036 ,
       0.0352, 0.0352])

In [56]:
fe.sum()

7.999199999999999

In [57]:
diferencia = abs(fre_relativa - benford)
diferencia 

array([0.0394, 0.0378, 0.0328, 0.0322, 0.028 , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0118, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0056,
       0.0054, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0043, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0035, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [58]:
diferencia.sum()

0.9839

In [59]:
f0_fe= (f0-fe)

In [60]:
f0_fe_2 = f0_fe*f0_fe

In [61]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 1.35052367,  0.3024    ,  1.87035402,  0.2576    ,  2.40666667,
        0.224     ,  0.2104    ,  0.1984    ,  0.188     ,  0.1784    ,
        0.1696    ,  0.1616    ,  0.1544    ,  0.148     ,  0.1416    ,
        0.136     ,  0.1312    ,  0.1264    ,  0.1216    ,  0.1176    ,
        0.1136    ,  7.16837101,  0.1072    ,  0.104     ,  0.1008    ,
        0.0976    ,  0.0952    ,  0.0928    ,  0.0904    ,  0.088     ,
        0.0856    ,  0.084     ,  0.0816    ,  0.08      ,  0.0784    ,
        0.076     ,  0.0744    ,  0.0728    ,  0.072     ,  0.0704    ,
        0.0688    ,  0.0672    ,  0.0664    ,  0.0648    ,  0.064     ,
        0.0624    ,  0.0616    , 14.50816842, 14.95109189,  0.0584    ,
        0.0576    ,  0.0568    ,  0.0552    ,  0.0544    ,  0.0536    ,
        0.0528    ,  0.052     ,  0.0512    , 17.89166984,  0.0496    ,
        0.0496    ,  0.0488    ,  0.048     ,  0.0472    ,  0.0464    ,
        0.0464    ,  0.0456    ,  0.0448    , 20.77127273,  0.04

# Total

In [62]:
x_2 = f0_fe_2_fe.sum()
x_2 

87.7429182571326