In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1zuU8MkVl8U3G7h5xz18XE3IUumEMog1b/export?format=csv")
df

PL     PN  LIBRE-PINU  TOTAL
0   6344  23173       32813  62598
1    874   2407        2043   5378
2   1059   6035        3197  10378
3    262   1295         743   2318
4   1155   4753        3142   9241
5   3204  10377        8058  21782
6   3491   7003        9004  19661
7   1230   1686         710   3645
8   2178   5990        6571  14820
9   1295   4733        3175   9250
10  1390   6258        5045  12777
11   713   2223         868   3820
12   516   1332         637   2492
13   645   1377         635   2689
14  2094   6777        4437  13384
15  1513   3105        3488   8138

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[6344,
 874,
 1059,
 262,
 1155,
 3204,
 3491,
 1230,
 2178,
 1295,
 1390,
 713,
 516,
 645,
 2094,
 1513]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[23173,
 2407,
 6035,
 1295,
 4753,
 10377,
 7003,
 1686,
 5990,
 4733,
 6258,
 2223,
 1332,
 1377,
 6777,
 3105]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[32813,
 2043,
 3197,
 743,
 3142,
 8058,
 9004,
 710,
 6571,
 3175,
 5045,
 868,
 637,
 635,
 4437,
 3488]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[62598,
 5378,
 10378,
 2318,
 9241,
 21782,
 19661,
 3645,
 14820,
 9250,
 12777,
 3820,
 2492,
 2689,
 13384,
 8138]

In [7]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [8]:
f0 = np.array(f0)
f0

array([1, 1, 2, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [9]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.002, 0.004, 0.002, 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [10]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [11]:
f0_tot=f0.sum()
f0_tot

16

In [12]:
fe = benford*f0_tot

In [13]:
fe 

array([0.6624, 0.6048, 0.5568, 0.5152, 0.48  , 0.448 , 0.4208, 0.3968,
       0.376 , 0.3568, 0.3392, 0.3232, 0.3088, 0.296 , 0.2832, 0.272 ,
       0.2624, 0.2528, 0.2432, 0.2352, 0.2272, 0.2208, 0.2144, 0.208 ,
       0.2016, 0.1952, 0.1904, 0.1856, 0.1808, 0.176 , 0.1712, 0.168 ,
       0.1632, 0.16  , 0.1568, 0.152 , 0.1488, 0.1456, 0.144 , 0.1408,
       0.1376, 0.1344, 0.1328, 0.1296, 0.128 , 0.1248, 0.1232, 0.1216,
       0.1184, 0.1168, 0.1152, 0.1136, 0.1104, 0.1088, 0.1072, 0.1056,
       0.104 , 0.1024, 0.1008, 0.0992, 0.0992, 0.0976, 0.096 , 0.0944,
       0.0928, 0.0928, 0.0912, 0.0896, 0.088 , 0.088 , 0.0864, 0.0848,
       0.0848, 0.0832, 0.0816, 0.0816, 0.08  , 0.08  , 0.0784, 0.0784,
       0.0768, 0.0752, 0.0752, 0.0736, 0.0736, 0.072 , 0.072 , 0.072 ,
       0.0704, 0.0704])

In [14]:
fe.sum()

15.998399999999998

In [15]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0358, -0.0308, -0.0302, -0.03  , -0.026 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0192, -0.0182, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0144, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0114, -0.013 , -0.0106, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0064,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0048, -0.0047, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0041, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.003 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [16]:
diferencia.sum()

-0.9679

In [17]:
f0_fe= (f0-fe)

In [18]:
f0_fe_2 = f0_fe*f0_fe

In [19]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.17206184,  0.25823915,  3.74070805,  0.45619379,  0.48      ,
        0.68014286,  0.4208    ,  0.3968    ,  0.376     ,  0.3568    ,
        1.28731321,  1.41725941,  0.3088    ,  0.296     ,  0.2832    ,
        0.272     ,  2.07337561,  0.2528    ,  0.2432    ,  0.2352    ,
        0.2272    ,  0.2208    ,  2.8785791 ,  0.208     ,  3.16191746,
        0.1952    ,  0.1904    ,  0.1856    ,  0.1808    ,  0.176     ,
        0.1712    ,  0.168     ,  0.1632    ,  0.16      ,  0.1568    ,
        0.152     ,  0.1488    ,  0.1456    ,  0.144     ,  0.1408    ,
        0.1376    ,  5.57487619,  0.1328    ,  0.1296    ,  0.128     ,
        0.1248    ,  0.1232    ,  0.1216    ,  0.1184    ,  0.1168    ,
        0.1152    ,  0.1136    ,  0.1104    ,  7.29997647,  7.43555821,
        0.1056    ,  0.104     ,  0.1024    ,  0.1008    ,  0.0992    ,
        0.0992    ,  8.34350164,  0.096     ,  0.0944    ,  0.0928    ,
        0.0928    ,  0.0912    ,  0.0896    ,  0.088     ,  0.08

# Partido Liberal

In [20]:
x_2 = f0_fe_2_fe.sum()
x_2 

66.70210297853055

In [21]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [22]:
f0 = np.array(f0)
f0

array([1, 0, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [23]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.   , 0.002, 0.004, 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.002, 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.004, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.002, 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [24]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [25]:
f0_tot=f0.sum()
f0_tot

16

In [26]:
fe = benford*f0_tot

In [27]:
fe 

array([0.6624, 0.6048, 0.5568, 0.5152, 0.48  , 0.448 , 0.4208, 0.3968,
       0.376 , 0.3568, 0.3392, 0.3232, 0.3088, 0.296 , 0.2832, 0.272 ,
       0.2624, 0.2528, 0.2432, 0.2352, 0.2272, 0.2208, 0.2144, 0.208 ,
       0.2016, 0.1952, 0.1904, 0.1856, 0.1808, 0.176 , 0.1712, 0.168 ,
       0.1632, 0.16  , 0.1568, 0.152 , 0.1488, 0.1456, 0.144 , 0.1408,
       0.1376, 0.1344, 0.1328, 0.1296, 0.128 , 0.1248, 0.1232, 0.1216,
       0.1184, 0.1168, 0.1152, 0.1136, 0.1104, 0.1088, 0.1072, 0.1056,
       0.104 , 0.1024, 0.1008, 0.0992, 0.0992, 0.0976, 0.096 , 0.0944,
       0.0928, 0.0928, 0.0912, 0.0896, 0.088 , 0.088 , 0.0864, 0.0848,
       0.0848, 0.0832, 0.0816, 0.0816, 0.08  , 0.08  , 0.0784, 0.0784,
       0.0768, 0.0752, 0.0752, 0.0736, 0.0736, 0.072 , 0.072 , 0.072 ,
       0.0704, 0.0704])

In [28]:
fe.sum()

15.998399999999998

In [29]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0378, -0.0328, -0.0282, -0.03  , -0.028 , -0.0243,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0202, -0.0173, -0.0165,
       -0.0157, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0118, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0051, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0053, -0.0052, -0.0071, -0.0049, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0044, -0.0063, -0.0062, -0.0042, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [30]:
diferencia.sum()

-0.9679

In [31]:
f0_fe= (f0-fe)

In [32]:
f0_fe_2 = f0_fe*f0_fe

In [33]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.17206184,  0.6048    ,  0.35277701,  4.27917516,  0.48      ,
        0.448     ,  0.79722586,  0.3968    ,  0.376     ,  0.3568    ,
        0.3392    ,  0.3232    ,  1.54714197,  1.67437838,  1.81427345,
        0.272     ,  0.2624    ,  0.2528    ,  0.2432    ,  0.2352    ,
        0.2272    ,  2.74978551,  0.2144    ,  0.208     ,  0.2016    ,
        0.1952    ,  0.1904    ,  0.1856    ,  0.1808    ,  0.176     ,
        0.1712    ,  0.168     ,  0.1632    ,  0.16      ,  0.1568    ,
        0.152     ,  0.1488    , 23.61812747,  0.144     ,  0.1408    ,
        0.1376    ,  0.1344    ,  0.1328    ,  0.1296    ,  0.128     ,
        0.1248    ,  0.1232    ,  0.1216    ,  0.1184    ,  6.67844384,
        6.79575556,  0.1136    ,  7.16837101,  0.1088    ,  0.1072    ,
        0.1056    ,  0.104     ,  7.868025  ,  0.1008    ,  0.0992    ,
        8.17984516,  0.0976    ,  0.096     ,  0.0944    ,  0.0928    ,
        0.0928    ,  0.0912    ,  0.0896    ,  0.088     ,  0.08

# Partido Nacional

In [34]:
x_2 = f0_fe_2_fe.sum()
x_2 

85.74018719838277

In [35]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [36]:
f0 = np.array(f0)
f0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [37]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.006, 0.002, 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.004,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [38]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [39]:
f0_tot=f0.sum()
f0_tot

16

In [40]:
fe = benford*f0_tot

In [41]:
fe 

array([0.6624, 0.6048, 0.5568, 0.5152, 0.48  , 0.448 , 0.4208, 0.3968,
       0.376 , 0.3568, 0.3392, 0.3232, 0.3088, 0.296 , 0.2832, 0.272 ,
       0.2624, 0.2528, 0.2432, 0.2352, 0.2272, 0.2208, 0.2144, 0.208 ,
       0.2016, 0.1952, 0.1904, 0.1856, 0.1808, 0.176 , 0.1712, 0.168 ,
       0.1632, 0.16  , 0.1568, 0.152 , 0.1488, 0.1456, 0.144 , 0.1408,
       0.1376, 0.1344, 0.1328, 0.1296, 0.128 , 0.1248, 0.1232, 0.1216,
       0.1184, 0.1168, 0.1152, 0.1136, 0.1104, 0.1088, 0.1072, 0.1056,
       0.104 , 0.1024, 0.1008, 0.0992, 0.0992, 0.0976, 0.096 , 0.0944,
       0.0928, 0.0928, 0.0912, 0.0896, 0.088 , 0.088 , 0.0864, 0.0848,
       0.0848, 0.0832, 0.0816, 0.0816, 0.08  , 0.08  , 0.0784, 0.0784,
       0.0768, 0.0752, 0.0752, 0.0736, 0.0736, 0.072 , 0.072 , 0.072 ,
       0.0704, 0.0704])

In [42]:
fe.sum()

15.998399999999998

In [43]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0378, -0.0348, -0.0322, -0.03  , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0192, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0078, -0.0114, -0.013 , -0.0106, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0078,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0066, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0028, -0.0067, -0.0046,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0041, -0.006 ,
       -0.0059, -0.0038, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0034, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.003 ,
       -0.005 , -0.0049, -0.0049, -0.0028, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [44]:
diferencia.sum()

-0.9679

In [45]:
f0_fe= (f0-fe)

In [46]:
f0_fe_2 = f0_fe*f0_fe

In [47]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.6624    ,  0.6048    ,  0.5568    ,  0.5152    ,  0.48      ,
        0.448     ,  0.4208    ,  0.3968    ,  0.376     ,  0.3568    ,
        1.28731321,  0.3232    ,  0.3088    ,  0.296     ,  0.2832    ,
        0.272     ,  0.2624    ,  0.2528    ,  0.2432    ,  0.2352    ,
        0.2272    , 34.98166957,  2.8785791 ,  0.208     ,  3.16191746,
        0.1952    ,  0.1904    ,  0.1856    ,  0.1808    ,  0.176     ,
        0.1712    ,  0.168     ,  0.1632    ,  0.16      ,  4.53435102,
        0.152     ,  0.1488    ,  0.1456    ,  0.144     ,  0.1408    ,
        5.40504186,  0.1344    ,  0.1328    ,  0.1296    ,  0.128     ,
        0.1248    ,  0.1232    ,  0.1216    ,  0.1184    ,  0.1168    ,
        0.1152    ,  0.1136    ,  0.1104    , 32.87350588,  0.1072    ,
        7.57529697,  0.104     ,  0.1024    ,  0.1008    ,  0.0992    ,
        0.0992    ,  8.34350164,  0.096     ,  0.0944    ,  8.86866207,
        0.0928    ,  0.0912    ,  0.0896    ,  0.088     ,  0.08

# Partido Libre

In [48]:
x_2 = f0_fe_2_fe.sum()
x_2 

155.32794618620005

In [49]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [50]:
f0 = np.array(f0)
f0

array([1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0,
       0, 0])

In [51]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.   , 0.002, 0.002, 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.002, 0.   , 0.002, 0.002, 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.004, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [52]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [53]:
f0_tot=f0.sum()
f0_tot

16

In [54]:
fe = benford*f0_tot

In [55]:
fe 

array([0.6624, 0.6048, 0.5568, 0.5152, 0.48  , 0.448 , 0.4208, 0.3968,
       0.376 , 0.3568, 0.3392, 0.3232, 0.3088, 0.296 , 0.2832, 0.272 ,
       0.2624, 0.2528, 0.2432, 0.2352, 0.2272, 0.2208, 0.2144, 0.208 ,
       0.2016, 0.1952, 0.1904, 0.1856, 0.1808, 0.176 , 0.1712, 0.168 ,
       0.1632, 0.16  , 0.1568, 0.152 , 0.1488, 0.1456, 0.144 , 0.1408,
       0.1376, 0.1344, 0.1328, 0.1296, 0.128 , 0.1248, 0.1232, 0.1216,
       0.1184, 0.1168, 0.1152, 0.1136, 0.1104, 0.1088, 0.1072, 0.1056,
       0.104 , 0.1024, 0.1008, 0.0992, 0.0992, 0.0976, 0.096 , 0.0944,
       0.0928, 0.0928, 0.0912, 0.0896, 0.088 , 0.088 , 0.0864, 0.0848,
       0.0848, 0.0832, 0.0816, 0.0816, 0.08  , 0.08  , 0.0784, 0.0784,
       0.0768, 0.0752, 0.0752, 0.0736, 0.0736, 0.072 , 0.072 , 0.072 ,
       0.0704, 0.0704])

In [56]:
fe.sum()

15.998399999999998

In [57]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0378, -0.0328, -0.0302, -0.028 , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0203, -0.0212, -0.0182, -0.0193, -0.0165,
       -0.0157, -0.017 , -0.0144, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0099, -0.0116,
       -0.0093, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0061, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0049, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0033, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0007, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [58]:
diferencia.sum()

-0.9679

In [59]:
f0_fe= (f0-fe)

In [60]:
f0_fe_2 = f0_fe*f0_fe

In [61]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.17206184,  0.6048    ,  0.35277701,  0.45619379,  0.56333333,
        0.448     ,  0.4208    ,  0.3968    ,  0.376     ,  1.15949058,
        0.3392    ,  1.41725941,  0.3088    ,  1.67437838,  1.81427345,
        0.272     ,  2.07337561,  0.2528    ,  0.2432    ,  0.2352    ,
        0.2272    ,  0.2208    ,  0.2144    ,  0.208     ,  0.2016    ,
        0.1952    ,  3.44250084,  0.1856    ,  3.71177345,  0.176     ,
        0.1712    ,  0.168     ,  0.1632    ,  0.16      ,  0.1568    ,
        0.152     ,  0.1488    ,  0.1456    ,  0.144     ,  0.1408    ,
        0.1376    ,  0.1344    ,  0.1328    ,  5.84564938,  0.128     ,
        0.1248    ,  0.1232    ,  0.1216    ,  0.1184    ,  0.1168    ,
        0.1152    ,  0.1136    ,  7.16837101,  0.1088    ,  0.1072    ,
        0.1056    ,  0.104     ,  0.1024    ,  0.1008    ,  0.0992    ,
        0.0992    ,  0.0976    ,  0.096     ,  0.0944    ,  0.0928    ,
        0.0928    ,  0.0912    ,  0.0896    ,  0.088     ,  0.08

# Total

In [62]:
x_2 = f0_fe_2_fe.sum()
x_2 

100.48658027352184