In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1HZCThrsZly6HJceEVUIZaOTjVTegqT9w/export?format=csv")
df

PL    PN  LIBRE-PINU  TOTAL
0  2149  8109       10141  20509
1   492  2060        1539   4113
2   706  1735        1299   3802
3   507  1270        1528   3341
4  1026  4062        8821  14003
5   323  1221         614   2198
6   244  1157         770   2190
7  1129  6620        9477  17329
8  3445  7948       16843  28407
9   735  5120        5947  11891

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[2149, 492, 706, 507, 1026, 323, 244, 1129, 3445, 735]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[8109, 2060, 1735, 1270, 4062, 1221, 1157, 6620, 7948, 5120]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[10141, 1539, 1299, 1528, 8821, 614, 770, 9477, 16843, 5947]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[20509, 4113, 3802, 3341, 14003, 2198, 2190, 17329, 28407, 11891]

In [7]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [8]:
f0 = np.array(f0)
f0

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [9]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [10]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [11]:
f0_tot=f0.sum()
f0_tot

10

In [12]:
fe = benford*f0_tot

In [13]:
fe 

array([0.414, 0.378, 0.348, 0.322, 0.3  , 0.28 , 0.263, 0.248, 0.235,
       0.223, 0.212, 0.202, 0.193, 0.185, 0.177, 0.17 , 0.164, 0.158,
       0.152, 0.147, 0.142, 0.138, 0.134, 0.13 , 0.126, 0.122, 0.119,
       0.116, 0.113, 0.11 , 0.107, 0.105, 0.102, 0.1  , 0.098, 0.095,
       0.093, 0.091, 0.09 , 0.088, 0.086, 0.084, 0.083, 0.081, 0.08 ,
       0.078, 0.077, 0.076, 0.074, 0.073, 0.072, 0.071, 0.069, 0.068,
       0.067, 0.066, 0.065, 0.064, 0.063, 0.062, 0.062, 0.061, 0.06 ,
       0.059, 0.058, 0.058, 0.057, 0.056, 0.055, 0.055, 0.054, 0.053,
       0.053, 0.052, 0.051, 0.051, 0.05 , 0.05 , 0.049, 0.049, 0.048,
       0.047, 0.047, 0.046, 0.046, 0.045, 0.045, 0.045, 0.044, 0.044])

In [14]:
fe.sum()

9.999000000000002

In [15]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0358, -0.0348, -0.0322, -0.03  , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0182, -0.0193, -0.0185,
       -0.0157, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0114, -0.013 , -0.0106, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0068, -0.0066, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0042, -0.0061, -0.006 ,
       -0.0039, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [16]:
diferencia.sum()

-0.9799

In [17]:
f0_fe= (f0-fe)

In [18]:
f0_fe_2 = f0_fe*f0_fe

In [19]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.82945894,  1.02350265,  0.348     ,  0.322     ,  0.3       ,
        0.28      ,  0.263     ,  0.248     ,  0.235     ,  0.223     ,
        0.212     ,  3.15249505,  0.193     ,  0.185     ,  3.82671751,
        0.17      ,  0.164     ,  0.158     ,  0.152     ,  0.147     ,
        0.142     ,  0.138     ,  5.59668657,  0.13      ,  6.06250794,
        0.122     ,  0.119     ,  0.116     ,  0.113     ,  0.11      ,
        0.107     ,  0.105     ,  0.102     ,  0.1       ,  0.098     ,
        0.095     ,  0.093     ,  0.091     ,  0.09      ,  9.45163636,
        9.71390698,  0.084     ,  0.083     ,  0.081     ,  0.08      ,
        0.078     ,  0.077     ,  0.076     ,  0.074     ,  0.073     ,
        0.072     ,  0.071     ,  0.069     ,  0.068     ,  0.067     ,
        0.066     ,  0.065     ,  0.064     ,  0.063     ,  0.062     ,
       14.19103226,  0.061     ,  0.06      , 15.00815254,  0.058     ,
        0.058     ,  0.057     ,  0.056     ,  0.055     ,  0.05

# Partido Liberal

In [20]:
x_2 = f0_fe_2_fe.sum()
x_2 

77.12909679082003

In [21]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [22]:
f0 = np.array(f0)
f0

array([0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [23]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.002, 0.004, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [24]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [25]:
f0_tot=f0.sum()
f0_tot

10

In [26]:
fe = benford*f0_tot

In [27]:
fe 

array([0.414, 0.378, 0.348, 0.322, 0.3  , 0.28 , 0.263, 0.248, 0.235,
       0.223, 0.212, 0.202, 0.193, 0.185, 0.177, 0.17 , 0.164, 0.158,
       0.152, 0.147, 0.142, 0.138, 0.134, 0.13 , 0.126, 0.122, 0.119,
       0.116, 0.113, 0.11 , 0.107, 0.105, 0.102, 0.1  , 0.098, 0.095,
       0.093, 0.091, 0.09 , 0.088, 0.086, 0.084, 0.083, 0.081, 0.08 ,
       0.078, 0.077, 0.076, 0.074, 0.073, 0.072, 0.071, 0.069, 0.068,
       0.067, 0.066, 0.065, 0.064, 0.063, 0.062, 0.062, 0.061, 0.06 ,
       0.059, 0.058, 0.058, 0.057, 0.056, 0.055, 0.055, 0.054, 0.053,
       0.053, 0.052, 0.051, 0.051, 0.05 , 0.05 , 0.049, 0.049, 0.048,
       0.047, 0.047, 0.046, 0.046, 0.045, 0.045, 0.045, 0.044, 0.044])

In [28]:
fe.sum()

9.999000000000002

In [29]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0358, -0.0308, -0.0322, -0.03  , -0.028 , -0.0263,
       -0.0228, -0.0235, -0.0223, -0.0192, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0087, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0064,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0045, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0035,
       -0.0054, -0.0033, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [30]:
diferencia.sum()

-0.9799

In [31]:
f0_fe= (f0-fe)

In [32]:
f0_fe_2 = f0_fe*f0_fe

In [33]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.414     ,  1.02350265,  7.84225287,  0.322     ,  0.3       ,
        0.28      ,  0.263     ,  2.28025806,  0.235     ,  0.223     ,
        2.92898113,  0.202     ,  0.193     ,  0.185     ,  0.177     ,
        0.17      ,  0.164     ,  0.158     ,  0.152     ,  0.147     ,
        0.142     ,  0.138     ,  0.134     ,  0.13      ,  0.126     ,
        0.122     ,  0.119     ,  0.116     ,  0.113     ,  0.11      ,
        7.45279439,  0.105     ,  0.102     ,  0.1       ,  0.098     ,
        0.095     ,  0.093     ,  0.091     ,  0.09      ,  0.088     ,
        0.086     ,  9.9887619 ,  0.083     ,  0.081     ,  0.08      ,
        0.078     ,  0.077     ,  0.076     ,  0.074     ,  0.073     ,
        0.072     ,  0.071     ,  0.069     ,  0.068     ,  0.067     ,
        0.066     , 13.44961538,  0.064     ,  0.063     ,  0.062     ,
        0.062     ,  0.061     ,  0.06      ,  0.059     ,  0.058     ,
        0.058     ,  0.057     ,  0.056     ,  0.055     , 16.23

# Partido Nacional

In [34]:
x_2 = f0_fe_2_fe.sum()
x_2 

86.57290910767819

In [35]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [36]:
f0 = np.array(f0)
f0

array([1, 0, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0])

In [37]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.   , 0.002, 0.   , 0.   , 0.004, 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ])

In [38]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [39]:
f0_tot=f0.sum()
f0_tot

10

In [40]:
fe = benford*f0_tot

In [41]:
fe 

array([0.414, 0.378, 0.348, 0.322, 0.3  , 0.28 , 0.263, 0.248, 0.235,
       0.223, 0.212, 0.202, 0.193, 0.185, 0.177, 0.17 , 0.164, 0.158,
       0.152, 0.147, 0.142, 0.138, 0.134, 0.13 , 0.126, 0.122, 0.119,
       0.116, 0.113, 0.11 , 0.107, 0.105, 0.102, 0.1  , 0.098, 0.095,
       0.093, 0.091, 0.09 , 0.088, 0.086, 0.084, 0.083, 0.081, 0.08 ,
       0.078, 0.077, 0.076, 0.074, 0.073, 0.072, 0.071, 0.069, 0.068,
       0.067, 0.066, 0.065, 0.064, 0.063, 0.062, 0.062, 0.061, 0.06 ,
       0.059, 0.058, 0.058, 0.057, 0.056, 0.055, 0.055, 0.054, 0.053,
       0.053, 0.052, 0.051, 0.051, 0.05 , 0.05 , 0.049, 0.049, 0.048,
       0.047, 0.047, 0.046, 0.046, 0.045, 0.045, 0.045, 0.044, 0.044])

In [42]:
fe.sum()

9.999000000000002

In [43]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0378, -0.0328, -0.0322, -0.03  , -0.024 , -0.0243,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0053, -0.0072, -0.0051, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0036, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0029, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0026, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [44]:
diferencia.sum()

-0.9799

In [45]:
f0_fe= (f0-fe)

In [46]:
f0_fe_2 = f0_fe*f0_fe

In [47]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.82945894,  0.378     ,  1.22156322,  0.322     ,  0.3       ,
       10.56571429,  2.06528137,  0.248     ,  0.235     ,  0.223     ,
        0.212     ,  0.202     ,  0.193     ,  0.185     ,  0.177     ,
        0.17      ,  0.164     ,  0.158     ,  0.152     ,  0.147     ,
        0.142     ,  0.138     ,  0.134     ,  0.13      ,  0.126     ,
        0.122     ,  0.119     ,  0.116     ,  0.113     ,  0.11      ,
        0.107     ,  0.105     ,  0.102     ,  0.1       ,  0.098     ,
        0.095     ,  0.093     ,  0.091     ,  0.09      ,  0.088     ,
        0.086     ,  0.084     ,  0.083     ,  0.081     ,  0.08      ,
        0.078     ,  0.077     ,  0.076     ,  0.074     , 11.77163014,
        0.072     , 12.15550704,  0.069     ,  0.068     ,  0.067     ,
        0.066     ,  0.065     ,  0.064     ,  0.063     ,  0.062     ,
        0.062     ,  0.061     ,  0.06      ,  0.059     ,  0.058     ,
        0.058     ,  0.057     , 15.91314286,  0.055     ,  0.05

# Partido Libre

In [48]:
x_2 = f0_fe_2_fe.sum()
x_2 

101.16359154659585

In [49]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [50]:
f0 = np.array(f0)
f0

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [51]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.002, 0.   , 0.   , 0.002, 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.002, 0.004, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [52]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [53]:
f0_tot=f0.sum()
f0_tot

10

In [54]:
fe = benford*f0_tot

In [55]:
fe 

array([0.414, 0.378, 0.348, 0.322, 0.3  , 0.28 , 0.263, 0.248, 0.235,
       0.223, 0.212, 0.202, 0.193, 0.185, 0.177, 0.17 , 0.164, 0.158,
       0.152, 0.147, 0.142, 0.138, 0.134, 0.13 , 0.126, 0.122, 0.119,
       0.116, 0.113, 0.11 , 0.107, 0.105, 0.102, 0.1  , 0.098, 0.095,
       0.093, 0.091, 0.09 , 0.088, 0.086, 0.084, 0.083, 0.081, 0.08 ,
       0.078, 0.077, 0.076, 0.074, 0.073, 0.072, 0.071, 0.069, 0.068,
       0.067, 0.066, 0.065, 0.064, 0.063, 0.062, 0.062, 0.061, 0.06 ,
       0.059, 0.058, 0.058, 0.057, 0.056, 0.055, 0.055, 0.054, 0.053,
       0.053, 0.052, 0.051, 0.051, 0.05 , 0.05 , 0.049, 0.049, 0.048,
       0.047, 0.047, 0.046, 0.046, 0.045, 0.045, 0.045, 0.044, 0.044])

In [56]:
fe.sum()

9.999000000000002

In [57]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0358, -0.0348, -0.0322, -0.028 , -0.028 , -0.0263,
       -0.0228, -0.0235, -0.0223, -0.0192, -0.0162, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0132, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.011 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0093, -0.011 , -0.0107, -0.0085, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [58]:
diferencia.sum()

-0.9798999999999999

In [59]:
f0_fe= (f0-fe)

In [60]:
f0_fe_2 = f0_fe*f0_fe

In [61]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.414     ,  1.02350265,  0.348     ,  0.322     ,  1.63333333,
        0.28      ,  0.263     ,  2.28025806,  0.235     ,  0.223     ,
        2.92898113, 16.0039802 ,  0.193     ,  0.185     ,  0.177     ,
        0.17      ,  0.164     ,  0.158     ,  4.73094737,  0.147     ,
        0.142     ,  0.138     ,  0.134     ,  5.82230769,  0.126     ,
        0.122     ,  0.119     ,  0.116     ,  6.96255752,  0.11      ,
        0.107     ,  7.62880952,  0.102     ,  0.1       ,  0.098     ,
        0.095     ,  0.093     ,  0.091     ,  0.09      ,  0.088     ,
        0.086     ,  0.084     ,  0.083     ,  0.081     ,  0.08      ,
        0.078     ,  0.077     ,  0.076     ,  0.074     ,  0.073     ,
        0.072     ,  0.071     ,  0.069     ,  0.068     ,  0.067     ,
        0.066     ,  0.065     ,  0.064     ,  0.063     ,  0.062     ,
        0.062     ,  0.061     ,  0.06      ,  0.059     ,  0.058     ,
        0.058     ,  0.057     ,  0.056     ,  0.055     ,  0.05

# Total

In [62]:
x_2 = f0_fe_2_fe.sum()
x_2 

57.173677480109546