In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1Q7hsUIfweYgBPBSBDYpedZhuGPt0E7GU/export?format=csv")
df

PL     PN  LIBRE-PINU  TOTAL
0   7722  21309       20172  49570
1    368   3093        2563   6043
2    893   5618        3283   9858
3    713   3626        1541   5950
4     87    686         375   1150
5   1407   4722        3506   9676
6    252   1620        1618   3501
7    333   1036         800   2196
8    220   1912        1823   3970
9    571   2264        1390   4258
10  1958   2457        1205   5652
11   587   2639        1901   5165
12   715   5110        3470   9337
13  1131   1523        1033   3715
14   902    660         916   2489
15  1088   2389        1768   5272
16   171    943         765   1882
17  5752  15114       13326  34492
18   893   4238        3717   8919
19  2237   2764        1142   6177
20  1302   4834        4721  10930

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[7722,
 368,
 893,
 713,
 87,
 1407,
 252,
 333,
 220,
 571,
 1958,
 587,
 715,
 1131,
 902,
 1088,
 171,
 5752,
 893,
 2237,
 1302]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[21309,
 3093,
 5618,
 3626,
 686,
 4722,
 1620,
 1036,
 1912,
 2264,
 2457,
 2639,
 5110,
 1523,
 660,
 2389,
 943,
 15114,
 4238,
 2764,
 4834]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[20172,
 2563,
 3283,
 1541,
 375,
 3506,
 1618,
 800,
 1823,
 1390,
 1205,
 1901,
 3470,
 1033,
 916,
 1768,
 765,
 13326,
 3717,
 1142,
 4721]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[49570,
 6043,
 9858,
 5950,
 1150,
 9676,
 3501,
 2196,
 3970,
 4258,
 5652,
 5165,
 9337,
 3715,
 2489,
 5272,
 1882,
 34492,
 8919,
 6177,
 10930]

In [7]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [8]:
f0 = np.array(f0)
f0

array([1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [9]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.002, 0.   , 0.002, 0.002, 0.   , 0.   , 0.002, 0.   ,
       0.002, 0.   , 0.   , 0.004, 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.004, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.004, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.004, 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [10]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [11]:
f0_tot=f0.sum()
f0_tot

21

In [12]:
fe = benford*f0_tot

In [13]:
fe 

array([0.8694, 0.7938, 0.7308, 0.6762, 0.63  , 0.588 , 0.5523, 0.5208,
       0.4935, 0.4683, 0.4452, 0.4242, 0.4053, 0.3885, 0.3717, 0.357 ,
       0.3444, 0.3318, 0.3192, 0.3087, 0.2982, 0.2898, 0.2814, 0.273 ,
       0.2646, 0.2562, 0.2499, 0.2436, 0.2373, 0.231 , 0.2247, 0.2205,
       0.2142, 0.21  , 0.2058, 0.1995, 0.1953, 0.1911, 0.189 , 0.1848,
       0.1806, 0.1764, 0.1743, 0.1701, 0.168 , 0.1638, 0.1617, 0.1596,
       0.1554, 0.1533, 0.1512, 0.1491, 0.1449, 0.1428, 0.1407, 0.1386,
       0.1365, 0.1344, 0.1323, 0.1302, 0.1302, 0.1281, 0.126 , 0.1239,
       0.1218, 0.1218, 0.1197, 0.1176, 0.1155, 0.1155, 0.1134, 0.1113,
       0.1113, 0.1092, 0.1071, 0.1071, 0.105 , 0.105 , 0.1029, 0.1029,
       0.1008, 0.0987, 0.0987, 0.0966, 0.0966, 0.0945, 0.0945, 0.0945,
       0.0924, 0.0924])

In [14]:
fe.sum()

20.9979

In [15]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0358, -0.0348, -0.0302, -0.028 , -0.028 , -0.0263,
       -0.0228, -0.0235, -0.0203, -0.0212, -0.0202, -0.0153, -0.0185,
       -0.0177, -0.015 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.011 , -0.0126, -0.0122, -0.0099, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0036, -0.0054,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0021, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0036, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.003 , -0.0049, -0.0009, -0.0028, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [16]:
diferencia.sum()

-0.9579

In [17]:
f0_fe= (f0-fe)

In [18]:
f0_fe_2 = f0_fe*f0_fe

In [19]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.96185415e-02, 5.35631645e-02, 7.30800000e-01, 1.55052411e-01,
       2.17301587e-01, 5.88000000e-01, 5.52300000e-01, 4.40922888e-01,
       4.93500000e-01, 6.03683301e-01, 4.45200000e-01, 4.24200000e-01,
       6.27453267e+00, 3.88500000e-01, 3.71700000e-01, 1.15812045e+00,
       3.44400000e-01, 3.31800000e-01, 3.19200000e-01, 3.08700000e-01,
       2.98200000e-01, 2.89800000e-01, 2.81400000e-01, 1.93600366e+00,
       2.64600000e-01, 2.56200000e-01, 2.25150064e+00, 2.43600000e-01,
       2.37300000e-01, 2.31000000e-01, 2.24700000e-01, 2.20500000e-01,
       2.14200000e-01, 2.10000000e-01, 2.05800000e-01, 1.99500000e-01,
       1.95300000e-01, 1.91100000e-01, 1.89000000e-01, 1.84800000e-01,
       1.80600000e-01, 1.76400000e-01, 1.74300000e-01, 1.70100000e-01,
       1.68000000e-01, 1.63800000e-01, 1.61700000e-01, 2.12222566e+01,
       4.59040644e+00, 1.53300000e-01, 1.51200000e-01, 1.49100000e-01,
       1.44900000e-01, 1.42800000e-01, 1.40700000e-01, 1.38600000e-01,
      

# Partido Liberal

In [20]:
x_2 = f0_fe_2_fe.sum()
x_2 

138.40830512325786

In [21]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [22]:
f0 = np.array(f0)
f0

array([1, 0, 0, 0, 0, 2, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0])

In [23]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.   , 0.   , 0.   , 0.   , 0.004, 0.002, 0.   , 0.   ,
       0.002, 0.   , 0.002, 0.002, 0.002, 0.002, 0.   , 0.002, 0.002,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.002, 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ])

In [24]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [25]:
f0_tot=f0.sum()
f0_tot

21

In [26]:
fe = benford*f0_tot

In [27]:
fe 

array([0.8694, 0.7938, 0.7308, 0.6762, 0.63  , 0.588 , 0.5523, 0.5208,
       0.4935, 0.4683, 0.4452, 0.4242, 0.4053, 0.3885, 0.3717, 0.357 ,
       0.3444, 0.3318, 0.3192, 0.3087, 0.2982, 0.2898, 0.2814, 0.273 ,
       0.2646, 0.2562, 0.2499, 0.2436, 0.2373, 0.231 , 0.2247, 0.2205,
       0.2142, 0.21  , 0.2058, 0.1995, 0.1953, 0.1911, 0.189 , 0.1848,
       0.1806, 0.1764, 0.1743, 0.1701, 0.168 , 0.1638, 0.1617, 0.1596,
       0.1554, 0.1533, 0.1512, 0.1491, 0.1449, 0.1428, 0.1407, 0.1386,
       0.1365, 0.1344, 0.1323, 0.1302, 0.1302, 0.1281, 0.126 , 0.1239,
       0.1218, 0.1218, 0.1197, 0.1176, 0.1155, 0.1155, 0.1134, 0.1113,
       0.1113, 0.1092, 0.1071, 0.1071, 0.105 , 0.105 , 0.1029, 0.1029,
       0.1008, 0.0987, 0.0987, 0.0966, 0.0966, 0.0945, 0.0945, 0.0945,
       0.0924, 0.0924])

In [28]:
fe.sum()

20.9979

In [29]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0378, -0.0348, -0.0322, -0.03  , -0.024 , -0.0243,
       -0.0248, -0.0235, -0.0203, -0.0212, -0.0182, -0.0173, -0.0165,
       -0.0157, -0.017 , -0.0144, -0.0138, -0.0152, -0.0147, -0.0122,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0099, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0082, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0071, -0.007 , -0.0088, -0.0086, -0.0064,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0057, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0045, -0.0064, -0.0043, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0026, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [30]:
diferencia.sum()

-0.9579

In [31]:
f0_fe= (f0-fe)

In [32]:
f0_fe_2 = f0_fe*f0_fe

In [33]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.01961854, 0.7938    , 0.7308    , 0.6762    , 0.63      ,
       3.39072109, 0.36291018, 0.5208    , 0.4935    , 0.6036833 ,
       0.4452    , 0.7815786 , 0.87260817, 0.96250257, 1.06204167,
       0.357     , 1.24800046, 1.34566377, 0.3192    , 0.3087    ,
       1.65165406, 0.2898    , 0.2814    , 0.273     , 0.2646    ,
       0.2562    , 2.25150064, 0.2436    , 0.2373    , 0.231     ,
       0.2247    , 0.2205    , 2.88273408, 0.21      , 0.2058    ,
       0.1995    , 0.1953    , 3.42396238, 3.48000529, 0.1848    ,
       0.1806    , 3.84533424, 0.1743    , 0.1701    , 0.168     ,
       0.1638    , 4.3459919 , 0.1596    , 0.1554    , 0.1533    ,
       0.1512    , 0.1491    , 0.1449    , 0.1428    , 0.1407    ,
       0.1386    , 5.46250733, 0.1344    , 5.69087899, 0.1302    ,
       0.1302    , 0.1281    , 0.126     , 0.1239    , 0.1218    ,
       0.1218    , 0.1197    , 0.1176    , 0.1155    , 0.1155    ,
       0.1134    , 0.1113    , 0.1113    , 0.1092    , 0.1071 

# Partido Nacional

In [34]:
x_2 = f0_fe_2_fe.sum()
x_2 

66.5405641247743

In [35]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [36]:
f0 = np.array(f0)
f0

array([1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0])

In [37]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.002, 0.002, 0.004, 0.   , 0.002, 0.002, 0.002, 0.002,
       0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.002, 0.002, 0.   ,
       0.004, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [38]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [39]:
f0_tot=f0.sum()
f0_tot

21

In [40]:
fe = benford*f0_tot

In [41]:
fe 

array([0.8694, 0.7938, 0.7308, 0.6762, 0.63  , 0.588 , 0.5523, 0.5208,
       0.4935, 0.4683, 0.4452, 0.4242, 0.4053, 0.3885, 0.3717, 0.357 ,
       0.3444, 0.3318, 0.3192, 0.3087, 0.2982, 0.2898, 0.2814, 0.273 ,
       0.2646, 0.2562, 0.2499, 0.2436, 0.2373, 0.231 , 0.2247, 0.2205,
       0.2142, 0.21  , 0.2058, 0.1995, 0.1953, 0.1911, 0.189 , 0.1848,
       0.1806, 0.1764, 0.1743, 0.1701, 0.168 , 0.1638, 0.1617, 0.1596,
       0.1554, 0.1533, 0.1512, 0.1491, 0.1449, 0.1428, 0.1407, 0.1386,
       0.1365, 0.1344, 0.1323, 0.1302, 0.1302, 0.1281, 0.126 , 0.1239,
       0.1218, 0.1218, 0.1197, 0.1176, 0.1155, 0.1155, 0.1134, 0.1113,
       0.1113, 0.1092, 0.1071, 0.1071, 0.105 , 0.105 , 0.1029, 0.1029,
       0.1008, 0.0987, 0.0987, 0.0966, 0.0966, 0.0945, 0.0945, 0.0945,
       0.0924, 0.0924])

In [42]:
fe.sum()

20.9979

In [43]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0358, -0.0328, -0.0282, -0.03  , -0.026 , -0.0243,
       -0.0228, -0.0215, -0.0203, -0.0192, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.015 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0114, -0.013 , -0.0106, -0.0102, -0.0119, -0.0076,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0071, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0037, -0.0056, -0.0055, -0.0055,
       -0.0034, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0027, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [44]:
diferencia.sum()

-0.9579

In [45]:
f0_fe= (f0-fe)

In [46]:
f0_fe_2 = f0_fe*f0_fe

In [47]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.01961854,  0.05356316,  0.09916344,  2.59160964,  0.63      ,
        0.28868027,  0.36291018,  0.44092289,  0.51984245,  0.6036833 ,
        0.69138149,  0.4242    ,  0.4053    ,  0.3885    ,  0.3717    ,
        1.15812045,  0.3444    ,  0.3318    ,  0.3192    ,  0.3087    ,
        0.2982    ,  0.2898    ,  1.83506027,  0.273     ,  2.04388949,
        2.15940062,  0.2499    , 12.66396125,  0.2373    ,  0.231     ,
        0.2247    ,  0.2205    ,  0.2142    ,  0.21      ,  0.2058    ,
        0.1995    ,  0.1953    ,  3.42396238,  0.189     ,  0.1848    ,
        0.1806    ,  0.1764    ,  0.1743    ,  0.1701    ,  0.168     ,
        0.1638    ,  0.1617    ,  0.1596    ,  0.1554    ,  0.1533    ,
        0.1512    ,  0.1491    ,  0.1449    ,  0.1428    ,  0.1407    ,
        0.1386    ,  0.1365    ,  0.1344    ,  0.1323    ,  0.1302    ,
        0.1302    ,  0.1281    ,  0.126     ,  0.1239    ,  0.1218    ,
        0.1218    ,  6.47391888,  0.1176    ,  0.1155    ,  0.11

# Partido Libre

In [48]:
x_2 = f0_fe_2_fe.sum()
x_2 

63.52574311733267

In [49]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [50]:
f0 = np.array(f0)
f0

array([1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0])

In [51]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.002, 0.   ,
       0.002, 0.   , 0.002, 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.002, 0.002, 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.002, 0.002, 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.002, 0.   , 0.002, 0.   ])

In [52]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [53]:
f0_tot=f0.sum()
f0_tot

21

In [54]:
fe = benford*f0_tot

In [55]:
fe 

array([0.8694, 0.7938, 0.7308, 0.6762, 0.63  , 0.588 , 0.5523, 0.5208,
       0.4935, 0.4683, 0.4452, 0.4242, 0.4053, 0.3885, 0.3717, 0.357 ,
       0.3444, 0.3318, 0.3192, 0.3087, 0.2982, 0.2898, 0.2814, 0.273 ,
       0.2646, 0.2562, 0.2499, 0.2436, 0.2373, 0.231 , 0.2247, 0.2205,
       0.2142, 0.21  , 0.2058, 0.1995, 0.1953, 0.1911, 0.189 , 0.1848,
       0.1806, 0.1764, 0.1743, 0.1701, 0.168 , 0.1638, 0.1617, 0.1596,
       0.1554, 0.1533, 0.1512, 0.1491, 0.1449, 0.1428, 0.1407, 0.1386,
       0.1365, 0.1344, 0.1323, 0.1302, 0.1302, 0.1281, 0.126 , 0.1239,
       0.1218, 0.1218, 0.1197, 0.1176, 0.1155, 0.1155, 0.1134, 0.1113,
       0.1113, 0.1092, 0.1071, 0.1071, 0.105 , 0.105 , 0.1029, 0.1029,
       0.1008, 0.0987, 0.0987, 0.0966, 0.0966, 0.0945, 0.0945, 0.0945,
       0.0924, 0.0924])

In [56]:
fe.sum()

20.9979

In [57]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0358, -0.0348, -0.0322, -0.03  , -0.028 , -0.0263,
       -0.0248, -0.0215, -0.0223, -0.0212, -0.0182, -0.0193, -0.0185,
       -0.0157, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0106, -0.0102, -0.0119, -0.0096,
       -0.0113, -0.009 , -0.0107, -0.0105, -0.0082, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0068, -0.0086, -0.0064,
       -0.0063, -0.0081, -0.008 , -0.0078, -0.0057, -0.0076, -0.0074,
       -0.0053, -0.0052, -0.0051, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0029, -0.0048, -0.0047, -0.0047, -0.0026,
       -0.0046, -0.0045, -0.0025, -0.0045, -0.0024, -0.0044])

In [58]:
diferencia.sum()

-0.9578999999999999

In [59]:
f0_fe= (f0-fe)

In [60]:
f0_fe_2 = f0_fe*f0_fe

In [61]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.01961854, 0.05356316, 0.7308    , 0.6762    , 0.63      ,
       0.588     , 0.5523    , 0.5208    , 0.51984245, 0.4683    ,
       0.4452    , 0.7815786 , 0.4053    , 0.3885    , 1.06204167,
       0.357     , 0.3444    , 0.3318    , 0.3192    , 0.3087    ,
       0.2982    , 0.2898    , 0.2814    , 0.273     , 2.04388949,
       2.15940062, 0.2499    , 2.34869031, 0.2373    , 2.56000433,
       0.2247    , 0.2205    , 2.88273408, 0.21      , 0.2058    ,
       0.1995    , 0.1953    , 0.1911    , 0.189     , 3.59605541,
       0.1806    , 3.84533424, 3.91153465, 0.1701    , 0.168     ,
       0.1638    , 4.3459919 , 0.1596    , 0.1554    , 4.67645721,
       4.76495661, 4.85600812, 0.1449    , 0.1428    , 0.1407    ,
       0.1386    , 0.1365    , 0.1344    , 0.1323    , 0.1302    ,
       0.1302    , 0.1281    , 0.126     , 0.1239    , 0.1218    ,
       0.1218    , 0.1197    , 0.1176    , 0.1155    , 0.1155    ,
       0.1134    , 0.1113    , 0.1113    , 0.1092    , 0.1071 

# Total

In [62]:
x_2 = f0_fe_2_fe.sum()
x_2 

93.5872626676983