In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1cItIweRj42zsfDCCLtBWVaXGOEcMmnUK/export?format=csv")
df

PL    PN  LIBRE-PINU  TOTAL
0   2540  6788       12172  21679
1   2913  2623         928   6497
2    234  1787         994   3043
3   7113  7339        3587  18210
4    423  3194        2662   6317
5   1265  4201        3548   9055
6    476  1326        1296   3122
7    365  1477        1550   3414
8   1459  4373        2367   8260
9   3045  3521        2913   9539
10   523  2148        1423   4115
11   503  3508        4082   8249
12  2739  6319        7428  16569
13   180  1646        1147   3008
14   259  3095        1497   4890
15   939   980        1301   3237
16   158  2245        1478   3900
17   190  2346        2112   4685
18  1205  1351        1316   3899
19  1206  1522        1311   4061
20  2622  4402        3013  10154
21   339  1817        1173   3353
22   271   979         849   2110

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[2540,
 2913,
 234,
 7113,
 423,
 1265,
 476,
 365,
 1459,
 3045,
 523,
 503,
 2739,
 180,
 259,
 939,
 158,
 190,
 1205,
 1206,
 2622,
 339,
 271]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[6788,
 2623,
 1787,
 7339,
 3194,
 4201,
 1326,
 1477,
 4373,
 3521,
 2148,
 3508,
 6319,
 1646,
 3095,
 980,
 2245,
 2346,
 1351,
 1522,
 4402,
 1817,
 979]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[12172,
 928,
 994,
 3587,
 2662,
 3548,
 1296,
 1550,
 2367,
 2913,
 1423,
 4082,
 7428,
 1147,
 1497,
 1301,
 1478,
 2112,
 1316,
 1311,
 3013,
 1173,
 849]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[21679,
 6497,
 3043,
 18210,
 6317,
 9055,
 3122,
 3414,
 8260,
 9539,
 4115,
 8249,
 16569,
 3008,
 4890,
 3237,
 3900,
 4685,
 3899,
 4061,
 10154,
 3353,
 2110]

In [7]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [8]:
f0 = np.array(f0)
f0

array([0, 0, 3, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 2, 1, 2, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0])

In [9]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.   , 0.006, 0.   , 0.002, 0.002, 0.   , 0.   , 0.002,
       0.002, 0.   , 0.   , 0.   , 0.002, 0.   , 0.004, 0.002, 0.004,
       0.   , 0.002, 0.002, 0.   , 0.   , 0.002, 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.002, 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [10]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [11]:
f0_tot=f0.sum()
f0_tot

23

In [12]:
fe = benford*f0_tot

In [13]:
fe 

array([0.9522, 0.8694, 0.8004, 0.7406, 0.69  , 0.644 , 0.6049, 0.5704,
       0.5405, 0.5129, 0.4876, 0.4646, 0.4439, 0.4255, 0.4071, 0.391 ,
       0.3772, 0.3634, 0.3496, 0.3381, 0.3266, 0.3174, 0.3082, 0.299 ,
       0.2898, 0.2806, 0.2737, 0.2668, 0.2599, 0.253 , 0.2461, 0.2415,
       0.2346, 0.23  , 0.2254, 0.2185, 0.2139, 0.2093, 0.207 , 0.2024,
       0.1978, 0.1932, 0.1909, 0.1863, 0.184 , 0.1794, 0.1771, 0.1748,
       0.1702, 0.1679, 0.1656, 0.1633, 0.1587, 0.1564, 0.1541, 0.1518,
       0.1495, 0.1472, 0.1449, 0.1426, 0.1426, 0.1403, 0.138 , 0.1357,
       0.1334, 0.1334, 0.1311, 0.1288, 0.1265, 0.1265, 0.1242, 0.1219,
       0.1219, 0.1196, 0.1173, 0.1173, 0.115 , 0.115 , 0.1127, 0.1127,
       0.1104, 0.1081, 0.1081, 0.1058, 0.1058, 0.1035, 0.1035, 0.1035,
       0.1012, 0.1012])

In [14]:
fe.sum()

22.9977

In [15]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0378, -0.0288, -0.0322, -0.028 , -0.026 , -0.0263,
       -0.0248, -0.0215, -0.0203, -0.0212, -0.0202, -0.0193, -0.0165,
       -0.0177, -0.013 , -0.0144, -0.0118, -0.0152, -0.0127, -0.0122,
       -0.0138, -0.0134, -0.011 , -0.0126, -0.0122, -0.0099, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0082, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0071, -0.009 , -0.0088, -0.0066, -0.0084,
       -0.0063, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0041, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0026,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [16]:
diferencia.sum()

-0.9539

In [17]:
f0_fe= (f0-fe)

In [18]:
f0_fe_2 = f0_fe*f0_fe

In [19]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.9522    , 0.8694    , 6.04477781, 0.7406    , 0.13927536,
       0.19679503, 0.6049    , 0.5704    , 0.39063876, 0.4625978 ,
       0.4876    , 0.4646    , 0.4439    , 0.77567626, 0.4071    ,
       6.62117903, 1.02831347, 7.37055465, 0.3496    , 1.29580482,
       1.38844936, 0.3174    , 0.3082    , 1.64348161, 0.2898    ,
       0.2806    , 1.92733537, 0.2668    , 0.2599    , 0.253     ,
       0.2461    , 0.2415    , 2.4971746 , 0.23      , 0.2254    ,
       0.2185    , 0.2139    , 2.98713086, 0.207     , 0.2024    ,
       3.25341173, 0.1932    , 3.42924468, 0.1863    , 0.184     ,
       0.1794    , 0.1771    , 0.1748    , 0.1702    , 0.1679    ,
       0.1656    , 0.1633    , 0.1587    , 0.1564    , 0.1541    ,
       0.1518    , 0.1495    , 0.1472    , 0.1449    , 0.1426    ,
       0.1426    , 5.26788375, 0.138     , 0.1357    , 0.1334    ,
       0.1334    , 0.1311    , 0.1288    , 0.1265    , 0.1265    ,
       0.1242    , 0.1219    , 0.1219    , 0.1196    , 0.1173 

# Partido Liberal

In [20]:
x_2 = f0_fe_2_fe.sum()
x_2 

70.21402078412277

In [21]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [22]:
f0 = np.array(f0)
f0

array([0, 0, 0, 2, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0])

In [23]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.   , 0.   , 0.004, 0.002, 0.002, 0.002, 0.002, 0.002,
       0.   , 0.   , 0.002, 0.002, 0.002, 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.004, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.002, 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.002, 0.   ])

In [24]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [25]:
f0_tot=f0.sum()
f0_tot

23

In [26]:
fe = benford*f0_tot

In [27]:
fe 

array([0.9522, 0.8694, 0.8004, 0.7406, 0.69  , 0.644 , 0.6049, 0.5704,
       0.5405, 0.5129, 0.4876, 0.4646, 0.4439, 0.4255, 0.4071, 0.391 ,
       0.3772, 0.3634, 0.3496, 0.3381, 0.3266, 0.3174, 0.3082, 0.299 ,
       0.2898, 0.2806, 0.2737, 0.2668, 0.2599, 0.253 , 0.2461, 0.2415,
       0.2346, 0.23  , 0.2254, 0.2185, 0.2139, 0.2093, 0.207 , 0.2024,
       0.1978, 0.1932, 0.1909, 0.1863, 0.184 , 0.1794, 0.1771, 0.1748,
       0.1702, 0.1679, 0.1656, 0.1633, 0.1587, 0.1564, 0.1541, 0.1518,
       0.1495, 0.1472, 0.1449, 0.1426, 0.1426, 0.1403, 0.138 , 0.1357,
       0.1334, 0.1334, 0.1311, 0.1288, 0.1265, 0.1265, 0.1242, 0.1219,
       0.1219, 0.1196, 0.1173, 0.1173, 0.115 , 0.115 , 0.1127, 0.1127,
       0.1104, 0.1081, 0.1081, 0.1058, 0.1058, 0.1035, 0.1035, 0.1035,
       0.1012, 0.1012])

In [28]:
fe.sum()

22.9977

In [29]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0378, -0.0348, -0.0282, -0.028 , -0.026 , -0.0243,
       -0.0228, -0.0215, -0.0223, -0.0212, -0.0182, -0.0173, -0.0165,
       -0.0177, -0.017 , -0.0144, -0.0158, -0.0152, -0.0147, -0.0122,
       -0.0118, -0.0134, -0.013 , -0.0126, -0.0082, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0082, -0.008 , -0.0078,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0048, -0.0067, -0.0066,
       -0.0065, -0.0044, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0039, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0025, -0.0024, -0.0044])

In [30]:
diferencia.sum()

-0.9538999999999999

In [31]:
f0_fe= (f0-fe)

In [32]:
f0_fe_2 = f0_fe*f0_fe

In [33]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.9522    ,  0.8694    ,  0.8004    ,  2.14162619,  0.13927536,
        0.19679503,  0.25806581,  0.32355568,  0.39063876,  0.5129    ,
        0.4876    ,  0.61698915,  0.69665963,  0.77567626,  0.4071    ,
        0.391     ,  1.02831347,  0.3634    ,  0.3496    ,  0.3381    ,
        1.38844936,  1.46799861,  0.3082    ,  0.299     ,  0.2898    ,
       10.5357675 ,  0.2737    ,  0.2668    ,  0.2599    ,  0.253     ,
        0.2461    ,  0.2415    ,  2.4971746 ,  2.57782609,  2.66195723,
        0.2185    ,  0.2139    ,  0.2093    ,  0.207     ,  0.2024    ,
        0.1978    ,  0.1932    ,  0.1909    ,  0.1863    ,  0.184     ,
        0.1794    ,  0.1771    ,  0.1748    ,  0.1702    ,  0.1679    ,
        0.1656    ,  0.1633    ,  0.1587    ,  4.55026189,  0.1541    ,
        0.1518    ,  0.1495    ,  4.94067826,  0.1449    ,  0.1426    ,
        0.1426    ,  0.1403    ,  0.138     ,  5.50489676,  0.1334    ,
        0.1334    ,  0.1311    ,  0.1288    ,  0.1265    ,  0.12

# Partido Nacional

In [34]:
x_2 = f0_fe_2_fe.sum()
x_2 

73.67806432216261

In [35]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [36]:
f0 = np.array(f0)
f0

array([0, 2, 2, 3, 3, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1])

In [37]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.004, 0.004, 0.006, 0.006, 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.002, 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.004, 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002])

In [38]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [39]:
f0_tot=f0.sum()
f0_tot

23

In [40]:
fe = benford*f0_tot

In [41]:
fe 

array([0.9522, 0.8694, 0.8004, 0.7406, 0.69  , 0.644 , 0.6049, 0.5704,
       0.5405, 0.5129, 0.4876, 0.4646, 0.4439, 0.4255, 0.4071, 0.391 ,
       0.3772, 0.3634, 0.3496, 0.3381, 0.3266, 0.3174, 0.3082, 0.299 ,
       0.2898, 0.2806, 0.2737, 0.2668, 0.2599, 0.253 , 0.2461, 0.2415,
       0.2346, 0.23  , 0.2254, 0.2185, 0.2139, 0.2093, 0.207 , 0.2024,
       0.1978, 0.1932, 0.1909, 0.1863, 0.184 , 0.1794, 0.1771, 0.1748,
       0.1702, 0.1679, 0.1656, 0.1633, 0.1587, 0.1564, 0.1541, 0.1518,
       0.1495, 0.1472, 0.1449, 0.1426, 0.1426, 0.1403, 0.138 , 0.1357,
       0.1334, 0.1334, 0.1311, 0.1288, 0.1265, 0.1265, 0.1242, 0.1219,
       0.1219, 0.1196, 0.1173, 0.1173, 0.115 , 0.115 , 0.1127, 0.1127,
       0.1104, 0.1081, 0.1081, 0.1058, 0.1058, 0.1035, 0.1035, 0.1035,
       0.1012, 0.1012])

In [42]:
fe.sum()

22.9977

In [43]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0338, -0.0308, -0.0262, -0.024 , -0.026 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0182, -0.0193, -0.0165,
       -0.0177, -0.017 , -0.0144, -0.0158, -0.0152, -0.0127, -0.0122,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0082, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0087, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0038, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0031, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0027, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0024])

In [44]:
diferencia.sum()

-0.9538999999999999

In [45]:
f0_fe= (f0-fe)

In [46]:
f0_fe_2 = f0_fe*f0_fe

In [47]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.9522    ,  1.47027417,  1.79790125,  6.89290894,  7.73347826,
        0.19679503,  0.6049    ,  0.5704    ,  0.5405    ,  0.5129    ,
        0.4876    ,  0.61698915,  0.4439    ,  0.77567626,  0.4071    ,
        0.391     ,  1.02831347,  0.3634    ,  0.3496    ,  1.29580482,
        1.38844936,  0.3174    ,  0.3082    ,  0.299     ,  0.2898    ,
       10.5357675 ,  0.2737    ,  0.2668    ,  0.2599    ,  0.253     ,
        2.30948887,  0.2415    ,  0.2346    ,  0.23      ,  0.2254    ,
        0.2185    ,  0.2139    ,  0.2093    ,  0.207     ,  0.2024    ,
        0.1978    ,  0.1932    ,  0.1909    ,  0.1863    ,  0.184     ,
        0.1794    ,  0.1771    ,  0.1748    ,  0.1702    ,  0.1679    ,
        0.1656    ,  0.1633    ,  0.1587    ,  0.1564    ,  0.1541    ,
        0.1518    ,  0.1495    ,  0.1472    ,  0.1449    ,  0.1426    ,
        0.1426    ,  0.1403    ,  0.138     ,  0.1357    ,  5.62965187,
        0.1334    ,  0.1311    ,  0.1288    ,  0.1265    ,  0.12

# Partido Libre

In [48]:
x_2 = f0_fe_2_fe.sum()
x_2 

79.98996486263877

In [49]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [50]:
f0 = np.array(f0)
f0

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0])

In [51]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.002,
       0.   , 0.   , 0.004, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.004, 0.002, 0.002, 0.002, 0.002, 0.   , 0.   ,
       0.   , 0.002, 0.002, 0.002, 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.004, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ])

In [52]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [53]:
f0_tot=f0.sum()
f0_tot

23

In [54]:
fe = benford*f0_tot

In [55]:
fe 

array([0.9522, 0.8694, 0.8004, 0.7406, 0.69  , 0.644 , 0.6049, 0.5704,
       0.5405, 0.5129, 0.4876, 0.4646, 0.4439, 0.4255, 0.4071, 0.391 ,
       0.3772, 0.3634, 0.3496, 0.3381, 0.3266, 0.3174, 0.3082, 0.299 ,
       0.2898, 0.2806, 0.2737, 0.2668, 0.2599, 0.253 , 0.2461, 0.2415,
       0.2346, 0.23  , 0.2254, 0.2185, 0.2139, 0.2093, 0.207 , 0.2024,
       0.1978, 0.1932, 0.1909, 0.1863, 0.184 , 0.1794, 0.1771, 0.1748,
       0.1702, 0.1679, 0.1656, 0.1633, 0.1587, 0.1564, 0.1541, 0.1518,
       0.1495, 0.1472, 0.1449, 0.1426, 0.1426, 0.1403, 0.138 , 0.1357,
       0.1334, 0.1334, 0.1311, 0.1288, 0.1265, 0.1265, 0.1242, 0.1219,
       0.1219, 0.1196, 0.1173, 0.1173, 0.115 , 0.115 , 0.1127, 0.1127,
       0.1104, 0.1081, 0.1081, 0.1058, 0.1058, 0.1035, 0.1035, 0.1035,
       0.1012, 0.1012])

In [56]:
fe.sum()

22.9977

In [57]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0378, -0.0348, -0.0322, -0.03  , -0.028 , -0.0243,
       -0.0248, -0.0215, -0.0223, -0.0212, -0.0162, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0102,
       -0.0118, -0.0114, -0.011 , -0.0106, -0.0122, -0.0119, -0.0116,
       -0.0093, -0.009 , -0.0087, -0.0085, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0073, -0.0091, -0.007 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0048, -0.0047, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0013, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0028, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0025, -0.0045, -0.0045, -0.0044, -0.0044])

In [58]:
diferencia.sum()

-0.9539

In [59]:
f0_fe= (f0-fe)

In [60]:
f0_fe_2 = f0_fe*f0_fe

In [61]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.39953791e-03, 8.69400000e-01, 8.00400000e-01, 7.40600000e-01,
       6.90000000e-01, 6.44000000e-01, 2.58065813e-01, 5.70400000e-01,
       3.90638760e-01, 5.12900000e-01, 4.87600000e-01, 5.07415661e+00,
       4.43900000e-01, 4.25500000e-01, 4.07100000e-01, 3.91000000e-01,
       3.77200000e-01, 3.63400000e-01, 3.49600000e-01, 3.38100000e-01,
       8.57399743e+00, 1.46799861e+00, 1.55284633e+00, 1.64348161e+00,
       1.74045562e+00, 2.80600000e-01, 2.73700000e-01, 2.66800000e-01,
       2.10753371e+00, 2.20556917e+00, 2.30948887e+00, 2.38228675e+00,
       2.34600000e-01, 2.30000000e-01, 2.25400000e-01, 2.18500000e-01,
       2.88898181e+00, 2.09300000e-01, 3.03791787e+00, 2.02400000e-01,
       1.97800000e-01, 1.93200000e-01, 1.90900000e-01, 1.86300000e-01,
       1.84000000e-01, 1.79400000e-01, 1.77100000e-01, 1.74800000e-01,
       1.70200000e-01, 1.67900000e-01, 1.65600000e-01, 1.63300000e-01,
       1.58700000e-01, 4.55026189e+00, 4.64339267e+00, 1.51800000e-01,
      

# Total

In [62]:
x_2 = f0_fe_2_fe.sum()
x_2 

105.52566161461264