In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1yfDyVKJeRiSLsxhyY0lCcHa3bHP5Bv7X/export?format=csv")
df

PL     PN  LIBRE-PINU   TOTAL
0   22010  73088      122234  219685
1    5922  20363       38592   65345
2    1117   9134        5884   16254
3     360   3400        3208    7081
4    1154   4289        4420    9927
5   10022  12814       23754   47002
6     698   4231        4202    9201
7    1318   3310        4252    8961
8    1218   3551        9041   13911
9    4262   9999       13711   28160
10   4375  11062       22567   38289
11   3384   5882       19182   28957

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[22010, 5922, 1117, 360, 1154, 10022, 698, 1318, 1218, 4262, 4375, 3384]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[73088, 20363, 9134, 3400, 4289, 12814, 4231, 3310, 3551, 9999, 11062, 5882]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[122234, 38592, 5884, 3208, 4420, 23754, 4202, 4252, 9041, 13711, 22567, 19182]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[219685,
 65345,
 16254,
 7081,
 9927,
 47002,
 9201,
 8961,
 13911,
 28160,
 38289,
 28957]

In [7]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [8]:
f0 = np.array(f0)
f0

array([1, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [9]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.004, 0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [10]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [11]:
f0_tot=f0.sum()
f0_tot

12

In [12]:
fe = benford*f0_tot

In [13]:
fe 

array([0.4968, 0.4536, 0.4176, 0.3864, 0.36  , 0.336 , 0.3156, 0.2976,
       0.282 , 0.2676, 0.2544, 0.2424, 0.2316, 0.222 , 0.2124, 0.204 ,
       0.1968, 0.1896, 0.1824, 0.1764, 0.1704, 0.1656, 0.1608, 0.156 ,
       0.1512, 0.1464, 0.1428, 0.1392, 0.1356, 0.132 , 0.1284, 0.126 ,
       0.1224, 0.12  , 0.1176, 0.114 , 0.1116, 0.1092, 0.108 , 0.1056,
       0.1032, 0.1008, 0.0996, 0.0972, 0.096 , 0.0936, 0.0924, 0.0912,
       0.0888, 0.0876, 0.0864, 0.0852, 0.0828, 0.0816, 0.0804, 0.0792,
       0.078 , 0.0768, 0.0756, 0.0744, 0.0744, 0.0732, 0.072 , 0.0708,
       0.0696, 0.0696, 0.0684, 0.0672, 0.066 , 0.066 , 0.0648, 0.0636,
       0.0636, 0.0624, 0.0612, 0.0612, 0.06  , 0.06  , 0.0588, 0.0588,
       0.0576, 0.0564, 0.0564, 0.0552, 0.0552, 0.054 , 0.054 , 0.054 ,
       0.0528, 0.0528])

In [14]:
fe.sum()

11.9988

In [15]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0338, -0.0328, -0.0302, -0.03  , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0202, -0.0173, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.011 , -0.0126, -0.0122, -0.0099, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0082, -0.008 , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0053, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0042, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [16]:
diferencia.sum()

-0.9758999999999999

In [17]:
f0_fe= (f0-fe)

In [18]:
f0_fe_2 = f0_fe*f0_fe

In [19]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.50968245,  5.27194215,  0.81223602,  0.97439172,  0.36      ,
        0.336     ,  0.3156    ,  0.2976    ,  0.282     ,  0.2676    ,
        0.2544    ,  0.2424    ,  2.54938929,  0.222     ,  0.2124    ,
        0.204     ,  0.1968    ,  0.1896    ,  0.1824    ,  0.1764    ,
        0.1704    ,  0.1656    ,  0.1608    ,  4.56625641,  0.1512    ,
        0.1464    ,  5.14560112,  0.1392    ,  0.1356    ,  0.132     ,
        0.1284    ,  0.126     ,  6.29233464,  6.45333333,  0.1176    ,
        0.114     ,  0.1116    ,  0.1092    ,  0.108     ,  0.1056    ,
        0.1032    ,  0.1008    ,  0.0996    ,  0.0972    ,  0.096     ,
        0.0936    ,  0.0924    ,  0.0912    ,  0.0888    ,  9.50312511,
        0.0864    ,  0.0852    ,  0.0828    ,  0.0816    ,  0.0804    ,
        0.0792    ,  0.078     ,  0.0768    ,  0.0756    , 11.51526022,
        0.0744    ,  0.0732    ,  0.072     ,  0.0708    ,  0.0696    ,
        0.0696    ,  0.0684    ,  0.0672    ,  0.066     ,  0.06

# Partido Liberal

In [20]:
x_2 = f0_fe_2_fe.sum()
x_2 

62.90315245874507

In [21]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [22]:
f0 = np.array(f0)
f0

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1])

In [23]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.002, 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.004, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002])

In [24]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [25]:
f0_tot=f0.sum()
f0_tot

12

In [26]:
fe = benford*f0_tot

In [27]:
fe 

array([0.4968, 0.4536, 0.4176, 0.3864, 0.36  , 0.336 , 0.3156, 0.2976,
       0.282 , 0.2676, 0.2544, 0.2424, 0.2316, 0.222 , 0.2124, 0.204 ,
       0.1968, 0.1896, 0.1824, 0.1764, 0.1704, 0.1656, 0.1608, 0.156 ,
       0.1512, 0.1464, 0.1428, 0.1392, 0.1356, 0.132 , 0.1284, 0.126 ,
       0.1224, 0.12  , 0.1176, 0.114 , 0.1116, 0.1092, 0.108 , 0.1056,
       0.1032, 0.1008, 0.0996, 0.0972, 0.096 , 0.0936, 0.0924, 0.0912,
       0.0888, 0.0876, 0.0864, 0.0852, 0.0828, 0.0816, 0.0804, 0.0792,
       0.078 , 0.0768, 0.0756, 0.0744, 0.0744, 0.0732, 0.072 , 0.0708,
       0.0696, 0.0696, 0.0684, 0.0672, 0.066 , 0.066 , 0.0648, 0.0636,
       0.0636, 0.0624, 0.0612, 0.0612, 0.06  , 0.06  , 0.0588, 0.0588,
       0.0576, 0.0564, 0.0564, 0.0552, 0.0552, 0.054 , 0.054 , 0.054 ,
       0.0528, 0.0528])

In [28]:
fe.sum()

11.9988

In [29]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0358, -0.0328, -0.0322, -0.03  , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0192, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.011 , -0.0106, -0.0102, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0062, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0054,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0039, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0027, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0024])

In [30]:
diferencia.sum()

-0.9759

In [31]:
f0_fe= (f0-fe)

In [32]:
f0_fe_2 = f0_fe*f0_fe

In [33]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.4968    ,  0.65818554,  0.81223602,  0.3864    ,  0.36      ,
        0.336     ,  0.3156    ,  0.2976    ,  0.282     ,  0.2676    ,
        2.18521761,  0.2424    ,  0.2316    ,  0.222     ,  0.2124    ,
        0.204     ,  0.1968    ,  0.1896    ,  0.1824    ,  0.1764    ,
        0.1704    ,  0.1656    ,  0.1608    ,  4.56625641,  4.76495661,
        4.97700109,  0.1428    ,  0.1392    ,  0.1356    ,  0.132     ,
        0.1284    ,  0.126     , 28.80213856,  0.12      ,  0.1176    ,
        0.114     ,  0.1116    ,  0.1092    ,  0.108     ,  0.1056    ,
        0.1032    ,  0.1008    ,  0.0996    ,  0.0972    ,  0.096     ,
        0.0936    ,  0.0924    ,  0.0912    ,  9.35006126,  0.0876    ,
        0.0864    ,  0.0852    ,  0.0828    ,  0.0816    ,  0.0804    ,
        0.0792    ,  0.078     ,  0.0768    ,  0.0756    ,  0.0744    ,
        0.0744    ,  0.0732    ,  0.072     , 12.19509379,  0.0696    ,
        0.0696    ,  0.0684    ,  0.0672    ,  0.066     ,  0.06

# Partido Nacional

In [34]:
x_2 = f0_fe_2_fe.sum()
x_2 

111.11863728217479

In [35]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [36]:
f0 = np.array(f0)
f0

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [37]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.004, 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [38]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [39]:
f0_tot=f0.sum()
f0_tot

12

In [40]:
fe = benford*f0_tot

In [41]:
fe 

array([0.4968, 0.4536, 0.4176, 0.3864, 0.36  , 0.336 , 0.3156, 0.2976,
       0.282 , 0.2676, 0.2544, 0.2424, 0.2316, 0.222 , 0.2124, 0.204 ,
       0.1968, 0.1896, 0.1824, 0.1764, 0.1704, 0.1656, 0.1608, 0.156 ,
       0.1512, 0.1464, 0.1428, 0.1392, 0.1356, 0.132 , 0.1284, 0.126 ,
       0.1224, 0.12  , 0.1176, 0.114 , 0.1116, 0.1092, 0.108 , 0.1056,
       0.1032, 0.1008, 0.0996, 0.0972, 0.096 , 0.0936, 0.0924, 0.0912,
       0.0888, 0.0876, 0.0864, 0.0852, 0.0828, 0.0816, 0.0804, 0.0792,
       0.078 , 0.0768, 0.0756, 0.0744, 0.0744, 0.0732, 0.072 , 0.0708,
       0.0696, 0.0696, 0.0684, 0.0672, 0.066 , 0.066 , 0.0648, 0.0636,
       0.0636, 0.0624, 0.0612, 0.0612, 0.06  , 0.06  , 0.0588, 0.0588,
       0.0576, 0.0564, 0.0564, 0.0552, 0.0552, 0.054 , 0.054 , 0.054 ,
       0.0528, 0.0528])

In [42]:
fe.sum()

11.9988

In [43]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0378, -0.0328, -0.0302, -0.03  , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0203, -0.0212, -0.0202, -0.0173, -0.0165,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0114, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0093, -0.011 , -0.0107, -0.0105, -0.0062, -0.01  , -0.0078,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0054,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0028, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [44]:
diferencia.sum()

-0.9759

In [45]:
f0_fe= (f0-fe)

In [46]:
f0_fe_2 = f0_fe*f0_fe

In [47]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.4968    ,  0.4536    ,  0.81223602,  0.97439172,  0.36      ,
        0.336     ,  0.3156    ,  0.2976    ,  0.282     ,  2.00452078,
        0.2544    ,  0.2424    ,  2.54938929,  2.7265045 ,  0.2124    ,
        0.204     ,  0.1968    ,  0.1896    ,  0.1824    ,  0.1764    ,
        0.1704    ,  0.1656    ,  4.37970547,  0.156     ,  0.1512    ,
        0.1464    ,  0.1428    ,  0.1392    ,  5.51023127,  0.132     ,
        0.1284    ,  0.126     , 28.80213856,  0.12      ,  6.62100136,
        0.114     ,  0.1116    ,  0.1092    ,  0.108     ,  0.1056    ,
        0.1032    ,  0.1008    ,  0.0996    ,  0.0972    ,  0.096     ,
        0.0936    ,  0.0924    ,  0.0912    ,  9.35006126,  0.0876    ,
        0.0864    ,  0.0852    ,  0.0828    ,  0.0816    ,  0.0804    ,
        0.0792    ,  0.078     ,  0.0768    ,  0.0756    ,  0.0744    ,
        0.0744    ,  0.0732    ,  0.072     ,  0.0708    ,  0.0696    ,
        0.0696    ,  0.0684    ,  0.0672    ,  0.066     ,  0.06

# Partido Libre

In [48]:
x_2 = f0_fe_2_fe.sum()
x_2 

88.93969134350026

In [49]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [50]:
f0 = np.array(f0)
f0

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1])

In [51]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.004, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002])

In [52]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [53]:
f0_tot=f0.sum()
f0_tot

12

In [54]:
fe = benford*f0_tot

In [55]:
fe 

array([0.4968, 0.4536, 0.4176, 0.3864, 0.36  , 0.336 , 0.3156, 0.2976,
       0.282 , 0.2676, 0.2544, 0.2424, 0.2316, 0.222 , 0.2124, 0.204 ,
       0.1968, 0.1896, 0.1824, 0.1764, 0.1704, 0.1656, 0.1608, 0.156 ,
       0.1512, 0.1464, 0.1428, 0.1392, 0.1356, 0.132 , 0.1284, 0.126 ,
       0.1224, 0.12  , 0.1176, 0.114 , 0.1116, 0.1092, 0.108 , 0.1056,
       0.1032, 0.1008, 0.0996, 0.0972, 0.096 , 0.0936, 0.0924, 0.0912,
       0.0888, 0.0876, 0.0864, 0.0852, 0.0828, 0.0816, 0.0804, 0.0792,
       0.078 , 0.0768, 0.0756, 0.0744, 0.0744, 0.0732, 0.072 , 0.0708,
       0.0696, 0.0696, 0.0684, 0.0672, 0.066 , 0.066 , 0.0648, 0.0636,
       0.0636, 0.0624, 0.0612, 0.0612, 0.06  , 0.06  , 0.0588, 0.0588,
       0.0576, 0.0564, 0.0564, 0.0552, 0.0552, 0.054 , 0.054 , 0.054 ,
       0.0528, 0.0528])

In [56]:
fe.sum()

11.9988

In [57]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0378, -0.0348, -0.0302, -0.03  , -0.028 , -0.0243,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0182, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0112, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0093, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0071, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0046,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0042, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0029, -0.0048, -0.0047, -0.0027, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0024])

In [58]:
diferencia.sum()

-0.9758999999999999

In [59]:
f0_fe= (f0-fe)

In [60]:
f0_fe_2 = f0_fe*f0_fe

In [61]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.4968    ,  0.4536    ,  0.4176    ,  0.97439172,  0.36      ,
        0.336     ,  1.48416781,  0.2976    ,  0.282     ,  0.2676    ,
        0.2544    ,  2.36781254,  0.2316    ,  0.222     ,  0.2124    ,
        0.204     ,  0.1968    ,  0.1896    , 18.11222456,  0.1764    ,
        0.1704    ,  0.1656    ,  0.1608    ,  0.156     ,  0.1512    ,
        0.1464    ,  0.1428    ,  0.1392    ,  5.51023127,  0.132     ,
        0.1284    ,  0.126     ,  0.1224    ,  0.12      ,  0.1176    ,
        0.114     ,  0.1116    ,  7.26670916,  0.108     ,  0.1056    ,
        0.1032    ,  0.1008    ,  0.0996    ,  0.0972    ,  0.096     ,
        0.0936    ,  0.0924    ,  0.0912    ,  0.0888    ,  0.0876    ,
        0.0864    ,  0.0852    ,  0.0828    ,  0.0816    ,  0.0804    ,
       10.70546263,  0.078     ,  0.0768    ,  0.0756    ,  0.0744    ,
       11.51526022,  0.0732    ,  0.072     ,  0.0708    ,  0.0696    ,
        0.0696    ,  0.0684    ,  0.0672    ,  0.066     ,  0.06

# Total

In [62]:
x_2 = f0_fe_2_fe.sum()
x_2 

116.08655301008044