In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1bviWBACEUUG9cXOLQd0cFYXtROj570cJ/export?format=csv")
df

PL     PN  LIBRE-PINU  TOTAL
0    1062   4419        1969   7519
1     938   3091        1916   5973
2   13589  29725       26887  70714
3    4749   9644        5603  20120
4     888   2395        1322   4641
5     717   1440        1105   3276
6    1920   3189        1701   6832
7    1401   3544        1765   6760
8     369   2142        1414   3943
9     460    883         580   1935
10    728   2102         820   3666
11   1638   2172         674   4531
12    819   1394         832   3068
13   1378   1955        2210   5588
14   4283   6855        4944  16237
15   1821   2574         937   5371
16   1013   1143         390   2554
17    175    669         324   1175
18   3561  10293        6575  20642

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[1062,
 938,
 13589,
 4749,
 888,
 717,
 1920,
 1401,
 369,
 460,
 728,
 1638,
 819,
 1378,
 4283,
 1821,
 1013,
 175,
 3561]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[4419,
 3091,
 29725,
 9644,
 2395,
 1440,
 3189,
 3544,
 2142,
 883,
 2102,
 2172,
 1394,
 1955,
 6855,
 2574,
 1143,
 669,
 10293]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[1969,
 1916,
 26887,
 5603,
 1322,
 1105,
 1701,
 1765,
 1414,
 580,
 820,
 674,
 832,
 2210,
 4944,
 937,
 390,
 324,
 6575]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[7519,
 5973,
 70714,
 20120,
 4641,
 3276,
 6832,
 6760,
 3943,
 1935,
 3666,
 4531,
 3068,
 5588,
 16237,
 5371,
 2554,
 1175,
 20642]

In [7]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [8]:
f0 = np.array(f0)
f0

array([2, 0, 0, 2, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0])

In [9]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.004, 0.   , 0.   , 0.004, 0.002, 0.   , 0.002, 0.002, 0.002,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [10]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [11]:
f0_tot=f0.sum()
f0_tot

19

In [12]:
fe = benford*f0_tot

In [13]:
fe 

array([0.7866, 0.7182, 0.6612, 0.6118, 0.57  , 0.532 , 0.4997, 0.4712,
       0.4465, 0.4237, 0.4028, 0.3838, 0.3667, 0.3515, 0.3363, 0.323 ,
       0.3116, 0.3002, 0.2888, 0.2793, 0.2698, 0.2622, 0.2546, 0.247 ,
       0.2394, 0.2318, 0.2261, 0.2204, 0.2147, 0.209 , 0.2033, 0.1995,
       0.1938, 0.19  , 0.1862, 0.1805, 0.1767, 0.1729, 0.171 , 0.1672,
       0.1634, 0.1596, 0.1577, 0.1539, 0.152 , 0.1482, 0.1463, 0.1444,
       0.1406, 0.1387, 0.1368, 0.1349, 0.1311, 0.1292, 0.1273, 0.1254,
       0.1235, 0.1216, 0.1197, 0.1178, 0.1178, 0.1159, 0.114 , 0.1121,
       0.1102, 0.1102, 0.1083, 0.1064, 0.1045, 0.1045, 0.1026, 0.1007,
       0.1007, 0.0988, 0.0969, 0.0969, 0.095 , 0.095 , 0.0931, 0.0931,
       0.0912, 0.0893, 0.0893, 0.0874, 0.0874, 0.0855, 0.0855, 0.0855,
       0.0836, 0.0836])

In [14]:
fe.sum()

18.9981

In [15]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0374, -0.0378, -0.0348, -0.0282, -0.028 , -0.028 , -0.0243,
       -0.0228, -0.0215, -0.0203, -0.0212, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0102, -0.0099, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0082, -0.01  , -0.0098,
       -0.0095, -0.0073, -0.0071, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0041, -0.004 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0033, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0029, -0.0049, -0.0048, -0.0047, -0.0047, -0.0026,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [16]:
diferencia.sum()

-0.9619

In [17]:
f0_fe= (f0-fe)

In [18]:
f0_fe_2 = f0_fe*f0_fe

In [19]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.87177671, 0.7182    , 0.6612    , 3.14988434, 0.32438596,
       0.532     , 0.50090072, 0.59344109, 0.68614166, 0.78386049,
       0.4028    , 0.3838    , 0.3667    , 0.3515    , 0.3363    ,
       0.323     , 0.3116    , 0.3002    , 0.2888    , 0.2793    ,
       0.2698    , 0.2622    , 0.2546    , 0.247     , 0.2394    ,
       2.54586385, 2.64892176, 0.2204    , 0.2147    , 0.209     ,
       0.2033    , 0.1995    , 3.35375872, 0.19      , 0.1862    ,
       0.1805    , 3.83600956, 3.95658999, 0.171     , 0.1672    ,
       0.1634    , 0.1596    , 0.1577    , 0.1539    , 0.152     ,
       0.1482    , 0.1463    , 0.1444    , 0.1406    , 0.1387    ,
       0.1368    , 0.1349    , 0.1311    , 0.1292    , 0.1273    ,
       0.1254    , 0.1235    , 0.1216    , 0.1197    , 0.1178    ,
       0.1178    , 6.7440277 , 6.88592982, 0.1121    , 0.1102    ,
       0.1102    , 0.1083    , 0.1064    , 0.1045    , 0.1045    ,
       0.1026    , 8.03118659, 0.1007    , 0.0988    , 0.0969 

# Partido Liberal

In [20]:
x_2 = f0_fe_2_fe.sum()
x_2 

77.95216513120242

In [21]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [22]:
f0 = np.array(f0)
f0

array([1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 3, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0])

In [23]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.002, 0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.006, 0.   , 0.002, 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.002, 0.002, 0.002, 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ])

In [24]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [25]:
f0_tot=f0.sum()
f0_tot

19

In [26]:
fe = benford*f0_tot

In [27]:
fe 

array([0.7866, 0.7182, 0.6612, 0.6118, 0.57  , 0.532 , 0.4997, 0.4712,
       0.4465, 0.4237, 0.4028, 0.3838, 0.3667, 0.3515, 0.3363, 0.323 ,
       0.3116, 0.3002, 0.2888, 0.2793, 0.2698, 0.2622, 0.2546, 0.247 ,
       0.2394, 0.2318, 0.2261, 0.2204, 0.2147, 0.209 , 0.2033, 0.1995,
       0.1938, 0.19  , 0.1862, 0.1805, 0.1767, 0.1729, 0.171 , 0.1672,
       0.1634, 0.1596, 0.1577, 0.1539, 0.152 , 0.1482, 0.1463, 0.1444,
       0.1406, 0.1387, 0.1368, 0.1349, 0.1311, 0.1292, 0.1273, 0.1254,
       0.1235, 0.1216, 0.1197, 0.1178, 0.1178, 0.1159, 0.114 , 0.1121,
       0.1102, 0.1102, 0.1083, 0.1064, 0.1045, 0.1045, 0.1026, 0.1007,
       0.1007, 0.0988, 0.0969, 0.0969, 0.095 , 0.095 , 0.0931, 0.0931,
       0.0912, 0.0893, 0.0893, 0.0874, 0.0874, 0.0855, 0.0855, 0.0855,
       0.0836, 0.0836])

In [28]:
fe.sum()

18.9981

In [29]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0358, -0.0348, -0.0302, -0.028 , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0203, -0.0212, -0.0142, -0.0193, -0.0165,
       -0.0177, -0.015 , -0.0164, -0.0158, -0.0152, -0.0127, -0.0122,
       -0.0118, -0.0134, -0.013 , -0.0126, -0.0102, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0078,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0045, -0.0064, -0.0043, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0029, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0025, -0.0045, -0.0044, -0.0044])

In [30]:
diferencia.sum()

-0.9619

In [31]:
f0_fe= (f0-fe)

In [32]:
f0_fe_2 = f0_fe*f0_fe

In [33]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.05789418,  0.11056981,  0.6612    ,  0.24632109,  0.32438596,
        0.532     ,  0.4997    ,  0.4712    ,  0.4465    ,  0.78386049,
        0.4028    , 17.83351339,  0.3667    ,  1.19645021,  0.3363    ,
        1.41897523,  0.3116    ,  0.3002    ,  0.2888    ,  1.85967952,
        1.97624922,  2.07608253,  0.2546    ,  0.247     ,  0.2394    ,
        2.54586385,  0.2261    ,  0.2204    ,  0.2147    ,  0.209     ,
        0.2033    ,  0.1995    ,  0.1938    ,  0.19      ,  3.55676928,
        0.1805    ,  0.1767    ,  0.1729    ,  0.171     ,  0.1672    ,
        0.1634    ,  0.1596    ,  0.1577    ,  0.1539    ,  0.152     ,
        0.1482    ,  0.1463    ,  0.1444    ,  0.1406    ,  0.1387    ,
        0.1368    ,  0.1349    ,  0.1311    ,  0.1292    ,  0.1273    ,
        0.1254    ,  6.22066599,  0.1216    ,  6.47391888,  0.1178    ,
        0.1178    ,  0.1159    ,  0.114     ,  0.1121    ,  0.1102    ,
        0.1102    ,  0.1083    ,  0.1064    ,  0.1045    ,  0.10

# Partido Nacional

In [34]:
x_2 = f0_fe_2_fe.sum()
x_2 

78.475244638659

In [35]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [36]:
f0 = np.array(f0)
f0

array([0, 1, 0, 1, 1, 0, 0, 2, 0, 2, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0])

In [37]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.002, 0.   , 0.002, 0.002, 0.   , 0.   , 0.004, 0.   ,
       0.004, 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [38]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [39]:
f0_tot=f0.sum()
f0_tot

19

In [40]:
fe = benford*f0_tot

In [41]:
fe 

array([0.7866, 0.7182, 0.6612, 0.6118, 0.57  , 0.532 , 0.4997, 0.4712,
       0.4465, 0.4237, 0.4028, 0.3838, 0.3667, 0.3515, 0.3363, 0.323 ,
       0.3116, 0.3002, 0.2888, 0.2793, 0.2698, 0.2622, 0.2546, 0.247 ,
       0.2394, 0.2318, 0.2261, 0.2204, 0.2147, 0.209 , 0.2033, 0.1995,
       0.1938, 0.19  , 0.1862, 0.1805, 0.1767, 0.1729, 0.171 , 0.1672,
       0.1634, 0.1596, 0.1577, 0.1539, 0.152 , 0.1482, 0.1463, 0.1444,
       0.1406, 0.1387, 0.1368, 0.1349, 0.1311, 0.1292, 0.1273, 0.1254,
       0.1235, 0.1216, 0.1197, 0.1178, 0.1178, 0.1159, 0.114 , 0.1121,
       0.1102, 0.1102, 0.1083, 0.1064, 0.1045, 0.1045, 0.1026, 0.1007,
       0.1007, 0.0988, 0.0969, 0.0969, 0.095 , 0.095 , 0.0931, 0.0931,
       0.0912, 0.0893, 0.0893, 0.0874, 0.0874, 0.0855, 0.0855, 0.0855,
       0.0836, 0.0836])

In [42]:
fe.sum()

18.9981

In [43]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0358, -0.0348, -0.0302, -0.028 , -0.028 , -0.0263,
       -0.0208, -0.0235, -0.0183, -0.0212, -0.0202, -0.0173, -0.0185,
       -0.0177, -0.017 , -0.0144, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0114, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.009 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0068, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0057, -0.0076, -0.0054,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0046,
       -0.0065, -0.0044, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0033, -0.0032, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0026,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [44]:
diferencia.sum()

-0.9618999999999999

In [45]:
f0_fe= (f0-fe)

In [46]:
f0_fe_2 = f0_fe*f0_fe

In [47]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.7866    , 0.11056981, 0.6612    , 0.24632109, 0.32438596,
       0.532     , 0.4997    , 4.96016435, 0.4465    , 5.86434196,
       0.4028    , 0.3838    , 1.09372482, 0.3515    , 0.3363    ,
       0.323     , 1.52084262, 0.3002    , 0.2888    , 0.2793    ,
       0.2698    , 0.2622    , 2.18232977, 0.247     , 0.2394    ,
       0.2318    , 0.2261    , 0.2204    , 0.2147    , 2.993689  ,
       0.2033    , 0.1995    , 0.1938    , 0.19      , 0.1862    ,
       0.1805    , 0.1767    , 0.1729    , 0.171     , 4.14806124,
       0.1634    , 0.1596    , 0.1577    , 0.1539    , 0.152     ,
       0.1482    , 4.98156999, 0.1444    , 5.25297553, 0.1387    ,
       0.1368    , 0.1349    , 0.1311    , 0.1292    , 0.1273    ,
       6.09988166, 0.1235    , 6.34528421, 0.1197    , 0.1178    ,
       0.1178    , 0.1159    , 0.114     , 0.1121    , 0.1102    ,
       0.1102    , 0.1083    , 0.1064    , 0.1045    , 0.1045    ,
       0.1026    , 0.1007    , 8.03118659, 8.22025749, 0.0969 

# Partido Libre

In [48]:
x_2 = f0_fe_2_fe.sum()
x_2 

85.97793369654096

In [49]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [50]:
f0 = np.array(f0)
f0

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [51]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.002, 0.004, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.002, 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [52]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [53]:
f0_tot=f0.sum()
f0_tot

19

In [54]:
fe = benford*f0_tot

In [55]:
fe 

array([0.7866, 0.7182, 0.6612, 0.6118, 0.57  , 0.532 , 0.4997, 0.4712,
       0.4465, 0.4237, 0.4028, 0.3838, 0.3667, 0.3515, 0.3363, 0.323 ,
       0.3116, 0.3002, 0.2888, 0.2793, 0.2698, 0.2622, 0.2546, 0.247 ,
       0.2394, 0.2318, 0.2261, 0.2204, 0.2147, 0.209 , 0.2033, 0.1995,
       0.1938, 0.19  , 0.1862, 0.1805, 0.1767, 0.1729, 0.171 , 0.1672,
       0.1634, 0.1596, 0.1577, 0.1539, 0.152 , 0.1482, 0.1463, 0.1444,
       0.1406, 0.1387, 0.1368, 0.1349, 0.1311, 0.1292, 0.1273, 0.1254,
       0.1235, 0.1216, 0.1197, 0.1178, 0.1178, 0.1159, 0.114 , 0.1121,
       0.1102, 0.1102, 0.1083, 0.1064, 0.1045, 0.1045, 0.1026, 0.1007,
       0.1007, 0.0988, 0.0969, 0.0969, 0.095 , 0.095 , 0.0931, 0.0931,
       0.0912, 0.0893, 0.0893, 0.0874, 0.0874, 0.0855, 0.0855, 0.0855,
       0.0836, 0.0836])

In [56]:
fe.sum()

18.9981

In [57]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0358, -0.0348, -0.0322, -0.03  , -0.028 , -0.0243,
       -0.0248, -0.0235, -0.0203, -0.0172, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.015 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0122,
       -0.0138, -0.0114, -0.013 , -0.0126, -0.0122, -0.0099, -0.0116,
       -0.0113, -0.009 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0075, -0.0073, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0061, -0.008 , -0.0058, -0.0077, -0.0076, -0.0074,
       -0.0053, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0044, -0.0043, -0.0062, -0.0042, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0038, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [58]:
diferencia.sum()

-0.9618999999999999

In [59]:
f0_fe= (f0-fe)

In [60]:
f0_fe_2 = f0_fe*f0_fe

In [61]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.7866    , 0.11056981, 0.6612    , 0.6118    , 0.57      ,
       0.532     , 0.50090072, 0.4712    , 0.4465    , 0.78386049,
       6.33328659, 0.3838    , 0.3667    , 0.3515    , 0.3363    ,
       1.41897523, 0.3116    , 0.3002    , 0.2888    , 0.2793    ,
       1.97624922, 0.2622    , 2.18232977, 0.247     , 0.2394    ,
       0.2318    , 2.64892176, 0.2204    , 0.2147    , 2.993689  ,
       0.2033    , 0.1995    , 0.1938    , 0.19      , 0.1862    ,
       3.7206662 , 3.83600956, 0.1729    , 0.171     , 0.1672    ,
       0.1634    , 0.1596    , 0.1577    , 4.6516258 , 0.152     ,
       4.89583833, 0.1463    , 0.1444    , 0.1406    , 5.34850534,
       0.1368    , 0.1349    , 0.1311    , 0.1292    , 0.1273    ,
       0.1254    , 0.1235    , 6.34528421, 6.47391888, 0.1178    ,
       6.60676435, 0.1159    , 0.114     , 0.1121    , 0.1102    ,
       7.18461016, 0.1083    , 0.1064    , 0.1045    , 0.1045    ,
       0.1026    , 0.1007    , 0.1007    , 0.0988    , 0.0969 

# Total

In [62]:
x_2 = f0_fe_2_fe.sum()
x_2 

82.41590542792753