In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1HeOZdGl5aMSIMShkHirP3s2xpCv3oxkx/export?format=csv")
df

PL   PN  LIBRE-PINU  TOTAL
0  18  108         246    379
1  25  171         229    430
2  74  304         311    694
3  22   75         179    280
4  31   90         184    332
5  23  129         173    330

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[18, 25, 74, 22, 31, 23]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[108, 171, 304, 75, 90, 129]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[246, 229, 311, 179, 184, 173]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[379, 430, 694, 280, 332, 330]

In [7]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [8]:
f0 = np.array(f0)
f0

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [9]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.002, 0.002, 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [10]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [11]:
f0_tot=f0.sum()
f0_tot

6

In [12]:
fe = benford*f0_tot

In [13]:
fe 

array([0.2484, 0.2268, 0.2088, 0.1932, 0.18  , 0.168 , 0.1578, 0.1488,
       0.141 , 0.1338, 0.1272, 0.1212, 0.1158, 0.111 , 0.1062, 0.102 ,
       0.0984, 0.0948, 0.0912, 0.0882, 0.0852, 0.0828, 0.0804, 0.078 ,
       0.0756, 0.0732, 0.0714, 0.0696, 0.0678, 0.066 , 0.0642, 0.063 ,
       0.0612, 0.06  , 0.0588, 0.057 , 0.0558, 0.0546, 0.054 , 0.0528,
       0.0516, 0.0504, 0.0498, 0.0486, 0.048 , 0.0468, 0.0462, 0.0456,
       0.0444, 0.0438, 0.0432, 0.0426, 0.0414, 0.0408, 0.0402, 0.0396,
       0.039 , 0.0384, 0.0378, 0.0372, 0.0372, 0.0366, 0.036 , 0.0354,
       0.0348, 0.0348, 0.0342, 0.0336, 0.033 , 0.033 , 0.0324, 0.0318,
       0.0318, 0.0312, 0.0306, 0.0306, 0.03  , 0.03  , 0.0294, 0.0294,
       0.0288, 0.0282, 0.0282, 0.0276, 0.0276, 0.027 , 0.027 , 0.027 ,
       0.0264, 0.0264])

In [14]:
fe.sum()

5.9994

In [15]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0378, -0.0348, -0.0322, -0.03  , -0.028 , -0.0263,
       -0.0248, -0.0215, -0.0223, -0.0212, -0.0202, -0.0173, -0.0165,
       -0.0177, -0.015 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0118, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0038, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [16]:
diferencia.sum()

-0.9879

In [17]:
f0_fe= (f0-fe)

In [18]:
f0_fe_2 = f0_fe*f0_fe

In [19]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.48400000e-01, 2.26800000e-01, 2.08800000e-01, 1.93200000e-01,
       1.80000000e-01, 1.68000000e-01, 1.57800000e-01, 1.48800000e-01,
       5.23319858e+00, 1.33800000e-01, 1.27200000e-01, 1.21200000e-01,
       6.75137858e+00, 7.12000901e+00, 1.06200000e-01, 7.90592157e+00,
       9.84000000e-02, 9.48000000e-02, 9.12000000e-02, 8.82000000e-02,
       8.52000000e-02, 1.01600947e+01, 8.04000000e-02, 7.80000000e-02,
       7.56000000e-02, 7.32000000e-02, 7.14000000e-02, 6.96000000e-02,
       6.78000000e-02, 6.60000000e-02, 6.42000000e-02, 6.30000000e-02,
       6.12000000e-02, 6.00000000e-02, 5.88000000e-02, 5.70000000e-02,
       5.58000000e-02, 5.46000000e-02, 5.40000000e-02, 5.28000000e-02,
       5.16000000e-02, 5.04000000e-02, 4.98000000e-02, 4.86000000e-02,
       4.80000000e-02, 4.68000000e-02, 4.62000000e-02, 4.56000000e-02,
       4.44000000e-02, 4.38000000e-02, 4.32000000e-02, 4.26000000e-02,
       4.14000000e-02, 4.08000000e-02, 4.02000000e-02, 3.96000000e-02,
      

# Partido Liberal

In [20]:
x_2 = f0_fe_2_fe.sum()
x_2 

69.35303461286023

In [21]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [22]:
f0 = np.array(f0)
f0

array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [23]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [24]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [25]:
f0_tot=f0.sum()
f0_tot

6

In [26]:
fe = benford*f0_tot

In [27]:
fe 

array([0.2484, 0.2268, 0.2088, 0.1932, 0.18  , 0.168 , 0.1578, 0.1488,
       0.141 , 0.1338, 0.1272, 0.1212, 0.1158, 0.111 , 0.1062, 0.102 ,
       0.0984, 0.0948, 0.0912, 0.0882, 0.0852, 0.0828, 0.0804, 0.078 ,
       0.0756, 0.0732, 0.0714, 0.0696, 0.0678, 0.066 , 0.0642, 0.063 ,
       0.0612, 0.06  , 0.0588, 0.057 , 0.0558, 0.0546, 0.054 , 0.0528,
       0.0516, 0.0504, 0.0498, 0.0486, 0.048 , 0.0468, 0.0462, 0.0456,
       0.0444, 0.0438, 0.0432, 0.0426, 0.0414, 0.0408, 0.0402, 0.0396,
       0.039 , 0.0384, 0.0378, 0.0372, 0.0372, 0.0366, 0.036 , 0.0354,
       0.0348, 0.0348, 0.0342, 0.0336, 0.033 , 0.033 , 0.0324, 0.0318,
       0.0318, 0.0312, 0.0306, 0.0306, 0.03  , 0.03  , 0.0294, 0.0294,
       0.0288, 0.0282, 0.0282, 0.0276, 0.0276, 0.027 , 0.027 , 0.027 ,
       0.0264, 0.0264])

In [28]:
fe.sum()

5.9994

In [29]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0378, -0.0328, -0.0322, -0.03  , -0.028 , -0.0263,
       -0.0228, -0.0235, -0.0223, -0.0212, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0122,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0038, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0028, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [30]:
diferencia.sum()

-0.9879

In [31]:
f0_fe= (f0-fe)

In [32]:
f0_fe_2 = f0_fe*f0_fe

In [33]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.27416490e+00, 2.26800000e-01, 2.99807203e+00, 1.93200000e-01,
       1.80000000e-01, 1.68000000e-01, 1.57800000e-01, 4.86923011e+00,
       1.41000000e-01, 1.33800000e-01, 1.27200000e-01, 1.21200000e-01,
       1.15800000e-01, 1.11000000e-01, 1.06200000e-01, 1.02000000e-01,
       9.84000000e-02, 9.48000000e-02, 9.12000000e-02, 8.82000000e-02,
       9.82228920e+00, 8.28000000e-02, 8.04000000e-02, 7.80000000e-02,
       7.56000000e-02, 7.32000000e-02, 7.14000000e-02, 6.96000000e-02,
       6.78000000e-02, 6.60000000e-02, 6.42000000e-02, 6.30000000e-02,
       6.12000000e-02, 6.00000000e-02, 5.88000000e-02, 5.70000000e-02,
       5.58000000e-02, 5.46000000e-02, 5.40000000e-02, 5.28000000e-02,
       5.16000000e-02, 5.04000000e-02, 4.98000000e-02, 4.86000000e-02,
       4.80000000e-02, 4.68000000e-02, 4.62000000e-02, 4.56000000e-02,
       4.44000000e-02, 4.38000000e-02, 4.32000000e-02, 4.26000000e-02,
       4.14000000e-02, 4.08000000e-02, 4.02000000e-02, 3.96000000e-02,
      

# Partido Nacional

In [34]:
x_2 = f0_fe_2_fe.sum()
x_2 

84.72981064151652

In [35]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [36]:
f0 = np.array(f0)
f0

array([0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [37]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.004, 0.002,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [38]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [39]:
f0_tot=f0.sum()
f0_tot

6

In [40]:
fe = benford*f0_tot

In [41]:
fe 

array([0.2484, 0.2268, 0.2088, 0.1932, 0.18  , 0.168 , 0.1578, 0.1488,
       0.141 , 0.1338, 0.1272, 0.1212, 0.1158, 0.111 , 0.1062, 0.102 ,
       0.0984, 0.0948, 0.0912, 0.0882, 0.0852, 0.0828, 0.0804, 0.078 ,
       0.0756, 0.0732, 0.0714, 0.0696, 0.0678, 0.066 , 0.0642, 0.063 ,
       0.0612, 0.06  , 0.0588, 0.057 , 0.0558, 0.0546, 0.054 , 0.0528,
       0.0516, 0.0504, 0.0498, 0.0486, 0.048 , 0.0468, 0.0462, 0.0456,
       0.0444, 0.0438, 0.0432, 0.0426, 0.0414, 0.0408, 0.0402, 0.0396,
       0.039 , 0.0384, 0.0378, 0.0372, 0.0372, 0.0366, 0.036 , 0.0354,
       0.0348, 0.0348, 0.0342, 0.0336, 0.033 , 0.033 , 0.0324, 0.0318,
       0.0318, 0.0312, 0.0306, 0.0306, 0.03  , 0.03  , 0.0294, 0.0294,
       0.0288, 0.0282, 0.0282, 0.0276, 0.0276, 0.027 , 0.027 , 0.027 ,
       0.0264, 0.0264])

In [42]:
fe.sum()

5.9994

In [43]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0378, -0.0348, -0.0322, -0.03  , -0.028 , -0.0263,
       -0.0208, -0.0215, -0.0223, -0.0212, -0.0202, -0.0173, -0.0185,
       -0.0157, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0118, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [44]:
diferencia.sum()

-0.9879

In [45]:
f0_fe= (f0-fe)

In [46]:
f0_fe_2 = f0_fe*f0_fe

In [47]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.2484    ,  0.2268    ,  0.2088    ,  0.1932    ,  0.18      ,
        0.168     ,  0.1578    , 23.03052043,  5.23319858,  0.1338    ,
        0.1272    ,  0.1212    ,  6.75137858,  0.111     ,  7.52239586,
        0.102     ,  0.0984    ,  0.0948    ,  0.0912    ,  0.0882    ,
        0.0852    , 10.16009469,  0.0804    ,  0.078     ,  0.0756    ,
        0.0732    ,  0.0714    ,  0.0696    ,  0.0678    ,  0.066     ,
        0.0642    ,  0.063     ,  0.0612    ,  0.06      ,  0.0588    ,
        0.057     ,  0.0558    ,  0.0546    ,  0.054     ,  0.0528    ,
        0.0516    ,  0.0504    ,  0.0498    ,  0.0486    ,  0.048     ,
        0.0468    ,  0.0462    ,  0.0456    ,  0.0444    ,  0.0438    ,
        0.0432    ,  0.0426    ,  0.0414    ,  0.0408    ,  0.0402    ,
        0.0396    ,  0.039     ,  0.0384    ,  0.0378    ,  0.0372    ,
        0.0372    ,  0.0366    ,  0.036     ,  0.0354    ,  0.0348    ,
        0.0348    ,  0.0342    ,  0.0336    ,  0.033     ,  0.03

# Partido Libre

In [48]:
x_2 = f0_fe_2_fe.sum()
x_2 

58.10238813829708

In [49]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [50]:
f0 = np.array(f0)
f0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [51]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.004, 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [52]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [53]:
f0_tot=f0.sum()
f0_tot

6

In [54]:
fe = benford*f0_tot

In [55]:
fe 

array([0.2484, 0.2268, 0.2088, 0.1932, 0.18  , 0.168 , 0.1578, 0.1488,
       0.141 , 0.1338, 0.1272, 0.1212, 0.1158, 0.111 , 0.1062, 0.102 ,
       0.0984, 0.0948, 0.0912, 0.0882, 0.0852, 0.0828, 0.0804, 0.078 ,
       0.0756, 0.0732, 0.0714, 0.0696, 0.0678, 0.066 , 0.0642, 0.063 ,
       0.0612, 0.06  , 0.0588, 0.057 , 0.0558, 0.0546, 0.054 , 0.0528,
       0.0516, 0.0504, 0.0498, 0.0486, 0.048 , 0.0468, 0.0462, 0.0456,
       0.0444, 0.0438, 0.0432, 0.0426, 0.0414, 0.0408, 0.0402, 0.0396,
       0.039 , 0.0384, 0.0378, 0.0372, 0.0372, 0.0366, 0.036 , 0.0354,
       0.0348, 0.0348, 0.0342, 0.0336, 0.033 , 0.033 , 0.0324, 0.0318,
       0.0318, 0.0312, 0.0306, 0.0306, 0.03  , 0.03  , 0.0294, 0.0294,
       0.0288, 0.0282, 0.0282, 0.0276, 0.0276, 0.027 , 0.027 , 0.027 ,
       0.0264, 0.0264])

In [56]:
fe.sum()

5.9994

In [57]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0378, -0.0348, -0.0322, -0.03  , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0132, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.009 , -0.0126, -0.0122, -0.0119, -0.0096,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.008 , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0042, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [58]:
diferencia.sum()

-0.9878999999999999

In [59]:
f0_fe= (f0-fe)

In [60]:
f0_fe_2 = f0_fe*f0_fe

In [61]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.48400000e-01, 2.26800000e-01, 2.08800000e-01, 1.93200000e-01,
       1.80000000e-01, 1.68000000e-01, 1.57800000e-01, 1.48800000e-01,
       1.41000000e-01, 1.33800000e-01, 1.27200000e-01, 1.21200000e-01,
       1.15800000e-01, 1.11000000e-01, 1.06200000e-01, 1.02000000e-01,
       9.84000000e-02, 9.48000000e-02, 9.05611228e+00, 8.82000000e-02,
       8.52000000e-02, 8.28000000e-02, 8.04000000e-02, 4.73600513e+01,
       7.56000000e-02, 7.32000000e-02, 7.14000000e-02, 1.24374161e+01,
       6.78000000e-02, 6.60000000e-02, 6.42000000e-02, 6.30000000e-02,
       6.12000000e-02, 1.47266667e+01, 5.88000000e-02, 5.70000000e-02,
       5.58000000e-02, 5.46000000e-02, 5.40000000e-02, 5.28000000e-02,
       5.16000000e-02, 5.04000000e-02, 4.98000000e-02, 4.86000000e-02,
       4.80000000e-02, 4.68000000e-02, 4.62000000e-02, 4.56000000e-02,
       4.44000000e-02, 4.38000000e-02, 4.32000000e-02, 4.26000000e-02,
       4.14000000e-02, 4.08000000e-02, 4.02000000e-02, 3.96000000e-02,
      

# Total

In [62]:
x_2 = f0_fe_2_fe.sum()
x_2 

114.16256675148125