In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1qBodT6OuwCASM5HnehlvoQcll7Mb-Cpd/export?format=csv")
df

PL      PN  LIBRE-PINU   TOTAL
0   64996  200482      185099  456964
1     949    1605         305    2875
2    2722    4520        3187   10512
3    3425    4234         700    8411
4     409    3870        3773    8099
5    2287    5737        5562   13684
6     387    1050        1021    2481
7     703    1792         744    3266
8    2944    4201         751    7978
9     870    1960         971    3843
10    312    1763        1469    3609
11    615     993        1202    2908
12   1953    3092        1397    6486
13    324    3090        3285    6745
14   2248    2553         699    5517
15   2106    4067        2788    9012
16   1475    3079        1791    6419
17   1509     882         355    2766
18   1319    2343        1762    5448
19   2544    3737        1381    7702
20    565     828         413    1818
21   2581    2237        2546    7514
22   1433    2873        1477    5869
23   2387    6477        5844   14863
24    988    2427         768    4209
25   1559    4885        2349    8875
26   1369    2140        2331    5891
27   1079    1707         974    3814

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[64996,
 949,
 2722,
 3425,
 409,
 2287,
 387,
 703,
 2944,
 870,
 312,
 615,
 1953,
 324,
 2248,
 2106,
 1475,
 1509,
 1319,
 2544,
 565,
 2581,
 1433,
 2387,
 988,
 1559,
 1369,
 1079]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[200482,
 1605,
 4520,
 4234,
 3870,
 5737,
 1050,
 1792,
 4201,
 1960,
 1763,
 993,
 3092,
 3090,
 2553,
 4067,
 3079,
 882,
 2343,
 3737,
 828,
 2237,
 2873,
 6477,
 2427,
 4885,
 2140,
 1707]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[185099,
 305,
 3187,
 700,
 3773,
 5562,
 1021,
 744,
 751,
 971,
 1469,
 1202,
 1397,
 3285,
 699,
 2788,
 1791,
 355,
 1762,
 1381,
 413,
 2546,
 1477,
 5844,
 768,
 2349,
 2331,
 974]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[456964,
 2875,
 10512,
 8411,
 8099,
 13684,
 2481,
 3266,
 7978,
 3843,
 3609,
 2908,
 6486,
 6745,
 5517,
 9012,
 6419,
 2766,
 5448,
 7702,
 1818,
 7514,
 5869,
 14863,
 4209,
 8875,
 5891,
 3814]

In [7]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [8]:
f0 = np.array(f0)
f0

array([1, 0, 0, 2, 2, 2, 0, 0, 0, 1, 0, 1, 2, 1, 0, 2, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0])

In [9]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.   , 0.   , 0.004, 0.004, 0.004, 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.002, 0.004, 0.002, 0.   , 0.004, 0.   , 0.002,
       0.   , 0.002, 0.   , 0.002, 0.002, 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.002, 0.   ])

In [10]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [11]:
f0_tot=f0.sum()
f0_tot

28

In [12]:
fe = benford*f0_tot

In [13]:
fe 

array([1.1592, 1.0584, 0.9744, 0.9016, 0.84  , 0.784 , 0.7364, 0.6944,
       0.658 , 0.6244, 0.5936, 0.5656, 0.5404, 0.518 , 0.4956, 0.476 ,
       0.4592, 0.4424, 0.4256, 0.4116, 0.3976, 0.3864, 0.3752, 0.364 ,
       0.3528, 0.3416, 0.3332, 0.3248, 0.3164, 0.308 , 0.2996, 0.294 ,
       0.2856, 0.28  , 0.2744, 0.266 , 0.2604, 0.2548, 0.252 , 0.2464,
       0.2408, 0.2352, 0.2324, 0.2268, 0.224 , 0.2184, 0.2156, 0.2128,
       0.2072, 0.2044, 0.2016, 0.1988, 0.1932, 0.1904, 0.1876, 0.1848,
       0.182 , 0.1792, 0.1764, 0.1736, 0.1736, 0.1708, 0.168 , 0.1652,
       0.1624, 0.1624, 0.1596, 0.1568, 0.154 , 0.154 , 0.1512, 0.1484,
       0.1484, 0.1456, 0.1428, 0.1428, 0.14  , 0.14  , 0.1372, 0.1372,
       0.1344, 0.1316, 0.1316, 0.1288, 0.1288, 0.126 , 0.126 , 0.126 ,
       0.1232, 0.1232])

In [14]:
fe.sum()

27.9972

In [15]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0378, -0.0348, -0.0282, -0.026 , -0.024 , -0.0263,
       -0.0248, -0.0235, -0.0203, -0.0212, -0.0182, -0.0153, -0.0165,
       -0.0177, -0.013 , -0.0164, -0.0138, -0.0152, -0.0127, -0.0142,
       -0.0118, -0.0114, -0.013 , -0.0106, -0.0122, -0.0119, -0.0116,
       -0.0093, -0.011 , -0.0087, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0057, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0051, -0.0069, -0.0068, -0.0047, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0042, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.003 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0026, -0.0045, -0.0045, -0.0045, -0.0024, -0.0044])

In [16]:
diferencia.sum()

-0.9439

In [17]:
f0_fe= (f0-fe)

In [18]:
f0_fe_2 = f0_fe*f0_fe

In [19]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.02186391, 1.0584    , 0.9744    , 1.33815723, 1.60190476,
       1.88604082, 0.7364    , 0.6944    , 0.658     , 0.22593748,
       0.5936    , 0.33363395, 3.9423245 , 0.44850193, 0.4956    ,
       4.87936134, 0.4592    , 0.70279783, 0.4256    , 0.84114325,
       0.3976    , 0.97439172, 1.0404452 , 0.364     , 1.18726712,
       0.3416    , 0.3332    , 0.3248    , 1.47695626, 0.308     ,
       1.63738371, 0.294     , 0.2856    , 0.28      , 0.2744    ,
       0.266     , 0.2604    , 0.2548    , 0.252     , 0.2464    ,
       0.2408    , 0.2352    , 0.2324    , 0.2268    , 0.224     ,
       0.2184    , 2.85381892, 0.2128    , 0.2072    , 0.2044    ,
       0.2016    , 3.22898109, 0.1932    , 0.1904    , 3.51809041,
       0.1848    , 0.182     , 0.1792    , 0.1764    , 0.1736    ,
       3.93396866, 0.1708    , 0.168     , 0.1652    , 0.1624    ,
       0.1624    , 0.1596    , 0.1568    , 0.154     , 0.154     ,
       0.1512    , 0.1484    , 0.1484    , 0.1456    , 0.1428 

# Partido Liberal

In [20]:
x_2 = f0_fe_2_fe.sum()
x_2 

71.32468549435539

In [21]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [22]:
f0 = np.array(f0)
f0

array([1, 0, 0, 0, 0, 0, 1, 3, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 3, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 2, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1])

In [23]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.006, 0.   ,
       0.002, 0.002, 0.002, 0.002, 0.002, 0.002, 0.002, 0.   , 0.   ,
       0.002, 0.   , 0.006, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.002, 0.   , 0.002, 0.   , 0.004, 0.   , 0.   , 0.002,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002])

In [24]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [25]:
f0_tot=f0.sum()
f0_tot

28

In [26]:
fe = benford*f0_tot

In [27]:
fe 

array([1.1592, 1.0584, 0.9744, 0.9016, 0.84  , 0.784 , 0.7364, 0.6944,
       0.658 , 0.6244, 0.5936, 0.5656, 0.5404, 0.518 , 0.4956, 0.476 ,
       0.4592, 0.4424, 0.4256, 0.4116, 0.3976, 0.3864, 0.3752, 0.364 ,
       0.3528, 0.3416, 0.3332, 0.3248, 0.3164, 0.308 , 0.2996, 0.294 ,
       0.2856, 0.28  , 0.2744, 0.266 , 0.2604, 0.2548, 0.252 , 0.2464,
       0.2408, 0.2352, 0.2324, 0.2268, 0.224 , 0.2184, 0.2156, 0.2128,
       0.2072, 0.2044, 0.2016, 0.1988, 0.1932, 0.1904, 0.1876, 0.1848,
       0.182 , 0.1792, 0.1764, 0.1736, 0.1736, 0.1708, 0.168 , 0.1652,
       0.1624, 0.1624, 0.1596, 0.1568, 0.154 , 0.154 , 0.1512, 0.1484,
       0.1484, 0.1456, 0.1428, 0.1428, 0.14  , 0.14  , 0.1372, 0.1372,
       0.1344, 0.1316, 0.1316, 0.1288, 0.1288, 0.126 , 0.126 , 0.126 ,
       0.1232, 0.1232])

In [28]:
fe.sum()

27.9972

In [29]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0378, -0.0348, -0.0322, -0.03  , -0.028 , -0.0243,
       -0.0188, -0.0235, -0.0203, -0.0192, -0.0182, -0.0173, -0.0165,
       -0.0157, -0.015 , -0.0164, -0.0158, -0.0132, -0.0147, -0.0082,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0096,
       -0.0093, -0.011 , -0.0087, -0.0105, -0.0062, -0.01  , -0.0098,
       -0.0075, -0.0093, -0.0091, -0.007 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0056, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0047, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0033, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0029, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0024])

In [30]:
diferencia.sum()

-0.9439

In [31]:
f0_fe= (f0-fe)

In [32]:
f0_fe_2 = f0_fe*f0_fe

In [33]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.02186391,  1.0584    ,  0.9744    ,  0.9016    ,  0.84      ,
        0.784     ,  0.09435763,  7.65522949,  0.658     ,  0.22593748,
        0.27823612,  0.33363395,  0.39088113,  0.44850193,  0.51335626,
        0.57684034,  0.4592    ,  0.4424    ,  0.77522406,  0.4116    ,
       17.03341489,  0.3864    ,  0.3752    ,  0.364     ,  0.3528    ,
        0.3416    ,  0.3332    ,  1.40361773,  1.47695626,  0.308     ,
        1.63738371,  0.294     , 10.29120224,  0.28      ,  0.2744    ,
        2.0253985 ,  0.2604    ,  0.2548    ,  2.22025397,  0.2464    ,
        0.2408    ,  0.2352    ,  0.2324    ,  0.2268    ,  0.224     ,
        0.2184    ,  0.2156    ,  2.91204812,  0.2072    ,  0.2044    ,
        0.2016    ,  0.1988    ,  0.1932    ,  0.1904    ,  3.51809041,
        0.1848    ,  0.182     ,  0.1792    ,  0.1764    ,  0.1736    ,
        0.1736    ,  0.1708    ,  0.168     ,  0.1652    ,  0.1624    ,
        0.1624    ,  0.1596    ,  0.1568    ,  0.154     ,  0.15

# Partido Nacional

In [34]:
x_2 = f0_fe_2_fe.sum()
x_2 

88.60208543124034

In [35]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [36]:
f0 = np.array(f0)
f0

array([1, 0, 1, 2, 2, 0, 0, 2, 1, 0, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       0, 0])

In [37]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.   , 0.002, 0.004, 0.004, 0.   , 0.   , 0.004, 0.002,
       0.   , 0.   , 0.   , 0.   , 0.004, 0.   , 0.002, 0.   , 0.002,
       0.   , 0.   , 0.002, 0.002, 0.002, 0.   , 0.   , 0.002, 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.002, 0.   , 0.   ,
       0.   , 0.002, 0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.004, 0.   , 0.   ])

In [38]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [39]:
f0_tot=f0.sum()
f0_tot

28

In [40]:
fe = benford*f0_tot

In [41]:
fe 

array([1.1592, 1.0584, 0.9744, 0.9016, 0.84  , 0.784 , 0.7364, 0.6944,
       0.658 , 0.6244, 0.5936, 0.5656, 0.5404, 0.518 , 0.4956, 0.476 ,
       0.4592, 0.4424, 0.4256, 0.4116, 0.3976, 0.3864, 0.3752, 0.364 ,
       0.3528, 0.3416, 0.3332, 0.3248, 0.3164, 0.308 , 0.2996, 0.294 ,
       0.2856, 0.28  , 0.2744, 0.266 , 0.2604, 0.2548, 0.252 , 0.2464,
       0.2408, 0.2352, 0.2324, 0.2268, 0.224 , 0.2184, 0.2156, 0.2128,
       0.2072, 0.2044, 0.2016, 0.1988, 0.1932, 0.1904, 0.1876, 0.1848,
       0.182 , 0.1792, 0.1764, 0.1736, 0.1736, 0.1708, 0.168 , 0.1652,
       0.1624, 0.1624, 0.1596, 0.1568, 0.154 , 0.154 , 0.1512, 0.1484,
       0.1484, 0.1456, 0.1428, 0.1428, 0.14  , 0.14  , 0.1372, 0.1372,
       0.1344, 0.1316, 0.1316, 0.1288, 0.1288, 0.126 , 0.126 , 0.126 ,
       0.1232, 0.1232])

In [42]:
fe.sum()

27.9972

In [43]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0378, -0.0328, -0.0282, -0.026 , -0.028 , -0.0263,
       -0.0208, -0.0215, -0.0223, -0.0212, -0.0202, -0.0193, -0.0145,
       -0.0177, -0.015 , -0.0164, -0.0138, -0.0152, -0.0147, -0.0122,
       -0.0118, -0.0114, -0.013 , -0.0126, -0.0102, -0.0119, -0.0096,
       -0.0113, -0.011 , -0.0107, -0.0085, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0058, -0.0077, -0.0076, -0.0054,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0042, -0.0042, -0.0061, -0.006 ,
       -0.0059, -0.0038, -0.0038, -0.0037, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0005, -0.0044, -0.0044])

In [44]:
diferencia.sum()

-0.9439

In [45]:
f0_fe= (f0-fe)

In [46]:
f0_fe_2 = f0_fe*f0_fe

In [47]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.18639061e-02, 1.05840000e+00, 6.72577997e-04, 1.33815723e+00,
       1.60190476e+00, 7.84000000e-01, 7.36400000e-01, 2.45476866e+00,
       1.77756839e-01, 6.24400000e-01, 5.93600000e-01, 5.65600000e-01,
       5.40400000e-01, 4.24000772e+00, 4.95600000e-01, 5.76840336e-01,
       4.59200000e-01, 7.02797830e-01, 4.25600000e-01, 4.11600000e-01,
       9.12690543e-01, 9.74391718e-01, 1.04044520e+00, 3.64000000e-01,
       3.52800000e-01, 1.26900047e+00, 3.33200000e-01, 1.40361773e+00,
       3.16400000e-01, 3.08000000e-01, 2.99600000e-01, 1.69536054e+00,
       2.85600000e-01, 2.80000000e-01, 2.74400000e-01, 2.66000000e-01,
       2.60400000e-01, 2.54800000e-01, 2.52000000e-01, 2.46400000e-01,
       2.40800000e-01, 2.35200000e-01, 2.32400000e-01, 2.26800000e-01,
       2.24000000e-01, 2.79715458e+00, 2.15600000e-01, 2.12800000e-01,
       3.03345483e+00, 2.04400000e-01, 2.01600000e-01, 1.98800000e-01,
       1.93200000e-01, 1.90400000e-01, 1.87600000e-01, 1.84800000e-01,
      

# Partido Libre

In [48]:
x_2 = f0_fe_2_fe.sum()
x_2 

90.87658965372071

In [49]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [50]:
f0 = np.array(f0)
f0

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [51]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.   , 0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.002,
       0.002, 0.002, 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.002,
       0.   , 0.004, 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.002, 0.   , 0.   , 0.004, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.004, 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.002, 0.   , 0.002, 0.002, 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.002, 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [52]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [53]:
f0_tot=f0.sum()
f0_tot

28

In [54]:
fe = benford*f0_tot

In [55]:
fe 

array([1.1592, 1.0584, 0.9744, 0.9016, 0.84  , 0.784 , 0.7364, 0.6944,
       0.658 , 0.6244, 0.5936, 0.5656, 0.5404, 0.518 , 0.4956, 0.476 ,
       0.4592, 0.4424, 0.4256, 0.4116, 0.3976, 0.3864, 0.3752, 0.364 ,
       0.3528, 0.3416, 0.3332, 0.3248, 0.3164, 0.308 , 0.2996, 0.294 ,
       0.2856, 0.28  , 0.2744, 0.266 , 0.2604, 0.2548, 0.252 , 0.2464,
       0.2408, 0.2352, 0.2324, 0.2268, 0.224 , 0.2184, 0.2156, 0.2128,
       0.2072, 0.2044, 0.2016, 0.1988, 0.1932, 0.1904, 0.1876, 0.1848,
       0.182 , 0.1792, 0.1764, 0.1736, 0.1736, 0.1708, 0.168 , 0.1652,
       0.1624, 0.1624, 0.1596, 0.1568, 0.154 , 0.154 , 0.1512, 0.1484,
       0.1484, 0.1456, 0.1428, 0.1428, 0.14  , 0.14  , 0.1372, 0.1372,
       0.1344, 0.1316, 0.1316, 0.1288, 0.1288, 0.126 , 0.126 , 0.126 ,
       0.1232, 0.1232])

In [56]:
fe.sum()

27.9972

In [57]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0378, -0.0348, -0.0302, -0.028 , -0.028 , -0.0263,
       -0.0248, -0.0215, -0.0223, -0.0212, -0.0202, -0.0193, -0.0185,
       -0.0157, -0.017 , -0.0164, -0.0138, -0.0132, -0.0127, -0.0142,
       -0.0138, -0.0114, -0.013 , -0.0126, -0.0122, -0.0099, -0.0116,
       -0.0073, -0.011 , -0.0107, -0.0105, -0.0082, -0.01  , -0.0098,
       -0.0075, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.006 , -0.0058, -0.0077, -0.0076, -0.0034,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0027, -0.0066,
       -0.0065, -0.0044, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0038, -0.0057, -0.0036, -0.0055, -0.0035,
       -0.0034, -0.0053, -0.0053, -0.0052, -0.0031, -0.0051, -0.005 ,
       -0.005 , -0.0029, -0.0049, -0.0028, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [58]:
diferencia.sum()

-0.9439

In [59]:
f0_fe= (f0-fe)

In [60]:
f0_fe_2 = f0_fe*f0_fe

In [61]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.18639061e-02, 1.05840000e+00, 9.74400000e-01, 1.07393079e-02,
       3.04761905e-02, 7.84000000e-01, 7.36400000e-01, 6.94400000e-01,
       1.77756839e-01, 6.24400000e-01, 5.93600000e-01, 5.65600000e-01,
       5.40400000e-01, 5.18000000e-01, 5.13356255e-01, 4.76000000e-01,
       4.59200000e-01, 7.02797830e-01, 7.75224060e-01, 8.41143246e-01,
       3.97600000e-01, 3.86400000e-01, 1.04044520e+00, 3.64000000e-01,
       3.52800000e-01, 3.41600000e-01, 1.33440048e+00, 3.24800000e-01,
       8.95862503e+00, 3.08000000e-01, 2.99600000e-01, 2.94000000e-01,
       1.78700056e+00, 2.80000000e-01, 2.74400000e-01, 2.02539850e+00,
       2.60400000e-01, 2.54800000e-01, 2.52000000e-01, 2.46400000e-01,
       2.40800000e-01, 2.35200000e-01, 2.32400000e-01, 2.26800000e-01,
       2.68828571e+00, 2.79715458e+00, 2.15600000e-01, 2.12800000e-01,
       1.55122193e+01, 2.04400000e-01, 2.01600000e-01, 1.98800000e-01,
       1.93200000e-01, 1.90400000e-01, 1.75095616e+01, 1.84800000e-01,
      

# Total

In [62]:
x_2 = f0_fe_2_fe.sum()
x_2 

113.93076241089588