In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1A_nJLWUA9iVtUslZhHGcYjYjfVBz6C6o/export?format=csv")
df

PL     PN  LIBRE-PINU  TOTAL
0   1260   3218        1932   6452
1    137   2042        1520   3724
2    250   3368        3460   7135
3    310   2526        1783   4660
4    792   1448         314   2582
5   5032  11280        4614  21187
6   1425   6484        3977  11959
7    106   1301         660   2089
8   1069   4013        1242   6417
9     59   1568        1715   3346
10   244   1238         535   2035
11  2047   3396        1627   7121
12   476   2000        1014   3551
13  1373   1876         344   3623
14    77   1509         783   2382
15  1949   5195        1412   8653
16   705   1894        1640   4315

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[1260,
 137,
 250,
 310,
 792,
 5032,
 1425,
 106,
 1069,
 59,
 244,
 2047,
 476,
 1373,
 77,
 1949,
 705]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[3218,
 2042,
 3368,
 2526,
 1448,
 11280,
 6484,
 1301,
 4013,
 1568,
 1238,
 3396,
 2000,
 1876,
 1509,
 5195,
 1894]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[1932,
 1520,
 3460,
 1783,
 314,
 4614,
 3977,
 660,
 1242,
 1715,
 535,
 1627,
 1014,
 344,
 783,
 1412,
 1640]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[6452,
 3724,
 7135,
 4660,
 2582,
 21187,
 11959,
 2089,
 6417,
 3346,
 2035,
 7121,
 3551,
 3623,
 2382,
 8653,
 4315]

In [7]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [8]:
f0 = np.array(f0)
f0

array([2, 0, 1, 2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [9]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.004, 0.   , 0.002, 0.004, 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.002, 0.   , 0.   , 0.   , 0.002, 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [10]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [11]:
f0_tot=f0.sum()
f0_tot

17

In [12]:
fe = benford*f0_tot

In [13]:
fe 

array([0.7038, 0.6426, 0.5916, 0.5474, 0.51  , 0.476 , 0.4471, 0.4216,
       0.3995, 0.3791, 0.3604, 0.3434, 0.3281, 0.3145, 0.3009, 0.289 ,
       0.2788, 0.2686, 0.2584, 0.2499, 0.2414, 0.2346, 0.2278, 0.221 ,
       0.2142, 0.2074, 0.2023, 0.1972, 0.1921, 0.187 , 0.1819, 0.1785,
       0.1734, 0.17  , 0.1666, 0.1615, 0.1581, 0.1547, 0.153 , 0.1496,
       0.1462, 0.1428, 0.1411, 0.1377, 0.136 , 0.1326, 0.1309, 0.1292,
       0.1258, 0.1241, 0.1224, 0.1207, 0.1173, 0.1156, 0.1139, 0.1122,
       0.1105, 0.1088, 0.1071, 0.1054, 0.1054, 0.1037, 0.102 , 0.1003,
       0.0986, 0.0986, 0.0969, 0.0952, 0.0935, 0.0935, 0.0918, 0.0901,
       0.0901, 0.0884, 0.0867, 0.0867, 0.085 , 0.085 , 0.0833, 0.0833,
       0.0816, 0.0799, 0.0799, 0.0782, 0.0782, 0.0765, 0.0765, 0.0765,
       0.0748, 0.0748])

In [14]:
fe.sum()

16.998299999999997

In [15]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0374, -0.0378, -0.0328, -0.0282, -0.028 , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0203, -0.0192, -0.0202, -0.0193, -0.0185,
       -0.0157, -0.015 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0118, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0071, -0.009 , -0.0088, -0.0066, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0053, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0042, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0036, -0.0055, -0.0035,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [16]:
diferencia.sum()

-0.9659

In [17]:
f0_fe= (f0-fe)

In [18]:
f0_fe_2 = f0_fe*f0_fe

In [19]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.38723279, 0.6426    , 0.2819313 , 3.85467073, 0.47078431,
       0.476     , 0.4471    , 0.4216    , 0.3995    , 1.01692643,
       1.13509478, 0.3434    , 0.3281    , 0.3145    , 1.62426324,
       1.74920761, 0.2788    , 0.2686    , 0.2584    , 0.2499    ,
       0.2414    , 2.4971746 , 0.2278    , 0.221     , 0.2142    ,
       0.2074    , 0.2023    , 0.1972    , 0.1921    , 0.187     ,
       0.1819    , 0.1785    , 0.1734    , 0.17      , 0.1666    ,
       0.1615    , 0.1581    , 4.61882411, 0.153     , 0.1496    ,
       4.98614528, 0.1428    , 0.1411    , 0.1377    , 0.136     ,
       0.1326    , 0.1309    , 0.1292    , 0.1258    , 6.18211773,
       0.1224    , 0.1207    , 0.1173    , 0.1156    , 0.1139    ,
       0.1122    , 0.1105    , 0.1088    , 0.1071    , 0.1054    ,
       7.59306603, 0.1037    , 0.102     , 0.1003    , 0.0986    ,
       0.0986    , 0.0969    , 8.59940168, 0.0935    , 8.78868717,
       0.0918    , 0.0901    , 0.0901    , 0.0884    , 0.0867 

# Partido Liberal

In [20]:
x_2 = f0_fe_2_fe.sum()
x_2 

68.14792781202146

In [21]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [22]:
f0 = np.array(f0)
f0

array([0, 1, 1, 1, 1, 2, 0, 0, 2, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [23]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.002, 0.002, 0.002, 0.002, 0.004, 0.   , 0.   , 0.004,
       0.   , 0.004, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.004, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [24]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [25]:
f0_tot=f0.sum()
f0_tot

17

In [26]:
fe = benford*f0_tot

In [27]:
fe 

array([0.7038, 0.6426, 0.5916, 0.5474, 0.51  , 0.476 , 0.4471, 0.4216,
       0.3995, 0.3791, 0.3604, 0.3434, 0.3281, 0.3145, 0.3009, 0.289 ,
       0.2788, 0.2686, 0.2584, 0.2499, 0.2414, 0.2346, 0.2278, 0.221 ,
       0.2142, 0.2074, 0.2023, 0.1972, 0.1921, 0.187 , 0.1819, 0.1785,
       0.1734, 0.17  , 0.1666, 0.1615, 0.1581, 0.1547, 0.153 , 0.1496,
       0.1462, 0.1428, 0.1411, 0.1377, 0.136 , 0.1326, 0.1309, 0.1292,
       0.1258, 0.1241, 0.1224, 0.1207, 0.1173, 0.1156, 0.1139, 0.1122,
       0.1105, 0.1088, 0.1071, 0.1054, 0.1054, 0.1037, 0.102 , 0.1003,
       0.0986, 0.0986, 0.0969, 0.0952, 0.0935, 0.0935, 0.0918, 0.0901,
       0.0901, 0.0884, 0.0867, 0.0867, 0.085 , 0.085 , 0.0833, 0.0833,
       0.0816, 0.0799, 0.0799, 0.0782, 0.0782, 0.0765, 0.0765, 0.0765,
       0.0748, 0.0748])

In [28]:
fe.sum()

16.998299999999997

In [29]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0358, -0.0328, -0.0302, -0.028 , -0.024 , -0.0263,
       -0.0248, -0.0195, -0.0223, -0.0172, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.015 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0114, -0.009 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0087, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0064,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0047, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [30]:
diferencia.sum()

-0.9659

In [31]:
f0_fe= (f0-fe)

In [32]:
f0_fe_2 = f0_fe*f0_fe

In [33]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.7038    ,  0.19877803,  0.2819313 ,  0.37421768,  0.47078431,
        4.87936134,  0.4471    ,  0.4216    ,  6.41201564,  0.3791    ,
        7.45917913,  0.3434    ,  0.3281    ,  0.3145    ,  0.3009    ,
        1.74920761,  0.2788    ,  0.2686    ,  0.2584    ,  0.2499    ,
        0.2414    ,  0.2346    ,  2.61761563, 14.32054751,  0.2142    ,
        0.2074    ,  0.2023    ,  0.1972    ,  0.1921    ,  0.187     ,
        3.67942611,  0.1785    ,  0.1734    ,  0.17      ,  0.1666    ,
        0.1615    ,  0.1581    ,  0.1547    ,  0.153     ,  0.1496    ,
        0.1462    ,  5.14560112,  0.1411    ,  0.1377    ,  0.136     ,
        0.1326    ,  0.1309    ,  0.1292    ,  0.1258    ,  0.1241    ,
        0.1224    ,  0.1207    ,  0.1173    ,  0.1156    ,  6.89353126,
        0.1122    ,  0.1105    ,  0.1088    ,  0.1071    ,  0.1054    ,
        0.1054    ,  0.1037    ,  0.102     ,  0.1003    ,  0.0986    ,
        0.0986    ,  0.0969    ,  0.0952    ,  0.0935    ,  0.09

# Partido Nacional

In [34]:
x_2 = f0_fe_2_fe.sum()
x_2 

66.7765966931085

In [35]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [36]:
f0 = np.array(f0)
f0

array([1, 0, 1, 0, 1, 1, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [37]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.   , 0.002, 0.   , 0.002, 0.002, 0.004, 0.004, 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.004, 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [38]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [39]:
f0_tot=f0.sum()
f0_tot

17

In [40]:
fe = benford*f0_tot

In [41]:
fe 

array([0.7038, 0.6426, 0.5916, 0.5474, 0.51  , 0.476 , 0.4471, 0.4216,
       0.3995, 0.3791, 0.3604, 0.3434, 0.3281, 0.3145, 0.3009, 0.289 ,
       0.2788, 0.2686, 0.2584, 0.2499, 0.2414, 0.2346, 0.2278, 0.221 ,
       0.2142, 0.2074, 0.2023, 0.1972, 0.1921, 0.187 , 0.1819, 0.1785,
       0.1734, 0.17  , 0.1666, 0.1615, 0.1581, 0.1547, 0.153 , 0.1496,
       0.1462, 0.1428, 0.1411, 0.1377, 0.136 , 0.1326, 0.1309, 0.1292,
       0.1258, 0.1241, 0.1224, 0.1207, 0.1173, 0.1156, 0.1139, 0.1122,
       0.1105, 0.1088, 0.1071, 0.1054, 0.1054, 0.1037, 0.102 , 0.1003,
       0.0986, 0.0986, 0.0969, 0.0952, 0.0935, 0.0935, 0.0918, 0.0901,
       0.0901, 0.0884, 0.0867, 0.0867, 0.085 , 0.085 , 0.0833, 0.0833,
       0.0816, 0.0799, 0.0799, 0.0782, 0.0782, 0.0765, 0.0765, 0.0765,
       0.0748, 0.0748])

In [42]:
fe.sum()

16.998299999999997

In [43]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0378, -0.0328, -0.0322, -0.028 , -0.026 , -0.0223,
       -0.0208, -0.0235, -0.0203, -0.0212, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0118, -0.0134, -0.013 , -0.0086, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.009 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0073, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0061, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0045, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0035, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [44]:
diferencia.sum()

-0.9659

In [45]:
f0_fe= (f0-fe)

In [46]:
f0_fe_2 = f0_fe*f0_fe

In [47]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.1246582 ,  0.6426    ,  0.2819313 ,  0.5474    ,  0.47078431,
        0.57684034,  5.3936444 ,  5.90926603,  0.3995    ,  1.01692643,
        0.3604    ,  0.3434    ,  0.3281    ,  0.3145    ,  0.3009    ,
        0.289     ,  0.2788    ,  0.2686    ,  0.2584    ,  0.2499    ,
        0.2414    ,  2.4971746 ,  0.2278    ,  0.221     , 14.88833632,
        0.2074    ,  0.2023    ,  0.1972    ,  0.1921    ,  3.53459358,
        0.1819    ,  0.1785    ,  0.1734    ,  0.17      ,  0.1666    ,
        0.1615    ,  4.48321069,  0.1547    ,  0.153     ,  0.1496    ,
        0.1462    ,  0.1428    ,  0.1411    ,  5.39986412,  0.136     ,
        0.1326    ,  0.1309    ,  0.1292    ,  0.1258    ,  0.1241    ,
        0.1224    ,  0.1207    ,  0.1173    ,  0.1156    ,  0.1139    ,
        0.1122    ,  7.16027376,  0.1088    ,  0.1071    ,  0.1054    ,
        0.1054    ,  0.1037    ,  0.102     ,  0.1003    ,  0.0986    ,
        0.0986    ,  0.0969    ,  0.0952    ,  8.78868717,  0.09

# Partido Libre

In [48]:
x_2 = f0_fe_2_fe.sum()
x_2 

72.85969125046658

In [49]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [50]:
f0 = np.array(f0)
f0

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [51]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.004, 0.002, 0.   , 0.002, 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.002, 0.002,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.004, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.004, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [52]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [53]:
f0_tot=f0.sum()
f0_tot

17

In [54]:
fe = benford*f0_tot

In [55]:
fe 

array([0.7038, 0.6426, 0.5916, 0.5474, 0.51  , 0.476 , 0.4471, 0.4216,
       0.3995, 0.3791, 0.3604, 0.3434, 0.3281, 0.3145, 0.3009, 0.289 ,
       0.2788, 0.2686, 0.2584, 0.2499, 0.2414, 0.2346, 0.2278, 0.221 ,
       0.2142, 0.2074, 0.2023, 0.1972, 0.1921, 0.187 , 0.1819, 0.1785,
       0.1734, 0.17  , 0.1666, 0.1615, 0.1581, 0.1547, 0.153 , 0.1496,
       0.1462, 0.1428, 0.1411, 0.1377, 0.136 , 0.1326, 0.1309, 0.1292,
       0.1258, 0.1241, 0.1224, 0.1207, 0.1173, 0.1156, 0.1139, 0.1122,
       0.1105, 0.1088, 0.1071, 0.1054, 0.1054, 0.1037, 0.102 , 0.1003,
       0.0986, 0.0986, 0.0969, 0.0952, 0.0935, 0.0935, 0.0918, 0.0901,
       0.0901, 0.0884, 0.0867, 0.0867, 0.085 , 0.085 , 0.0833, 0.0833,
       0.0816, 0.0799, 0.0799, 0.0782, 0.0782, 0.0765, 0.0765, 0.0765,
       0.0748, 0.0748])

In [56]:
fe.sum()

16.998299999999997

In [57]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0358, -0.0348, -0.0322, -0.03  , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0172, -0.0182, -0.0193, -0.0165,
       -0.0177, -0.015 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.011 , -0.0126, -0.0102, -0.0099, -0.0096,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.008 , -0.0098,
       -0.0095, -0.0073, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0027, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0021, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.003 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [58]:
diferencia.sum()

-0.9659

In [59]:
f0_fe= (f0-fe)

In [60]:
f0_fe_2 = f0_fe*f0_fe

In [61]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.7038    ,  0.19877803,  0.5916    ,  0.5474    ,  0.51      ,
        0.476     ,  0.4471    ,  0.4216    ,  0.3995    ,  0.3791    ,
        7.45917913,  1.25545591,  0.3281    ,  1.49415024,  0.3009    ,
        1.74920761,  0.2788    ,  0.2686    ,  0.2584    ,  0.2499    ,
        0.2414    ,  0.2346    ,  0.2278    ,  2.74588688,  0.2142    ,
        3.02900077,  3.14545373,  3.26819391,  0.1921    ,  0.187     ,
        0.1819    ,  0.1785    ,  0.1734    ,  4.05235294,  0.1666    ,
        0.1615    ,  4.48321069,  0.1547    ,  0.153     ,  0.1496    ,
        0.1462    ,  0.1428    ,  0.1411    ,  0.1377    ,  0.136     ,
        0.1326    ,  0.1309    ,  0.1292    ,  0.1258    ,  0.1241    ,
        0.1224    ,  0.1207    ,  0.1173    ,  0.1156    , 31.23242502,
        0.1122    ,  0.1105    ,  0.1088    ,  0.1071    ,  0.1054    ,
        0.1054    , 34.67650617,  0.102     ,  0.1003    ,  0.0986    ,
        0.0986    ,  0.0969    ,  0.0952    ,  0.0935    ,  0.09

# Total

In [62]:
x_2 = f0_fe_2_fe.sum()
x_2 

122.2293069262026