In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1VA4yihruttcj_lAHd-RMrIzFJ8HnOipm/export?format=csv")
df

PL    PN  LIBRE-PINU  TOTAL
0  2427  4387        6245  13174
1   815  1138         722   2688
2  1348  1372        1360   4111
3   451   955         676   2105

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[2427, 815, 1348, 451]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[4387, 1138, 1372, 955]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[6245, 722, 1360, 676]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[13174, 2688, 4111, 2105]

In [7]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [8]:
f0 = np.array(f0)
f0

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [9]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [10]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [11]:
f0_tot=f0.sum()
f0_tot

4

In [12]:
fe = benford*f0_tot

In [13]:
fe 

array([0.1656, 0.1512, 0.1392, 0.1288, 0.12  , 0.112 , 0.1052, 0.0992,
       0.094 , 0.0892, 0.0848, 0.0808, 0.0772, 0.074 , 0.0708, 0.068 ,
       0.0656, 0.0632, 0.0608, 0.0588, 0.0568, 0.0552, 0.0536, 0.052 ,
       0.0504, 0.0488, 0.0476, 0.0464, 0.0452, 0.044 , 0.0428, 0.042 ,
       0.0408, 0.04  , 0.0392, 0.038 , 0.0372, 0.0364, 0.036 , 0.0352,
       0.0344, 0.0336, 0.0332, 0.0324, 0.032 , 0.0312, 0.0308, 0.0304,
       0.0296, 0.0292, 0.0288, 0.0284, 0.0276, 0.0272, 0.0268, 0.0264,
       0.026 , 0.0256, 0.0252, 0.0248, 0.0248, 0.0244, 0.024 , 0.0236,
       0.0232, 0.0232, 0.0228, 0.0224, 0.022 , 0.022 , 0.0216, 0.0212,
       0.0212, 0.0208, 0.0204, 0.0204, 0.02  , 0.02  , 0.0196, 0.0196,
       0.0192, 0.0188, 0.0188, 0.0184, 0.0184, 0.018 , 0.018 , 0.018 ,
       0.0176, 0.0176])

In [14]:
fe.sum()

3.9995999999999996

In [15]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0378, -0.0348, -0.0302, -0.03  , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0202, -0.0193, -0.0185,
       -0.0157, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0075, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0033, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [16]:
diferencia.sum()

-0.9918999999999999

In [17]:
f0_fe= (f0-fe)

In [18]:
f0_fe_2 = f0_fe*f0_fe

In [19]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.65600000e-01, 1.51200000e-01, 1.39200000e-01, 5.89277516e+00,
       1.20000000e-01, 1.12000000e-01, 1.05200000e-01, 9.92000000e-02,
       9.40000000e-02, 8.92000000e-02, 8.48000000e-02, 8.08000000e-02,
       7.72000000e-02, 7.40000000e-02, 1.21950938e+01, 6.80000000e-02,
       6.56000000e-02, 6.32000000e-02, 6.08000000e-02, 5.88000000e-02,
       5.68000000e-02, 5.52000000e-02, 5.36000000e-02, 5.20000000e-02,
       5.04000000e-02, 4.88000000e-02, 4.76000000e-02, 4.64000000e-02,
       4.52000000e-02, 4.40000000e-02, 4.28000000e-02, 4.20000000e-02,
       4.08000000e-02, 4.00000000e-02, 3.92000000e-02, 2.43537895e+01,
       3.72000000e-02, 3.64000000e-02, 3.60000000e-02, 3.52000000e-02,
       3.44000000e-02, 3.36000000e-02, 3.32000000e-02, 3.24000000e-02,
       3.20000000e-02, 3.12000000e-02, 3.08000000e-02, 3.04000000e-02,
       2.96000000e-02, 2.92000000e-02, 2.88000000e-02, 2.84000000e-02,
       2.76000000e-02, 2.72000000e-02, 2.68000000e-02, 2.64000000e-02,
      

# Partido Liberal

In [20]:
x_2 = f0_fe_2_fe.sum()
x_2 

91.37346973502916

In [21]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [22]:
f0 = np.array(f0)
f0

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0])

In [23]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ])

In [24]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [25]:
f0_tot=f0.sum()
f0_tot

4

In [26]:
fe = benford*f0_tot

In [27]:
fe 

array([0.1656, 0.1512, 0.1392, 0.1288, 0.12  , 0.112 , 0.1052, 0.0992,
       0.094 , 0.0892, 0.0848, 0.0808, 0.0772, 0.074 , 0.0708, 0.068 ,
       0.0656, 0.0632, 0.0608, 0.0588, 0.0568, 0.0552, 0.0536, 0.052 ,
       0.0504, 0.0488, 0.0476, 0.0464, 0.0452, 0.044 , 0.0428, 0.042 ,
       0.0408, 0.04  , 0.0392, 0.038 , 0.0372, 0.0364, 0.036 , 0.0352,
       0.0344, 0.0336, 0.0332, 0.0324, 0.032 , 0.0312, 0.0308, 0.0304,
       0.0296, 0.0292, 0.0288, 0.0284, 0.0276, 0.0272, 0.0268, 0.0264,
       0.026 , 0.0256, 0.0252, 0.0248, 0.0248, 0.0244, 0.024 , 0.0236,
       0.0232, 0.0232, 0.0228, 0.0224, 0.022 , 0.022 , 0.0216, 0.0212,
       0.0212, 0.0208, 0.0204, 0.0204, 0.02  , 0.02  , 0.0196, 0.0196,
       0.0192, 0.0188, 0.0188, 0.0184, 0.0184, 0.018 , 0.018 , 0.018 ,
       0.0176, 0.0176])

In [28]:
fe.sum()

3.9995999999999996

In [29]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0358, -0.0348, -0.0302, -0.03  , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.008 , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0025, -0.0045, -0.0045, -0.0044, -0.0044])

In [30]:
diferencia.sum()

-0.9918999999999999

In [31]:
f0_fe= (f0-fe)

In [32]:
f0_fe_2 = f0_fe*f0_fe

In [33]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.65600000e-01, 4.76495661e+00, 1.39200000e-01, 5.89277516e+00,
       1.20000000e-01, 1.12000000e-01, 1.05200000e-01, 9.92000000e-02,
       9.40000000e-02, 8.92000000e-02, 8.48000000e-02, 8.08000000e-02,
       7.72000000e-02, 7.40000000e-02, 7.08000000e-02, 6.80000000e-02,
       6.56000000e-02, 6.32000000e-02, 6.08000000e-02, 5.88000000e-02,
       5.68000000e-02, 5.52000000e-02, 5.36000000e-02, 5.20000000e-02,
       5.04000000e-02, 4.88000000e-02, 4.76000000e-02, 4.64000000e-02,
       4.52000000e-02, 4.40000000e-02, 4.28000000e-02, 4.20000000e-02,
       4.08000000e-02, 2.30400000e+01, 3.92000000e-02, 3.80000000e-02,
       3.72000000e-02, 3.64000000e-02, 3.60000000e-02, 3.52000000e-02,
       3.44000000e-02, 3.36000000e-02, 3.32000000e-02, 3.24000000e-02,
       3.20000000e-02, 3.12000000e-02, 3.08000000e-02, 3.04000000e-02,
       2.96000000e-02, 2.92000000e-02, 2.88000000e-02, 2.84000000e-02,
       2.76000000e-02, 2.72000000e-02, 2.68000000e-02, 2.64000000e-02,
      

# Partido Nacional

In [34]:
x_2 = f0_fe_2_fe.sum()
x_2 

90.93288732459168

In [35]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [36]:
f0 = np.array(f0)
f0

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [37]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [38]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [39]:
f0_tot=f0.sum()
f0_tot

4

In [40]:
fe = benford*f0_tot

In [41]:
fe 

array([0.1656, 0.1512, 0.1392, 0.1288, 0.12  , 0.112 , 0.1052, 0.0992,
       0.094 , 0.0892, 0.0848, 0.0808, 0.0772, 0.074 , 0.0708, 0.068 ,
       0.0656, 0.0632, 0.0608, 0.0588, 0.0568, 0.0552, 0.0536, 0.052 ,
       0.0504, 0.0488, 0.0476, 0.0464, 0.0452, 0.044 , 0.0428, 0.042 ,
       0.0408, 0.04  , 0.0392, 0.038 , 0.0372, 0.0364, 0.036 , 0.0352,
       0.0344, 0.0336, 0.0332, 0.0324, 0.032 , 0.0312, 0.0308, 0.0304,
       0.0296, 0.0292, 0.0288, 0.0284, 0.0276, 0.0272, 0.0268, 0.0264,
       0.026 , 0.0256, 0.0252, 0.0248, 0.0248, 0.0244, 0.024 , 0.0236,
       0.0232, 0.0232, 0.0228, 0.0224, 0.022 , 0.022 , 0.0216, 0.0212,
       0.0212, 0.0208, 0.0204, 0.0204, 0.02  , 0.02  , 0.0196, 0.0196,
       0.0192, 0.0188, 0.0188, 0.0184, 0.0184, 0.018 , 0.018 , 0.018 ,
       0.0176, 0.0176])

In [42]:
fe.sum()

3.9995999999999996

In [43]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0378, -0.0348, -0.0302, -0.03  , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0049, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0044, -0.0063, -0.0062, -0.0062, -0.0061, -0.004 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [44]:
diferencia.sum()

-0.9918999999999999

In [45]:
f0_fe= (f0-fe)

In [46]:
f0_fe_2 = f0_fe*f0_fe

In [47]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.65600000e-01, 1.51200000e-01, 1.39200000e-01, 5.89277516e+00,
       1.20000000e-01, 1.12000000e-01, 1.05200000e-01, 9.92000000e-02,
       9.40000000e-02, 8.92000000e-02, 8.48000000e-02, 8.08000000e-02,
       7.72000000e-02, 7.40000000e-02, 7.08000000e-02, 6.80000000e-02,
       6.56000000e-02, 6.32000000e-02, 6.08000000e-02, 5.88000000e-02,
       5.68000000e-02, 5.52000000e-02, 5.36000000e-02, 5.20000000e-02,
       5.04000000e-02, 4.88000000e-02, 4.76000000e-02, 4.64000000e-02,
       4.52000000e-02, 4.40000000e-02, 4.28000000e-02, 4.20000000e-02,
       4.08000000e-02, 4.00000000e-02, 3.92000000e-02, 3.80000000e-02,
       3.72000000e-02, 3.64000000e-02, 3.60000000e-02, 3.52000000e-02,
       3.44000000e-02, 3.36000000e-02, 3.32000000e-02, 3.24000000e-02,
       3.20000000e-02, 3.12000000e-02, 3.08000000e-02, 3.04000000e-02,
       2.96000000e-02, 2.92000000e-02, 2.88000000e-02, 2.84000000e-02,
       3.42594841e+01, 2.72000000e-02, 2.68000000e-02, 2.64000000e-02,
      

# Partido Libre

In [48]:
x_2 = f0_fe_2_fe.sum()
x_2 

120.7246258799172

In [49]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [50]:
f0 = np.array(f0)
f0

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [51]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [52]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [53]:
f0_tot=f0.sum()
f0_tot

4

In [54]:
fe = benford*f0_tot

In [55]:
fe 

array([0.1656, 0.1512, 0.1392, 0.1288, 0.12  , 0.112 , 0.1052, 0.0992,
       0.094 , 0.0892, 0.0848, 0.0808, 0.0772, 0.074 , 0.0708, 0.068 ,
       0.0656, 0.0632, 0.0608, 0.0588, 0.0568, 0.0552, 0.0536, 0.052 ,
       0.0504, 0.0488, 0.0476, 0.0464, 0.0452, 0.044 , 0.0428, 0.042 ,
       0.0408, 0.04  , 0.0392, 0.038 , 0.0372, 0.0364, 0.036 , 0.0352,
       0.0344, 0.0336, 0.0332, 0.0324, 0.032 , 0.0312, 0.0308, 0.0304,
       0.0296, 0.0292, 0.0288, 0.0284, 0.0276, 0.0272, 0.0268, 0.0264,
       0.026 , 0.0256, 0.0252, 0.0248, 0.0248, 0.0244, 0.024 , 0.0236,
       0.0232, 0.0232, 0.0228, 0.0224, 0.022 , 0.022 , 0.0216, 0.0212,
       0.0212, 0.0208, 0.0204, 0.0204, 0.02  , 0.02  , 0.0196, 0.0196,
       0.0192, 0.0188, 0.0188, 0.0184, 0.0184, 0.018 , 0.018 , 0.018 ,
       0.0176, 0.0176])

In [56]:
fe.sum()

3.9995999999999996

In [57]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0378, -0.0348, -0.0302, -0.03  , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0182, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0144, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0085, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [58]:
diferencia.sum()

-0.9919

In [59]:
f0_fe= (f0-fe)

In [60]:
f0_fe_2 = f0_fe*f0_fe

In [61]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.65600000e-01, 1.51200000e-01, 1.39200000e-01, 5.89277516e+00,
       1.20000000e-01, 1.12000000e-01, 1.05200000e-01, 9.92000000e-02,
       9.40000000e-02, 8.92000000e-02, 8.48000000e-02, 1.04570376e+01,
       7.72000000e-02, 7.40000000e-02, 7.08000000e-02, 6.80000000e-02,
       1.33095024e+01, 6.32000000e-02, 6.08000000e-02, 5.88000000e-02,
       5.68000000e-02, 5.52000000e-02, 5.36000000e-02, 5.20000000e-02,
       5.04000000e-02, 4.88000000e-02, 4.76000000e-02, 4.64000000e-02,
       4.52000000e-02, 4.40000000e-02, 4.28000000e-02, 2.18515238e+01,
       4.08000000e-02, 4.00000000e-02, 3.92000000e-02, 3.80000000e-02,
       3.72000000e-02, 3.64000000e-02, 3.60000000e-02, 3.52000000e-02,
       3.44000000e-02, 3.36000000e-02, 3.32000000e-02, 3.24000000e-02,
       3.20000000e-02, 3.12000000e-02, 3.08000000e-02, 3.04000000e-02,
       2.96000000e-02, 2.92000000e-02, 2.88000000e-02, 2.84000000e-02,
       2.76000000e-02, 2.72000000e-02, 2.68000000e-02, 2.64000000e-02,
      

# Total

In [62]:
x_2 = f0_fe_2_fe.sum()
x_2 

55.19323902759008