In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1CfI-HjqE2wp51lWUJuBH6wSN1l0kQfvq/export?format=csv")
df

PL    PN  LIBRE-PINU  TOTAL
0   3274  6600        8141  18099
1    640  1712         638   3011
2    191  1165         318   1689
3    655   573         989   2230
4    884  1800         668   3380
5   1956  3534         408   5927
6    921   602         357   1883
7   2254  5961        3799  12103
8    249   421          93    776
9   1131  2057         709   3921
10   210   872         305   1397
11  1183  2018        1098   4331
12   388   464         277   1145
13   624  1891         913   3448
14  1638  2710         444   4835
15  1031  3145         746   4990
16  1561  2699         699   5051
17  2723  4604        1066   8427
18   845  2714         250   3842

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[3274,
 640,
 191,
 655,
 884,
 1956,
 921,
 2254,
 249,
 1131,
 210,
 1183,
 388,
 624,
 1638,
 1031,
 1561,
 2723,
 845]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[6600,
 1712,
 1165,
 573,
 1800,
 3534,
 602,
 5961,
 421,
 2057,
 872,
 2018,
 464,
 1891,
 2710,
 3145,
 2699,
 4604,
 2714]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[8141,
 638,
 318,
 989,
 668,
 408,
 357,
 3799,
 93,
 709,
 305,
 1098,
 277,
 913,
 444,
 746,
 699,
 1066,
 250]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[18099,
 3011,
 1689,
 2230,
 3380,
 5927,
 1883,
 12103,
 776,
 3921,
 1397,
 4331,
 1145,
 3448,
 4835,
 4990,
 5051,
 8427,
 3842]

In [7]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [8]:
f0 = np.array(f0)
f0

array([1, 2, 0, 0, 0, 1, 1, 0, 0, 2, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0])

In [9]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.004, 0.   , 0.   , 0.   , 0.002, 0.002, 0.   , 0.   ,
       0.004, 0.   , 0.002, 0.002, 0.   , 0.002, 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [10]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [11]:
f0_tot=f0.sum()
f0_tot

19

In [12]:
fe = benford*f0_tot

In [13]:
fe 

array([0.7866, 0.7182, 0.6612, 0.6118, 0.57  , 0.532 , 0.4997, 0.4712,
       0.4465, 0.4237, 0.4028, 0.3838, 0.3667, 0.3515, 0.3363, 0.323 ,
       0.3116, 0.3002, 0.2888, 0.2793, 0.2698, 0.2622, 0.2546, 0.247 ,
       0.2394, 0.2318, 0.2261, 0.2204, 0.2147, 0.209 , 0.2033, 0.1995,
       0.1938, 0.19  , 0.1862, 0.1805, 0.1767, 0.1729, 0.171 , 0.1672,
       0.1634, 0.1596, 0.1577, 0.1539, 0.152 , 0.1482, 0.1463, 0.1444,
       0.1406, 0.1387, 0.1368, 0.1349, 0.1311, 0.1292, 0.1273, 0.1254,
       0.1235, 0.1216, 0.1197, 0.1178, 0.1178, 0.1159, 0.114 , 0.1121,
       0.1102, 0.1102, 0.1083, 0.1064, 0.1045, 0.1045, 0.1026, 0.1007,
       0.1007, 0.0988, 0.0969, 0.0969, 0.095 , 0.095 , 0.0931, 0.0931,
       0.0912, 0.0893, 0.0893, 0.0874, 0.0874, 0.0855, 0.0855, 0.0855,
       0.0836, 0.0836])

In [14]:
fe.sum()

18.9981

In [15]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0338, -0.0348, -0.0322, -0.03  , -0.026 , -0.0243,
       -0.0248, -0.0235, -0.0183, -0.0212, -0.0182, -0.0173, -0.0185,
       -0.0157, -0.017 , -0.0164, -0.0138, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0114, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0093, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0049, -0.0068, -0.0047, -0.0046,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0031, -0.0051, -0.005 ,
       -0.005 , -0.0029, -0.0049, -0.0048, -0.0047, -0.0027, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [16]:
diferencia.sum()

-0.9619

In [17]:
f0_fe= (f0-fe)

In [18]:
f0_fe_2 = f0_fe*f0_fe

In [19]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.05789418, 2.28767925, 0.6612    , 0.6118    , 0.57      ,
       0.41169925, 0.50090072, 0.4712    , 0.4465    , 5.86434196,
       0.4028    , 0.98932371, 1.09372482, 0.3515    , 1.30983553,
       0.323     , 0.3116    , 1.63131259, 0.2888    , 0.2793    ,
       0.2698    , 0.2622    , 2.18232977, 0.247     , 0.2394    ,
       0.2318    , 0.2261    , 0.2204    , 2.87236185, 0.209     ,
       0.2033    , 0.1995    , 0.1938    , 0.19      , 0.1862    ,
       0.1805    , 0.1767    , 0.1729    , 0.171     , 0.1672    ,
       0.1634    , 0.1596    , 0.1577    , 0.1539    , 0.152     ,
       0.1482    , 0.1463    , 0.1444    , 0.1406    , 0.1387    ,
       0.1368    , 0.1349    , 5.75886506, 0.1292    , 5.98275954,
       6.09988166, 0.1235    , 0.1216    , 0.1197    , 0.1178    ,
       0.1178    , 0.1159    , 0.114     , 0.1121    , 0.1102    ,
       0.1102    , 0.1083    , 0.1064    , 0.1045    , 0.1045    ,
       0.1026    , 0.1007    , 0.1007    , 0.0988    , 8.41681

# Partido Liberal

In [20]:
x_2 = f0_fe_2_fe.sum()
x_2 

77.09997419679003

In [21]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [22]:
f0 = np.array(f0)
f0

array([0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [23]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.004,
       0.   , 0.004, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.004,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.004, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.002, 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [24]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [25]:
f0_tot=f0.sum()
f0_tot

19

In [26]:
fe = benford*f0_tot

In [27]:
fe 

array([0.7866, 0.7182, 0.6612, 0.6118, 0.57  , 0.532 , 0.4997, 0.4712,
       0.4465, 0.4237, 0.4028, 0.3838, 0.3667, 0.3515, 0.3363, 0.323 ,
       0.3116, 0.3002, 0.2888, 0.2793, 0.2698, 0.2622, 0.2546, 0.247 ,
       0.2394, 0.2318, 0.2261, 0.2204, 0.2147, 0.209 , 0.2033, 0.1995,
       0.1938, 0.19  , 0.1862, 0.1805, 0.1767, 0.1729, 0.171 , 0.1672,
       0.1634, 0.1596, 0.1577, 0.1539, 0.152 , 0.1482, 0.1463, 0.1444,
       0.1406, 0.1387, 0.1368, 0.1349, 0.1311, 0.1292, 0.1273, 0.1254,
       0.1235, 0.1216, 0.1197, 0.1178, 0.1178, 0.1159, 0.114 , 0.1121,
       0.1102, 0.1102, 0.1083, 0.1064, 0.1045, 0.1045, 0.1026, 0.1007,
       0.1007, 0.0988, 0.0969, 0.0969, 0.095 , 0.095 , 0.0931, 0.0931,
       0.0912, 0.0893, 0.0893, 0.0874, 0.0874, 0.0855, 0.0855, 0.0855,
       0.0836, 0.0836])

In [28]:
fe.sum()

18.9981

In [29]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0358, -0.0348, -0.0322, -0.03  , -0.028 , -0.0263,
       -0.0228, -0.0195, -0.0223, -0.0172, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0144, -0.0118, -0.0152, -0.0147, -0.0142,
       -0.0118, -0.0134, -0.013 , -0.0126, -0.0102, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0082, -0.01  , -0.0098,
       -0.0095, -0.0053, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0056, -0.0074,
       -0.0053, -0.0052, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0045, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.003 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [30]:
diferencia.sum()

-0.9619

In [31]:
f0_fe= (f0-fe)

In [32]:
f0_fe_2 = f0_fe*f0_fe

In [33]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.7866    ,  0.11056981,  0.6612    ,  0.6118    ,  0.57      ,
        0.532     ,  0.4997    ,  0.59344109,  5.40506663,  0.4237    ,
        6.33328659,  0.3838    ,  0.3667    ,  0.3515    ,  0.3363    ,
        0.323     ,  1.52084262,  9.62465037,  0.2888    ,  0.2793    ,
        0.2698    ,  2.07608253,  0.2546    ,  0.247     ,  0.2394    ,
        2.54586385,  0.2261    ,  0.2204    ,  0.2147    ,  0.209     ,
        0.2033    ,  0.1995    ,  3.35375872,  0.19      ,  0.1862    ,
        0.1805    , 18.81393826,  0.1729    ,  0.171     ,  0.1672    ,
        0.1634    ,  0.1596    ,  0.1577    ,  0.1539    ,  0.152     ,
        0.1482    ,  0.1463    ,  5.06960776,  0.1406    ,  5.34850534,
        5.44674152,  0.1349    ,  0.1311    ,  0.1292    ,  0.1273    ,
        0.1254    ,  6.22066599,  0.1216    ,  0.1197    ,  0.1178    ,
        0.1178    ,  0.1159    ,  0.114     ,  0.1121    ,  0.1102    ,
        0.1102    ,  0.1083    ,  0.1064    ,  0.1045    ,  0.10

# Partido Nacional

In [34]:
x_2 = f0_fe_2_fe.sum()
x_2 

95.92903685951548

In [35]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [36]:
f0 = np.array(f0)
f0

array([2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0])

In [37]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.004, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.002,
       0.   , 0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.002, 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.002, 0.002, 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ])

In [38]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [39]:
f0_tot=f0.sum()
f0_tot

19

In [40]:
fe = benford*f0_tot

In [41]:
fe 

array([0.7866, 0.7182, 0.6612, 0.6118, 0.57  , 0.532 , 0.4997, 0.4712,
       0.4465, 0.4237, 0.4028, 0.3838, 0.3667, 0.3515, 0.3363, 0.323 ,
       0.3116, 0.3002, 0.2888, 0.2793, 0.2698, 0.2622, 0.2546, 0.247 ,
       0.2394, 0.2318, 0.2261, 0.2204, 0.2147, 0.209 , 0.2033, 0.1995,
       0.1938, 0.19  , 0.1862, 0.1805, 0.1767, 0.1729, 0.171 , 0.1672,
       0.1634, 0.1596, 0.1577, 0.1539, 0.152 , 0.1482, 0.1463, 0.1444,
       0.1406, 0.1387, 0.1368, 0.1349, 0.1311, 0.1292, 0.1273, 0.1254,
       0.1235, 0.1216, 0.1197, 0.1178, 0.1178, 0.1159, 0.114 , 0.1121,
       0.1102, 0.1102, 0.1083, 0.1064, 0.1045, 0.1045, 0.1026, 0.1007,
       0.1007, 0.0988, 0.0969, 0.0969, 0.095 , 0.095 , 0.0931, 0.0931,
       0.0912, 0.0893, 0.0893, 0.0874, 0.0874, 0.0855, 0.0855, 0.0855,
       0.0836, 0.0836])

In [42]:
fe.sum()

18.9981

In [43]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0374, -0.0378, -0.0348, -0.0322, -0.03  , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.015 , -0.0164, -0.0138, -0.0152, -0.0147, -0.0122,
       -0.0118, -0.0134, -0.013 , -0.0126, -0.0102, -0.0119, -0.0096,
       -0.0113, -0.011 , -0.0087, -0.0105, -0.0102, -0.01  , -0.0078,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0048, -0.0067, -0.0066,
       -0.0045, -0.0064, -0.0063, -0.0042, -0.0042, -0.0061, -0.006 ,
       -0.0059, -0.0038, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0033, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0027, -0.0047, -0.0026,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0024, -0.0044])

In [44]:
diferencia.sum()

-0.9619

In [45]:
f0_fe= (f0-fe)

In [46]:
f0_fe_2 = f0_fe*f0_fe

In [47]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 1.87177671,  0.7182    ,  0.6612    ,  0.6118    ,  0.57      ,
        0.532     ,  0.4997    ,  0.4712    ,  0.4465    ,  0.4237    ,
        0.4028    ,  0.3838    ,  0.3667    ,  0.3515    ,  0.3363    ,
        1.41897523,  0.3116    ,  1.63131259,  0.2888    ,  0.2793    ,
        1.97624922,  2.07608253,  0.2546    ,  0.247     ,  0.2394    ,
        2.54586385,  0.2261    ,  2.75760508,  0.2147    ,  0.209     ,
        3.12213915,  0.1995    ,  0.1938    ,  0.19      ,  3.55676928,
        0.1805    ,  0.1767    ,  0.1729    ,  0.171     ,  0.1672    ,
        0.1634    ,  0.1596    ,  0.1577    ,  0.1539    ,  0.152     ,
        0.1482    ,  0.1463    ,  0.1444    ,  0.1406    ,  0.1387    ,
        0.1368    ,  0.1349    ,  0.1311    ,  5.86913808,  0.1273    ,
        0.1254    ,  6.22066599,  0.1216    ,  0.1197    ,  6.60676435,
        6.60676435,  0.1159    ,  0.114     ,  0.1121    ,  7.18461016,
        0.1102    ,  0.1083    ,  0.1064    ,  0.1045    ,  0.10

# Partido Libre

In [48]:
x_2 = f0_fe_2_fe.sum()
x_2 

105.59288154612267

In [49]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [50]:
f0 = np.array(f0)
f0

array([0, 1, 1, 1, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [51]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.002, 0.002, 0.002, 0.   , 0.   , 0.002, 0.   , 0.004,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.002, 0.002, 0.   , 0.   ,
       0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.002, 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [52]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [53]:
f0_tot=f0.sum()
f0_tot

19

In [54]:
fe = benford*f0_tot

In [55]:
fe 

array([0.7866, 0.7182, 0.6612, 0.6118, 0.57  , 0.532 , 0.4997, 0.4712,
       0.4465, 0.4237, 0.4028, 0.3838, 0.3667, 0.3515, 0.3363, 0.323 ,
       0.3116, 0.3002, 0.2888, 0.2793, 0.2698, 0.2622, 0.2546, 0.247 ,
       0.2394, 0.2318, 0.2261, 0.2204, 0.2147, 0.209 , 0.2033, 0.1995,
       0.1938, 0.19  , 0.1862, 0.1805, 0.1767, 0.1729, 0.171 , 0.1672,
       0.1634, 0.1596, 0.1577, 0.1539, 0.152 , 0.1482, 0.1463, 0.1444,
       0.1406, 0.1387, 0.1368, 0.1349, 0.1311, 0.1292, 0.1273, 0.1254,
       0.1235, 0.1216, 0.1197, 0.1178, 0.1178, 0.1159, 0.114 , 0.1121,
       0.1102, 0.1102, 0.1083, 0.1064, 0.1045, 0.1045, 0.1026, 0.1007,
       0.1007, 0.0988, 0.0969, 0.0969, 0.095 , 0.095 , 0.0931, 0.0931,
       0.0912, 0.0893, 0.0893, 0.0874, 0.0874, 0.0855, 0.0855, 0.0855,
       0.0836, 0.0836])

In [56]:
fe.sum()

18.9981

In [57]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0358, -0.0328, -0.0302, -0.03  , -0.028 , -0.0243,
       -0.0248, -0.0195, -0.0223, -0.0212, -0.0202, -0.0173, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0122,
       -0.0138, -0.0134, -0.011 , -0.0106, -0.0122, -0.0119, -0.0116,
       -0.0093, -0.009 , -0.0107, -0.0105, -0.0102, -0.008 , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.007 , -0.0068, -0.0066, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0053, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0036, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0031, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [58]:
diferencia.sum()

-0.9619

In [59]:
f0_fe= (f0-fe)

In [60]:
f0_fe_2 = f0_fe*f0_fe

In [61]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.7866    , 0.11056981, 0.17360169, 0.24632109, 0.57      ,
       0.532     , 0.50090072, 0.4712    , 5.40506663, 0.4237    ,
       0.4028    , 0.3838    , 1.09372482, 0.3515    , 0.3363    ,
       0.323     , 0.3116    , 0.3002    , 0.2888    , 0.2793    ,
       1.97624922, 0.2622    , 0.2546    , 2.295583  , 2.41650944,
       0.2318    , 0.2261    , 0.2204    , 2.87236185, 2.993689  ,
       0.2033    , 0.1995    , 0.1938    , 3.45315789, 0.1862    ,
       0.1805    , 0.1767    , 0.1729    , 4.01895322, 4.14806124,
       4.28335104, 0.1596    , 0.1577    , 0.1539    , 0.152     ,
       0.1482    , 0.1463    , 0.1444    , 0.1406    , 5.34850534,
       0.1368    , 0.1349    , 0.1311    , 0.1292    , 0.1273    ,
       0.1254    , 0.1235    , 0.1216    , 0.1197    , 0.1178    ,
       0.1178    , 0.1159    , 0.114     , 0.1121    , 0.1102    ,
       0.1102    , 0.1083    , 7.50489624, 0.1045    , 0.1045    ,
       0.1026    , 0.1007    , 0.1007    , 0.0988    , 8.41681

# Total

In [62]:
x_2 = f0_fe_2_fe.sum()
x_2 

70.73881967720074