In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1HCvzhYjTDoj04gFf14v09zri_ZcSogTe/export?format=csv")
df

PL     PN  LIBRE-PINU  TOTAL
0   1887  13367        4992  20364
1    903   2235         893   4069
2     36   1853        1886   3800
3    151   2303         757   3241
4    839   4340        2988   8212
5    415   2887         966   4333
6    753   2092         912   3783
7    857   2226         534   3633
8   1459   6169        2514  10254
9    243   2714        1895   4873
10   372   3767        2910   7085
11    32   2251        1625   3918
12   420   9552        6145  16216
13   178   1159        1263   2624
14   132   3078        1359   4638
15   365   3947        1748   6187
16   118   2260        1935   4342
17   263    730         363   1378
18  1290   4399        1186   6911
19   328   3561        2411   6369
20   457   2874        1107   4494
21  1316   1861         417   3605
22   154   2279        1512   3973
23    37   1153         445   1752
24    48   2415         929   3407
25    39   1719         395   2165
26    24    812         971   1822
27   439   1153        1386   2998

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[1887,
 903,
 36,
 151,
 839,
 415,
 753,
 857,
 1459,
 243,
 372,
 32,
 420,
 178,
 132,
 365,
 118,
 263,
 1290,
 328,
 457,
 1316,
 154,
 37,
 48,
 39,
 24,
 439]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[13367,
 2235,
 1853,
 2303,
 4340,
 2887,
 2092,
 2226,
 6169,
 2714,
 3767,
 2251,
 9552,
 1159,
 3078,
 3947,
 2260,
 730,
 4399,
 3561,
 2874,
 1861,
 2279,
 1153,
 2415,
 1719,
 812,
 1153]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[4992,
 893,
 1886,
 757,
 2988,
 966,
 912,
 534,
 2514,
 1895,
 2910,
 1625,
 6145,
 1263,
 1359,
 1748,
 1935,
 363,
 1186,
 2411,
 1107,
 417,
 1512,
 445,
 929,
 395,
 971,
 1386]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[20364,
 4069,
 3800,
 3241,
 8212,
 4333,
 3783,
 3633,
 10254,
 4873,
 7085,
 3918,
 16216,
 2624,
 4638,
 6187,
 4342,
 1378,
 6911,
 6369,
 4494,
 3605,
 3973,
 1752,
 3407,
 2165,
 1822,
 2998]

In [7]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [8]:
f0 = np.array(f0)
f0

array([0, 1, 1, 2, 1, 2, 0, 1, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0,
       2, 0, 0, 0, 2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [9]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.002, 0.002, 0.004, 0.002, 0.004, 0.   , 0.002, 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.004, 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.004, 0.   , 0.   , 0.   , 0.004,
       0.004, 0.   , 0.002, 0.   , 0.002, 0.002, 0.002, 0.   , 0.002,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [10]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [11]:
f0_tot=f0.sum()
f0_tot

28

In [12]:
fe = benford*f0_tot

In [13]:
fe 

array([1.1592, 1.0584, 0.9744, 0.9016, 0.84  , 0.784 , 0.7364, 0.6944,
       0.658 , 0.6244, 0.5936, 0.5656, 0.5404, 0.518 , 0.4956, 0.476 ,
       0.4592, 0.4424, 0.4256, 0.4116, 0.3976, 0.3864, 0.3752, 0.364 ,
       0.3528, 0.3416, 0.3332, 0.3248, 0.3164, 0.308 , 0.2996, 0.294 ,
       0.2856, 0.28  , 0.2744, 0.266 , 0.2604, 0.2548, 0.252 , 0.2464,
       0.2408, 0.2352, 0.2324, 0.2268, 0.224 , 0.2184, 0.2156, 0.2128,
       0.2072, 0.2044, 0.2016, 0.1988, 0.1932, 0.1904, 0.1876, 0.1848,
       0.182 , 0.1792, 0.1764, 0.1736, 0.1736, 0.1708, 0.168 , 0.1652,
       0.1624, 0.1624, 0.1596, 0.1568, 0.154 , 0.154 , 0.1512, 0.1484,
       0.1484, 0.1456, 0.1428, 0.1428, 0.14  , 0.14  , 0.1372, 0.1372,
       0.1344, 0.1316, 0.1316, 0.1288, 0.1288, 0.126 , 0.126 , 0.126 ,
       0.1232, 0.1232])

In [14]:
fe.sum()

27.9972

In [15]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0358, -0.0328, -0.0282, -0.028 , -0.024 , -0.0263,
       -0.0228, -0.0215, -0.0223, -0.0212, -0.0202, -0.0193, -0.0185,
       -0.0137, -0.017 , -0.0144, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0094, -0.013 , -0.0126, -0.0122, -0.0079, -0.0076,
       -0.0113, -0.009 , -0.0107, -0.0085, -0.0082, -0.008 , -0.0098,
       -0.0075, -0.0093, -0.0091, -0.007 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0038, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0032, -0.0051, -0.0031, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0028, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [16]:
diferencia.sum()

-0.9438999999999999

In [17]:
f0_fe= (f0-fe)

In [18]:
f0_fe_2 = f0_fe*f0_fe

In [19]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.15920000e+00, 3.22237339e-03, 6.72577997e-04, 1.33815723e+00,
       3.04761905e-02, 1.88604082e+00, 7.36400000e-01, 1.34492166e-01,
       1.77756839e-01, 6.24400000e-01, 5.93600000e-01, 5.65600000e-01,
       5.40400000e-01, 5.18000000e-01, 4.56662502e+00, 4.76000000e-01,
       6.36900348e-01, 4.42400000e-01, 4.25600000e-01, 4.11600000e-01,
       3.97600000e-01, 3.86400000e-01, 7.03618081e+00, 3.64000000e-01,
       3.52800000e-01, 3.41600000e-01, 8.33800192e+00, 8.64007094e+00,
       3.16400000e-01, 1.55475325e+00, 2.99600000e-01, 1.69536054e+00,
       1.78700056e+00, 1.85142857e+00, 2.74400000e-01, 2.02539850e+00,
       2.60400000e-01, 2.54800000e-01, 2.22025397e+00, 2.46400000e-01,
       2.40800000e-01, 2.35200000e-01, 2.32400000e-01, 2.26800000e-01,
       2.24000000e-01, 2.18400000e-01, 2.15600000e-01, 2.12800000e-01,
       2.07200000e-01, 2.04400000e-01, 2.01600000e-01, 1.98800000e-01,
       1.93200000e-01, 1.90400000e-01, 1.87600000e-01, 1.84800000e-01,
      

# Partido Liberal

In [20]:
x_2 = f0_fe_2_fe.sum()
x_2 

81.80463726431367

In [21]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [22]:
f0 = np.array(f0)
f0

array([0, 3, 0, 1, 0, 0, 0, 1, 2, 0, 1, 0, 5, 1, 1, 0, 0, 1, 2, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0])

In [23]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.006, 0.   , 0.002, 0.   , 0.   , 0.   , 0.002, 0.004,
       0.   , 0.002, 0.   , 0.01 , 0.002, 0.002, 0.   , 0.   , 0.002,
       0.004, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.004, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ])

In [24]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [25]:
f0_tot=f0.sum()
f0_tot

28

In [26]:
fe = benford*f0_tot

In [27]:
fe 

array([1.1592, 1.0584, 0.9744, 0.9016, 0.84  , 0.784 , 0.7364, 0.6944,
       0.658 , 0.6244, 0.5936, 0.5656, 0.5404, 0.518 , 0.4956, 0.476 ,
       0.4592, 0.4424, 0.4256, 0.4116, 0.3976, 0.3864, 0.3752, 0.364 ,
       0.3528, 0.3416, 0.3332, 0.3248, 0.3164, 0.308 , 0.2996, 0.294 ,
       0.2856, 0.28  , 0.2744, 0.266 , 0.2604, 0.2548, 0.252 , 0.2464,
       0.2408, 0.2352, 0.2324, 0.2268, 0.224 , 0.2184, 0.2156, 0.2128,
       0.2072, 0.2044, 0.2016, 0.1988, 0.1932, 0.1904, 0.1876, 0.1848,
       0.182 , 0.1792, 0.1764, 0.1736, 0.1736, 0.1708, 0.168 , 0.1652,
       0.1624, 0.1624, 0.1596, 0.1568, 0.154 , 0.154 , 0.1512, 0.1484,
       0.1484, 0.1456, 0.1428, 0.1428, 0.14  , 0.14  , 0.1372, 0.1372,
       0.1344, 0.1316, 0.1316, 0.1288, 0.1288, 0.126 , 0.126 , 0.126 ,
       0.1232, 0.1232])

In [28]:
fe.sum()

27.9972

In [29]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0318, -0.0348, -0.0302, -0.03  , -0.028 , -0.0263,
       -0.0228, -0.0195, -0.0223, -0.0192, -0.0202, -0.0093, -0.0165,
       -0.0157, -0.017 , -0.0164, -0.0138, -0.0112, -0.0147, -0.0122,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0102, -0.0119, -0.0096,
       -0.0113, -0.009 , -0.0107, -0.0105, -0.0102, -0.006 , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0051, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0039, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0033, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0025, -0.0045, -0.0045, -0.0044, -0.0044])

In [30]:
diferencia.sum()

-0.9439

In [31]:
f0_fe= (f0-fe)

In [32]:
f0_fe_2 = f0_fe*f0_fe

In [33]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.15920000e+00, 3.56180136e+00, 9.74400000e-01, 1.07393079e-02,
       8.40000000e-01, 7.84000000e-01, 7.36400000e-01, 1.34492166e-01,
       2.73702736e+00, 6.24400000e-01, 2.78236119e-01, 5.65600000e-01,
       3.68024281e+01, 4.48501931e-01, 5.13356255e-01, 4.76000000e-01,
       4.59200000e-01, 7.02797830e-01, 5.82409624e+00, 4.11600000e-01,
       9.12690543e-01, 3.86400000e-01, 3.75200000e-01, 3.64000000e-01,
       3.52800000e-01, 1.26900047e+00, 3.33200000e-01, 1.40361773e+00,
       3.16400000e-01, 1.55475325e+00, 2.99600000e-01, 2.94000000e-01,
       2.85600000e-01, 1.05657143e+01, 2.74400000e-01, 2.66000000e-01,
       2.60400000e-01, 2.54800000e-01, 2.52000000e-01, 2.46400000e-01,
       2.40800000e-01, 2.35200000e-01, 2.32400000e-01, 2.26800000e-01,
       2.24000000e-01, 2.18400000e-01, 2.15600000e-01, 2.12800000e-01,
       2.07200000e-01, 2.04400000e-01, 2.01600000e-01, 3.22898109e+00,
       1.93200000e-01, 1.90400000e-01, 1.87600000e-01, 1.84800000e-01,
      

# Partido Nacional

In [34]:
x_2 = f0_fe_2_fe.sum()
x_2 

104.49495523269546

In [35]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [36]:
f0 = np.array(f0)
f0

array([0, 2, 1, 2, 0, 1, 1, 1, 2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0])

In [37]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.004, 0.002, 0.004, 0.   , 0.002, 0.002, 0.002, 0.004,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.002, 0.002, 0.   , 0.   ,
       0.   , 0.004, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.002, 0.   , 0.002, 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.002, 0.002, 0.   , 0.   , 0.   , 0.002, 0.002, 0.   , 0.   ])

In [38]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [39]:
f0_tot=f0.sum()
f0_tot

28

In [40]:
fe = benford*f0_tot

In [41]:
fe 

array([1.1592, 1.0584, 0.9744, 0.9016, 0.84  , 0.784 , 0.7364, 0.6944,
       0.658 , 0.6244, 0.5936, 0.5656, 0.5404, 0.518 , 0.4956, 0.476 ,
       0.4592, 0.4424, 0.4256, 0.4116, 0.3976, 0.3864, 0.3752, 0.364 ,
       0.3528, 0.3416, 0.3332, 0.3248, 0.3164, 0.308 , 0.2996, 0.294 ,
       0.2856, 0.28  , 0.2744, 0.266 , 0.2604, 0.2548, 0.252 , 0.2464,
       0.2408, 0.2352, 0.2324, 0.2268, 0.224 , 0.2184, 0.2156, 0.2128,
       0.2072, 0.2044, 0.2016, 0.1988, 0.1932, 0.1904, 0.1876, 0.1848,
       0.182 , 0.1792, 0.1764, 0.1736, 0.1736, 0.1708, 0.168 , 0.1652,
       0.1624, 0.1624, 0.1596, 0.1568, 0.154 , 0.154 , 0.1512, 0.1484,
       0.1484, 0.1456, 0.1428, 0.1428, 0.14  , 0.14  , 0.1372, 0.1372,
       0.1344, 0.1316, 0.1316, 0.1288, 0.1288, 0.126 , 0.126 , 0.126 ,
       0.1232, 0.1232])

In [42]:
fe.sum()

27.9972

In [43]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0338, -0.0328, -0.0282, -0.03  , -0.026 , -0.0243,
       -0.0228, -0.0195, -0.0203, -0.0212, -0.0202, -0.0193, -0.0185,
       -0.0157, -0.015 , -0.0164, -0.0158, -0.0152, -0.0107, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0099, -0.0116,
       -0.0113, -0.009 , -0.0107, -0.0085, -0.0102, -0.01  , -0.0078,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0068, -0.0086, -0.0084,
       -0.0083, -0.0061, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0051, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0038, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0029, -0.0048, -0.0027, -0.0027, -0.0046,
       -0.0046, -0.0045, -0.0025, -0.0025, -0.0044, -0.0044])

In [44]:
diferencia.sum()

-0.9438999999999999

In [45]:
f0_fe= (f0-fe)

In [46]:
f0_fe_2 = f0_fe*f0_fe

In [47]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.15920000e+00, 8.37689494e-01, 6.72577997e-04, 1.33815723e+00,
       8.40000000e-01, 5.95102041e-02, 9.43576317e-02, 1.34492166e-01,
       2.73702736e+00, 2.25937476e-01, 5.93600000e-01, 5.65600000e-01,
       5.40400000e-01, 5.18000000e-01, 5.13356255e-01, 5.76840336e-01,
       4.59200000e-01, 4.42400000e-01, 4.25600000e-01, 6.12977298e+00,
       3.97600000e-01, 3.86400000e-01, 3.75200000e-01, 3.64000000e-01,
       3.52800000e-01, 3.41600000e-01, 1.33440048e+00, 3.24800000e-01,
       3.16400000e-01, 1.55475325e+00, 2.99600000e-01, 1.69536054e+00,
       2.85600000e-01, 2.80000000e-01, 1.91871487e+00, 2.66000000e-01,
       2.60400000e-01, 2.54800000e-01, 2.52000000e-01, 2.30484156e+00,
       2.40800000e-01, 2.35200000e-01, 2.32400000e-01, 2.63597108e+00,
       2.24000000e-01, 2.18400000e-01, 2.15600000e-01, 2.12800000e-01,
       2.07200000e-01, 2.04400000e-01, 2.01600000e-01, 3.22898109e+00,
       1.93200000e-01, 1.90400000e-01, 1.87600000e-01, 1.84800000e-01,
      

# Partido Libre

In [48]:
x_2 = f0_fe_2_fe.sum()
x_2 

78.13848603954968

In [49]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [50]:
f0 = np.array(f0)
f0

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 2, 1, 1, 2, 1, 0, 0, 2, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [51]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.   , 0.   , 0.002, 0.   , 0.   , 0.002, 0.002, 0.002,
       0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.002, 0.   , 0.002, 0.   , 0.004,
       0.002, 0.002, 0.004, 0.002, 0.   , 0.   , 0.004, 0.002, 0.   ,
       0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [52]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [53]:
f0_tot=f0.sum()
f0_tot

28

In [54]:
fe = benford*f0_tot

In [55]:
fe 

array([1.1592, 1.0584, 0.9744, 0.9016, 0.84  , 0.784 , 0.7364, 0.6944,
       0.658 , 0.6244, 0.5936, 0.5656, 0.5404, 0.518 , 0.4956, 0.476 ,
       0.4592, 0.4424, 0.4256, 0.4116, 0.3976, 0.3864, 0.3752, 0.364 ,
       0.3528, 0.3416, 0.3332, 0.3248, 0.3164, 0.308 , 0.2996, 0.294 ,
       0.2856, 0.28  , 0.2744, 0.266 , 0.2604, 0.2548, 0.252 , 0.2464,
       0.2408, 0.2352, 0.2324, 0.2268, 0.224 , 0.2184, 0.2156, 0.2128,
       0.2072, 0.2044, 0.2016, 0.1988, 0.1932, 0.1904, 0.1876, 0.1848,
       0.182 , 0.1792, 0.1764, 0.1736, 0.1736, 0.1708, 0.168 , 0.1652,
       0.1624, 0.1624, 0.1596, 0.1568, 0.154 , 0.154 , 0.1512, 0.1484,
       0.1484, 0.1456, 0.1428, 0.1428, 0.14  , 0.14  , 0.1372, 0.1372,
       0.1344, 0.1316, 0.1316, 0.1288, 0.1288, 0.126 , 0.126 , 0.126 ,
       0.1232, 0.1232])

In [56]:
fe.sum()

27.9972

In [57]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0378, -0.0348, -0.0302, -0.03  , -0.028 , -0.0243,
       -0.0228, -0.0215, -0.0223, -0.0192, -0.0182, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0144, -0.0158, -0.0152, -0.0127, -0.0142,
       -0.0138, -0.0114, -0.013 , -0.0106, -0.0122, -0.0079, -0.0096,
       -0.0093, -0.007 , -0.0087, -0.0105, -0.0102, -0.006 , -0.0078,
       -0.0095, -0.0073, -0.0091, -0.007 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0051, -0.0069, -0.0048, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0042, -0.0042, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0033, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [58]:
diferencia.sum()

-0.9439

In [59]:
f0_fe= (f0-fe)

In [60]:
f0_fe_2 = f0_fe*f0_fe

In [61]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.02186391,  1.0584    ,  0.9744    ,  0.01073931,  0.84      ,
        0.784     ,  0.09435763,  0.13449217,  0.17775684,  0.6244    ,
        0.27823612,  0.33363395,  0.5404    ,  0.518     ,  0.4956    ,
        0.476     ,  0.63690035,  0.4424    ,  0.4256    ,  0.84114325,
        0.3976    ,  0.3864    ,  1.0404452 ,  0.364     ,  1.18726712,
        0.3416    ,  8.33800192,  1.40361773,  1.47695626,  9.29501299,
        1.63738371,  0.294     ,  0.2856    , 10.56571429,  1.91871487,
        0.266     ,  2.10064578,  0.2548    ,  2.22025397,  0.2464    ,
        0.2408    ,  0.2352    ,  0.2324    ,  0.2268    ,  0.224     ,
        0.2184    ,  0.2156    ,  0.2128    ,  0.2072    ,  0.2044    ,
        0.2016    ,  3.22898109,  0.1932    ,  3.44250084,  0.1876    ,
        0.1848    ,  0.182     ,  0.1792    ,  0.1764    ,  3.93396866,
        3.93396866,  0.1708    ,  0.168     ,  0.1652    ,  0.1624    ,
        0.1624    ,  0.1596    ,  0.1568    ,  0.154     ,  0.15

# Total

In [62]:
x_2 = f0_fe_2_fe.sum()
x_2 

80.69550107068613