In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1waXfL5jUCgEbteG-sf1mOPn_8jMDTHDJ/export?format=csv")
df

PL      PN  LIBRE-PINU   TOTAL
0    20194   52450       73661  147470
1    10756   39302       56979  107783
2    29302   88557       71035  190202
3    30967   68987       60147  161366
4    55840  161123      271047  492773
5    27963   88524       84566  202371
6    41509   89629       61968  194545
7   106058  278624      234944  627578
8     3474   11044        8373   23619
9    17311   54356       28572  101231
10    5041    7852        9003   22078
11   22358   45542       21918   90485
12   13555   89156       46444  150446
13   17302   31338       22630   71830
14   26146   90767       81777  200417
15   10739   96205       98135  206163
16   19307   37000       31936   88656
17   26166   79541       95931  203170
18     199     891        1376    2521

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[20194,
 10756,
 29302,
 30967,
 55840,
 27963,
 41509,
 106058,
 3474,
 17311,
 5041,
 22358,
 13555,
 17302,
 26146,
 10739,
 19307,
 26166,
 199]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[52450,
 39302,
 88557,
 68987,
 161123,
 88524,
 89629,
 278624,
 11044,
 54356,
 7852,
 45542,
 89156,
 31338,
 90767,
 96205,
 37000,
 79541,
 891]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[73661,
 56979,
 71035,
 60147,
 271047,
 84566,
 61968,
 234944,
 8373,
 28572,
 9003,
 21918,
 46444,
 22630,
 81777,
 98135,
 31936,
 95931,
 1376]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[147470,
 107783,
 190202,
 161366,
 492773,
 202371,
 194545,
 627578,
 23619,
 101231,
 22078,
 90485,
 150446,
 71830,
 200417,
 206163,
 88656,
 203170,
 2521]

In [7]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [8]:
f0 = np.array(f0)
f0

array([3, 0, 0, 1, 0, 0, 0, 2, 0, 2, 1, 0, 1, 0, 0, 0, 2, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [9]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.006, 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.004, 0.   ,
       0.004, 0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.004, 0.002,
       0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [10]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [11]:
f0_tot=f0.sum()
f0_tot

19

In [12]:
fe = benford*f0_tot

In [13]:
fe 

array([0.7866, 0.7182, 0.6612, 0.6118, 0.57  , 0.532 , 0.4997, 0.4712,
       0.4465, 0.4237, 0.4028, 0.3838, 0.3667, 0.3515, 0.3363, 0.323 ,
       0.3116, 0.3002, 0.2888, 0.2793, 0.2698, 0.2622, 0.2546, 0.247 ,
       0.2394, 0.2318, 0.2261, 0.2204, 0.2147, 0.209 , 0.2033, 0.1995,
       0.1938, 0.19  , 0.1862, 0.1805, 0.1767, 0.1729, 0.171 , 0.1672,
       0.1634, 0.1596, 0.1577, 0.1539, 0.152 , 0.1482, 0.1463, 0.1444,
       0.1406, 0.1387, 0.1368, 0.1349, 0.1311, 0.1292, 0.1273, 0.1254,
       0.1235, 0.1216, 0.1197, 0.1178, 0.1178, 0.1159, 0.114 , 0.1121,
       0.1102, 0.1102, 0.1083, 0.1064, 0.1045, 0.1045, 0.1026, 0.1007,
       0.1007, 0.0988, 0.0969, 0.0969, 0.095 , 0.095 , 0.0931, 0.0931,
       0.0912, 0.0893, 0.0893, 0.0874, 0.0874, 0.0855, 0.0855, 0.0855,
       0.0836, 0.0836])

In [14]:
fe.sum()

18.9981

In [15]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0354, -0.0378, -0.0348, -0.0302, -0.03  , -0.028 , -0.0263,
       -0.0208, -0.0235, -0.0183, -0.0192, -0.0202, -0.0173, -0.0185,
       -0.0177, -0.017 , -0.0124, -0.0138, -0.0152, -0.0127, -0.0122,
       -0.0138, -0.0134, -0.013 , -0.0106, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0085, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0066, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0058, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [16]:
diferencia.sum()

-0.9619

In [17]:
f0_fe= (f0-fe)

In [18]:
f0_fe_2 = f0_fe*f0_fe

In [19]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([6.2282476 , 0.7182    , 0.6612    , 0.24632109, 0.57      ,
       0.532     , 0.4997    , 4.96016435, 0.4465    , 5.86434196,
       0.88542165, 0.3838    , 1.09372482, 0.3515    , 0.3363    ,
       0.323     , 9.14857047, 1.63131259, 0.2888    , 1.85967952,
       1.97624922, 0.2622    , 0.2546    , 0.247     , 2.41650944,
       0.2318    , 0.2261    , 0.2204    , 0.2147    , 0.209     ,
       0.2033    , 3.21203133, 0.1938    , 0.19      , 0.1862    ,
       0.1805    , 0.1767    , 0.1729    , 0.171     , 0.1672    ,
       4.28335104, 0.1596    , 0.1577    , 0.1539    , 0.152     ,
       4.89583833, 0.1463    , 0.1444    , 0.1406    , 0.1387    ,
       0.1368    , 0.1349    , 0.1311    , 0.1292    , 0.1273    ,
       0.1254    , 0.1235    , 0.1216    , 0.1197    , 0.1178    ,
       0.1178    , 0.1159    , 0.114     , 0.1121    , 0.1102    ,
       0.1102    , 0.1083    , 0.1064    , 0.1045    , 0.1045    ,
       0.1026    , 0.1007    , 0.1007    , 0.0988    , 0.0969 

# Partido Liberal

In [20]:
x_2 = f0_fe_2_fe.sum()
x_2 

62.725663400979684

In [21]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [22]:
f0 = np.array(f0)
f0

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0])

In [23]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.004, 0.006, 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ])

In [24]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [25]:
f0_tot=f0.sum()
f0_tot

19

In [26]:
fe = benford*f0_tot

In [27]:
fe 

array([0.7866, 0.7182, 0.6612, 0.6118, 0.57  , 0.532 , 0.4997, 0.4712,
       0.4465, 0.4237, 0.4028, 0.3838, 0.3667, 0.3515, 0.3363, 0.323 ,
       0.3116, 0.3002, 0.2888, 0.2793, 0.2698, 0.2622, 0.2546, 0.247 ,
       0.2394, 0.2318, 0.2261, 0.2204, 0.2147, 0.209 , 0.2033, 0.1995,
       0.1938, 0.19  , 0.1862, 0.1805, 0.1767, 0.1729, 0.171 , 0.1672,
       0.1634, 0.1596, 0.1577, 0.1539, 0.152 , 0.1482, 0.1463, 0.1444,
       0.1406, 0.1387, 0.1368, 0.1349, 0.1311, 0.1292, 0.1273, 0.1254,
       0.1235, 0.1216, 0.1197, 0.1178, 0.1178, 0.1159, 0.114 , 0.1121,
       0.1102, 0.1102, 0.1083, 0.1064, 0.1045, 0.1045, 0.1026, 0.1007,
       0.1007, 0.0988, 0.0969, 0.0969, 0.095 , 0.095 , 0.0931, 0.0931,
       0.0912, 0.0893, 0.0893, 0.0874, 0.0874, 0.0855, 0.0855, 0.0855,
       0.0836, 0.0836])

In [28]:
fe.sum()

18.9981

In [29]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0358, -0.0348, -0.0322, -0.03  , -0.028 , -0.0243,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0138, -0.0152, -0.0147, -0.0142,
       -0.0118, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0096,
       -0.0113, -0.009 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0075, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0063, -0.0081, -0.006 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0043, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0035, -0.0035,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0009,  0.0011, -0.0028, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0025, -0.0045, -0.0044, -0.0044])

In [30]:
diferencia.sum()

-0.9618999999999999

In [31]:
f0_fe= (f0-fe)

In [32]:
f0_fe_2 = f0_fe*f0_fe

In [33]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([7.86600000e-01, 1.10569813e-01, 6.61200000e-01, 6.11800000e-01,
       5.70000000e-01, 5.32000000e-01, 5.00900720e-01, 4.71200000e-01,
       4.46500000e-01, 4.23700000e-01, 4.02800000e-01, 3.83800000e-01,
       3.66700000e-01, 3.51500000e-01, 3.36300000e-01, 3.23000000e-01,
       3.11600000e-01, 1.63131259e+00, 2.88800000e-01, 2.79300000e-01,
       2.69800000e-01, 2.07608253e+00, 2.54600000e-01, 2.47000000e-01,
       2.39400000e-01, 2.31800000e-01, 2.26100000e-01, 2.75760508e+00,
       2.14700000e-01, 2.99368900e+00, 2.03300000e-01, 1.99500000e-01,
       1.93800000e-01, 1.90000000e-01, 1.86200000e-01, 3.72066620e+00,
       1.76700000e-01, 1.72900000e-01, 1.71000000e-01, 1.67200000e-01,
       1.63400000e-01, 1.59600000e-01, 4.49885409e+00, 1.53900000e-01,
       4.73094737e+00, 1.48200000e-01, 1.46300000e-01, 1.44400000e-01,
       1.40600000e-01, 1.38700000e-01, 1.36800000e-01, 1.34900000e-01,
       1.31100000e-01, 1.29200000e-01, 1.27300000e-01, 1.25400000e-01,
      

# Partido Nacional

In [34]:
x_2 = f0_fe_2_fe.sum()
x_2 

209.1074222619977

In [35]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [36]:
f0 = np.array(f0)
f0

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0])

In [37]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.002, 0.002, 0.   , 0.   , 0.   , 0.002,
       0.002, 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.002, 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.002, 0.   ])

In [38]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [39]:
f0_tot=f0.sum()
f0_tot

19

In [40]:
fe = benford*f0_tot

In [41]:
fe 

array([0.7866, 0.7182, 0.6612, 0.6118, 0.57  , 0.532 , 0.4997, 0.4712,
       0.4465, 0.4237, 0.4028, 0.3838, 0.3667, 0.3515, 0.3363, 0.323 ,
       0.3116, 0.3002, 0.2888, 0.2793, 0.2698, 0.2622, 0.2546, 0.247 ,
       0.2394, 0.2318, 0.2261, 0.2204, 0.2147, 0.209 , 0.2033, 0.1995,
       0.1938, 0.19  , 0.1862, 0.1805, 0.1767, 0.1729, 0.171 , 0.1672,
       0.1634, 0.1596, 0.1577, 0.1539, 0.152 , 0.1482, 0.1463, 0.1444,
       0.1406, 0.1387, 0.1368, 0.1349, 0.1311, 0.1292, 0.1273, 0.1254,
       0.1235, 0.1216, 0.1197, 0.1178, 0.1178, 0.1159, 0.114 , 0.1121,
       0.1102, 0.1102, 0.1083, 0.1064, 0.1045, 0.1045, 0.1026, 0.1007,
       0.1007, 0.0988, 0.0969, 0.0969, 0.095 , 0.095 , 0.0931, 0.0931,
       0.0912, 0.0893, 0.0893, 0.0874, 0.0874, 0.0855, 0.0855, 0.0855,
       0.0836, 0.0836])

In [42]:
fe.sum()

18.9981

In [43]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0378, -0.0348, -0.0302, -0.03  , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0182, -0.0173, -0.0165,
       -0.0177, -0.017 , -0.0164, -0.0138, -0.0132, -0.0147, -0.0142,
       -0.0118, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0073, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0057, -0.0076, -0.0074,
       -0.0073, -0.0052, -0.0051, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0041, -0.006 ,
       -0.0039, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0033, -0.0053, -0.0032, -0.0031, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0028, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0025, -0.0045, -0.0045, -0.0024, -0.0044])

In [44]:
diferencia.sum()

-0.9619

In [45]:
f0_fe= (f0-fe)

In [46]:
f0_fe_2 = f0_fe*f0_fe

In [47]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.7866    ,  0.7182    ,  0.6612    ,  0.24632109,  0.57      ,
        0.532     ,  0.4997    ,  0.4712    ,  0.4465    ,  0.4237    ,
        0.4028    ,  0.98932371,  1.09372482,  1.19645021,  0.3363    ,
        0.323     ,  0.3116    ,  1.63131259,  1.75140388,  0.2793    ,
        0.2698    ,  2.07608253,  0.2546    ,  0.247     ,  0.2394    ,
        0.2318    ,  0.2261    ,  0.2204    ,  0.2147    ,  0.209     ,
        0.2033    ,  0.1995    ,  0.1938    ,  0.19      ,  0.1862    ,
        0.1805    ,  3.83600956,  0.1729    ,  0.171     ,  0.1672    ,
        0.1634    ,  0.1596    ,  0.1577    ,  0.1539    ,  0.152     ,
        0.1482    ,  4.98156999,  0.1444    ,  0.1406    ,  0.1387    ,
        5.44674152,  5.54779844,  0.1311    ,  0.1292    ,  0.1273    ,
        0.1254    ,  0.1235    ,  0.1216    ,  0.1197    ,  0.1178    ,
        0.1178    ,  6.7440277 ,  0.114     ,  7.0327066 ,  0.1102    ,
        0.1102    ,  0.1083    ,  0.1064    ,  0.1045    ,  0.10

# Partido Libre

In [48]:
x_2 = f0_fe_2_fe.sum()
x_2 

111.17827537159135

In [49]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [50]:
f0 = np.array(f0)
f0

array([2, 0, 0, 0, 1, 1, 1, 0, 0, 2, 4, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [51]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.004, 0.   , 0.   , 0.   , 0.002, 0.002, 0.002, 0.   , 0.   ,
       0.004, 0.008, 0.   , 0.002, 0.002, 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [52]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [53]:
f0_tot=f0.sum()
f0_tot

19

In [54]:
fe = benford*f0_tot

In [55]:
fe 

array([0.7866, 0.7182, 0.6612, 0.6118, 0.57  , 0.532 , 0.4997, 0.4712,
       0.4465, 0.4237, 0.4028, 0.3838, 0.3667, 0.3515, 0.3363, 0.323 ,
       0.3116, 0.3002, 0.2888, 0.2793, 0.2698, 0.2622, 0.2546, 0.247 ,
       0.2394, 0.2318, 0.2261, 0.2204, 0.2147, 0.209 , 0.2033, 0.1995,
       0.1938, 0.19  , 0.1862, 0.1805, 0.1767, 0.1729, 0.171 , 0.1672,
       0.1634, 0.1596, 0.1577, 0.1539, 0.152 , 0.1482, 0.1463, 0.1444,
       0.1406, 0.1387, 0.1368, 0.1349, 0.1311, 0.1292, 0.1273, 0.1254,
       0.1235, 0.1216, 0.1197, 0.1178, 0.1178, 0.1159, 0.114 , 0.1121,
       0.1102, 0.1102, 0.1083, 0.1064, 0.1045, 0.1045, 0.1026, 0.1007,
       0.1007, 0.0988, 0.0969, 0.0969, 0.095 , 0.095 , 0.0931, 0.0931,
       0.0912, 0.0893, 0.0893, 0.0874, 0.0874, 0.0855, 0.0855, 0.0855,
       0.0836, 0.0836])

In [56]:
fe.sum()

18.9981

In [57]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0374, -0.0378, -0.0348, -0.0322, -0.028 , -0.026 , -0.0243,
       -0.0248, -0.0235, -0.0183, -0.0132, -0.0202, -0.0173, -0.0165,
       -0.0177, -0.015 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0068, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0049, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0041, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0029, -0.0049, -0.0028, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [58]:
diferencia.sum()

-0.9619

In [59]:
f0_fe= (f0-fe)

In [60]:
f0_fe_2 = f0_fe*f0_fe

In [61]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 1.87177671,  0.7182    ,  0.6612    ,  0.6118    ,  0.32438596,
        0.41169925,  0.50090072,  0.4712    ,  0.4465    ,  5.86434196,
       32.12474638,  0.3838    ,  1.09372482,  1.19645021,  0.3363    ,
        1.41897523,  0.3116    ,  0.3002    ,  0.2888    ,  0.2793    ,
        0.2698    ,  0.2622    ,  0.2546    ,  0.247     ,  0.2394    ,
        0.2318    ,  0.2261    ,  0.2204    ,  0.2147    ,  0.209     ,
        0.2033    ,  0.1995    ,  0.1938    ,  0.19      ,  0.1862    ,
        0.1805    ,  0.1767    ,  0.1729    ,  0.171     ,  4.14806124,
        0.1634    ,  0.1596    ,  0.1577    ,  0.1539    ,  0.152     ,
        0.1482    ,  0.1463    ,  0.1444    ,  0.1406    ,  0.1387    ,
        0.1368    ,  0.1349    ,  5.75886506,  0.1292    ,  0.1273    ,
        0.1254    ,  0.1235    ,  0.1216    ,  0.1197    ,  0.1178    ,
        0.1178    ,  6.7440277 ,  0.114     ,  0.1121    ,  0.1102    ,
        0.1102    ,  0.1083    ,  0.1064    ,  0.1045    ,  0.10

# Total

In [62]:
x_2 = f0_fe_2_fe.sum()
x_2 

93.49190609041092