In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1Qmdl_97d9SUNMvGmyKckK405QL-Mwbjr/export?format=csv")
df

PL    PN  LIBRE-PINU  TOTAL
0   2289  4237        4733  11325
1   2479  4210        1325   8072
2    156  1293        1011   2498
3   1160  1087         170   2430
4    977  1054         486   2526
5    938  1455         782   3182
6    870  2123        1779   4799
7    529  1241        1022   2814
8    258  1756         609   2654
9   2003  1033         372   3433
10   469  2023        1647   4161
11   582  1219         458   2274
12  2436  3846        3047   9369
13   541  1106        1118   2867
14   713  2256        2175   5199
15   902  1399        1896   4227

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[2289,
 2479,
 156,
 1160,
 977,
 938,
 870,
 529,
 258,
 2003,
 469,
 582,
 2436,
 541,
 713,
 902]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[4237,
 4210,
 1293,
 1087,
 1054,
 1455,
 2123,
 1241,
 1756,
 1033,
 2023,
 1219,
 3846,
 1106,
 2256,
 1399]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[4733,
 1325,
 1011,
 170,
 486,
 782,
 1779,
 1022,
 609,
 372,
 1647,
 458,
 3047,
 1118,
 2175,
 1896]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[11325,
 8072,
 2498,
 2430,
 2526,
 3182,
 4799,
 2814,
 2654,
 3433,
 4161,
 2274,
 9369,
 2867,
 5199,
 4227]

In [7]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [8]:
f0 = np.array(f0)
f0

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 2, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0])

In [9]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.002, 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.002, 0.   , 0.004, 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.002,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.002,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ])

In [10]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [11]:
f0_tot=f0.sum()
f0_tot

16

In [12]:
fe = benford*f0_tot

In [13]:
fe 

array([0.6624, 0.6048, 0.5568, 0.5152, 0.48  , 0.448 , 0.4208, 0.3968,
       0.376 , 0.3568, 0.3392, 0.3232, 0.3088, 0.296 , 0.2832, 0.272 ,
       0.2624, 0.2528, 0.2432, 0.2352, 0.2272, 0.2208, 0.2144, 0.208 ,
       0.2016, 0.1952, 0.1904, 0.1856, 0.1808, 0.176 , 0.1712, 0.168 ,
       0.1632, 0.16  , 0.1568, 0.152 , 0.1488, 0.1456, 0.144 , 0.1408,
       0.1376, 0.1344, 0.1328, 0.1296, 0.128 , 0.1248, 0.1232, 0.1216,
       0.1184, 0.1168, 0.1152, 0.1136, 0.1104, 0.1088, 0.1072, 0.1056,
       0.104 , 0.1024, 0.1008, 0.0992, 0.0992, 0.0976, 0.096 , 0.0944,
       0.0928, 0.0928, 0.0912, 0.0896, 0.088 , 0.088 , 0.0864, 0.0848,
       0.0848, 0.0832, 0.0816, 0.0816, 0.08  , 0.08  , 0.0784, 0.0784,
       0.0768, 0.0752, 0.0752, 0.0736, 0.0736, 0.072 , 0.072 , 0.072 ,
       0.0704, 0.0704])

In [14]:
fe.sum()

15.998399999999998

In [15]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0358, -0.0348, -0.0322, -0.03  , -0.026 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0192, -0.0202, -0.0173, -0.0185,
       -0.0137, -0.015 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0073, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0063, -0.0081, -0.006 , -0.0078, -0.0077, -0.0076, -0.0054,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0041, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.003 , -0.0049, -0.0049, -0.0028, -0.0047, -0.0047, -0.0026,
       -0.0046, -0.0045, -0.0045, -0.0025, -0.0044, -0.0044])

In [16]:
diferencia.sum()

-0.9679

In [17]:
f0_fe= (f0-fe)

In [18]:
f0_fe_2 = f0_fe*f0_fe

In [19]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.6624    ,  0.25823915,  0.5568    ,  0.5152    ,  0.48      ,
        0.68014286,  0.4208    ,  0.3968    ,  0.376     ,  0.3568    ,
        1.28731321,  0.3232    ,  1.54714197,  0.296     , 10.40749379,
        1.94847059,  0.2624    ,  0.2528    ,  0.2432    ,  0.2352    ,
        0.2272    ,  0.2208    ,  0.2144    ,  0.208     ,  0.2016    ,
        0.1952    ,  0.1904    ,  0.1856    ,  0.1808    ,  0.176     ,
        0.1712    ,  0.168     ,  0.1632    ,  0.16      ,  0.1568    ,
        0.152     ,  4.86923011,  0.1456    ,  0.144     ,  0.1408    ,
        0.1376    ,  0.1344    ,  5.66292048,  0.1296    ,  5.9405    ,
        0.1248    ,  0.1232    ,  0.1216    ,  6.56434595,  0.1168    ,
        0.1152    ,  0.1136    ,  0.1104    ,  0.1088    ,  0.1072    ,
        0.1056    ,  0.104     ,  0.1024    ,  0.1008    ,  0.0992    ,
        0.0992    ,  8.34350164,  0.096     ,  0.0944    ,  0.0928    ,
        0.0928    ,  0.0912    ,  0.0896    ,  0.088     ,  0.08

# Partido Liberal

In [20]:
x_2 = f0_fe_2_fe.sum()
x_2 

105.62277847929329

In [21]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [22]:
f0 = np.array(f0)
f0

array([3, 1, 3, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [23]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.006, 0.002, 0.006, 0.002, 0.002, 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.002, 0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.004, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [24]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [25]:
f0_tot=f0.sum()
f0_tot

16

In [26]:
fe = benford*f0_tot

In [27]:
fe 

array([0.6624, 0.6048, 0.5568, 0.5152, 0.48  , 0.448 , 0.4208, 0.3968,
       0.376 , 0.3568, 0.3392, 0.3232, 0.3088, 0.296 , 0.2832, 0.272 ,
       0.2624, 0.2528, 0.2432, 0.2352, 0.2272, 0.2208, 0.2144, 0.208 ,
       0.2016, 0.1952, 0.1904, 0.1856, 0.1808, 0.176 , 0.1712, 0.168 ,
       0.1632, 0.16  , 0.1568, 0.152 , 0.1488, 0.1456, 0.144 , 0.1408,
       0.1376, 0.1344, 0.1328, 0.1296, 0.128 , 0.1248, 0.1232, 0.1216,
       0.1184, 0.1168, 0.1152, 0.1136, 0.1104, 0.1088, 0.1072, 0.1056,
       0.104 , 0.1024, 0.1008, 0.0992, 0.0992, 0.0976, 0.096 , 0.0944,
       0.0928, 0.0928, 0.0912, 0.0896, 0.088 , 0.088 , 0.0864, 0.0848,
       0.0848, 0.0832, 0.0816, 0.0816, 0.08  , 0.08  , 0.0784, 0.0784,
       0.0768, 0.0752, 0.0752, 0.0736, 0.0736, 0.072 , 0.072 , 0.072 ,
       0.0704, 0.0704])

In [28]:
fe.sum()

15.998399999999998

In [29]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0354, -0.0358, -0.0288, -0.0302, -0.028 , -0.028 , -0.0263,
       -0.0228, -0.0235, -0.0223, -0.0192, -0.0182, -0.0173, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0093, -0.011 , -0.0107, -0.0105, -0.0062, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [30]:
diferencia.sum()

-0.9679

In [31]:
f0_fe= (f0-fe)

In [32]:
f0_fe_2 = f0_fe*f0_fe

In [33]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 8.24935652,  0.25823915, 10.7205931 ,  0.45619379,  0.56333333,
        0.448     ,  0.4208    ,  0.91696129,  0.376     ,  0.3568    ,
        1.28731321,  1.41725941,  1.54714197,  0.296     ,  0.2832    ,
        0.272     ,  0.2624    ,  0.2528    ,  0.2432    ,  0.2352    ,
        0.2272    ,  0.2208    ,  0.2144    ,  0.208     ,  0.2016    ,
        0.1952    ,  0.1904    ,  0.1856    ,  3.71177345,  0.176     ,
        0.1712    ,  0.168     , 20.67300392,  0.16      ,  0.1568    ,
        0.152     ,  0.1488    ,  0.1456    ,  0.144     ,  0.1408    ,
        0.1376    ,  0.1344    ,  0.1328    ,  0.1296    ,  0.128     ,
        0.1248    ,  0.1232    ,  0.1216    ,  0.1184    ,  0.1168    ,
        0.1152    ,  0.1136    ,  0.1104    ,  0.1088    ,  0.1072    ,
        0.1056    ,  0.104     ,  0.1024    ,  0.1008    ,  0.0992    ,
        0.0992    ,  0.0976    ,  0.096     ,  0.0944    ,  0.0928    ,
        0.0928    ,  0.0912    ,  0.0896    ,  0.088     ,  0.08

# Partido Nacional

In [34]:
x_2 = f0_fe_2_fe.sum()
x_2 

61.268369146398086

In [35]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [36]:
f0 = np.array(f0)
f0

array([2, 1, 0, 1, 0, 0, 1, 2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [37]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.004, 0.002, 0.   , 0.002, 0.   , 0.   , 0.002, 0.004, 0.002,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [38]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [39]:
f0_tot=f0.sum()
f0_tot

16

In [40]:
fe = benford*f0_tot

In [41]:
fe 

array([0.6624, 0.6048, 0.5568, 0.5152, 0.48  , 0.448 , 0.4208, 0.3968,
       0.376 , 0.3568, 0.3392, 0.3232, 0.3088, 0.296 , 0.2832, 0.272 ,
       0.2624, 0.2528, 0.2432, 0.2352, 0.2272, 0.2208, 0.2144, 0.208 ,
       0.2016, 0.1952, 0.1904, 0.1856, 0.1808, 0.176 , 0.1712, 0.168 ,
       0.1632, 0.16  , 0.1568, 0.152 , 0.1488, 0.1456, 0.144 , 0.1408,
       0.1376, 0.1344, 0.1328, 0.1296, 0.128 , 0.1248, 0.1232, 0.1216,
       0.1184, 0.1168, 0.1152, 0.1136, 0.1104, 0.1088, 0.1072, 0.1056,
       0.104 , 0.1024, 0.1008, 0.0992, 0.0992, 0.0976, 0.096 , 0.0944,
       0.0928, 0.0928, 0.0912, 0.0896, 0.088 , 0.088 , 0.0864, 0.0848,
       0.0848, 0.0832, 0.0816, 0.0816, 0.08  , 0.08  , 0.0784, 0.0784,
       0.0768, 0.0752, 0.0752, 0.0736, 0.0736, 0.072 , 0.072 , 0.072 ,
       0.0704, 0.0704])

In [42]:
fe.sum()

15.998399999999998

In [43]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0374, -0.0358, -0.0348, -0.0302, -0.03  , -0.028 , -0.0243,
       -0.0208, -0.0215, -0.0223, -0.0212, -0.0182, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0122,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0096,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0075, -0.0093, -0.0071, -0.007 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0052, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0035, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [44]:
diferencia.sum()

-0.9679

In [45]:
f0_fe= (f0-fe)

In [46]:
f0_fe_2 = f0_fe*f0_fe

In [47]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.70104734, 0.25823915, 0.5568    , 0.45619379, 0.48      ,
       0.448     , 0.79722586, 6.47744516, 1.03557447, 0.3568    ,
       0.3392    , 1.41725941, 0.3088    , 0.296     , 0.2832    ,
       0.272     , 0.2624    , 0.2528    , 0.2432    , 0.2352    ,
       2.62860845, 0.2208    , 0.2144    , 0.208     , 0.2016    ,
       0.1952    , 0.1904    , 3.57353103, 0.1808    , 0.176     ,
       0.1712    , 0.168     , 0.1632    , 0.16      , 0.1568    ,
       4.73094737, 0.1488    , 5.01373187, 5.08844444, 0.1408    ,
       0.1376    , 0.1344    , 0.1328    , 0.1296    , 0.128     ,
       0.1248    , 0.1232    , 0.1216    , 0.1184    , 0.1168    ,
       6.79575556, 0.1136    , 0.1104    , 0.1088    , 0.1072    ,
       0.1056    , 0.104     , 0.1024    , 0.1008    , 0.0992    ,
       0.0992    , 0.0976    , 0.096     , 0.0944    , 0.0928    ,
       0.0928    , 0.0912    , 0.0896    , 9.45163636, 0.088     ,
       0.0864    , 0.0848    , 0.0848    , 0.0832    , 0.0816 

# Partido Libre

In [48]:
x_2 = f0_fe_2_fe.sum()
x_2 

62.06724026145981

In [49]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [50]:
f0 = np.array(f0)
f0

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 1, 1, 0, 2, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0])

In [51]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.004, 0.002, 0.002, 0.   ,
       0.004, 0.   , 0.   , 0.002, 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [52]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [53]:
f0_tot=f0.sum()
f0_tot

16

In [54]:
fe = benford*f0_tot

In [55]:
fe 

array([0.6624, 0.6048, 0.5568, 0.5152, 0.48  , 0.448 , 0.4208, 0.3968,
       0.376 , 0.3568, 0.3392, 0.3232, 0.3088, 0.296 , 0.2832, 0.272 ,
       0.2624, 0.2528, 0.2432, 0.2352, 0.2272, 0.2208, 0.2144, 0.208 ,
       0.2016, 0.1952, 0.1904, 0.1856, 0.1808, 0.176 , 0.1712, 0.168 ,
       0.1632, 0.16  , 0.1568, 0.152 , 0.1488, 0.1456, 0.144 , 0.1408,
       0.1376, 0.1344, 0.1328, 0.1296, 0.128 , 0.1248, 0.1232, 0.1216,
       0.1184, 0.1168, 0.1152, 0.1136, 0.1104, 0.1088, 0.1072, 0.1056,
       0.104 , 0.1024, 0.1008, 0.0992, 0.0992, 0.0976, 0.096 , 0.0944,
       0.0928, 0.0928, 0.0912, 0.0896, 0.088 , 0.088 , 0.0864, 0.0848,
       0.0848, 0.0832, 0.0816, 0.0816, 0.08  , 0.08  , 0.0784, 0.0784,
       0.0768, 0.0752, 0.0752, 0.0736, 0.0736, 0.072 , 0.072 , 0.072 ,
       0.0704, 0.0704])

In [56]:
fe.sum()

15.998399999999998

In [57]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0358, -0.0348, -0.0322, -0.03  , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0202, -0.0173, -0.0185,
       -0.0137, -0.015 , -0.0144, -0.0158, -0.0112, -0.0147, -0.0142,
       -0.0118, -0.0134, -0.013 , -0.0106, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0085, -0.0082, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0071, -0.009 , -0.0088, -0.0086, -0.0064,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0034, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0026,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [58]:
diferencia.sum()

-0.9679

In [59]:
f0_fe= (f0-fe)

In [60]:
f0_fe_2 = f0_fe*f0_fe

In [61]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.6624    ,  0.25823915,  0.5568    ,  0.5152    ,  0.48      ,
        0.448     ,  0.4208    ,  0.3968    ,  0.376     ,  0.3568    ,
        0.3392    ,  0.3232    ,  1.54714197,  0.296     , 10.40749379,
        1.94847059,  2.07337561,  0.2528    , 12.69056842,  0.2352    ,
        0.2272    ,  2.74978551,  0.2144    ,  0.208     ,  3.16191746,
        0.1952    ,  0.1904    ,  0.1856    ,  0.1808    ,  0.176     ,
        0.1712    ,  4.12038095,  4.29065098,  0.16      ,  0.1568    ,
        0.152     ,  0.1488    ,  5.01373187,  0.144     ,  0.1408    ,
        0.1376    ,  5.57487619,  0.1328    ,  0.1296    ,  0.128     ,
        0.1248    ,  0.1232    ,  0.1216    ,  0.1184    ,  0.1168    ,
        0.1152    ,  0.1136    ,  0.1104    ,  0.1088    ,  0.1072    ,
        0.1056    ,  0.104     ,  0.1024    ,  0.1008    ,  0.0992    ,
        0.0992    ,  0.0976    ,  0.096     ,  0.0944    ,  0.0928    ,
        0.0928    ,  0.0912    ,  0.0896    ,  0.088     ,  0.08

# Total

In [62]:
x_2 = f0_fe_2_fe.sum()
x_2 

87.98806308146405