In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1MzgxfBh-cXzeZe-OZBJY1V2-J-jDdK_t/export?format=csv")
df

PL    PN  LIBRE-PINU  TOTAL
0   568  9585       11371  21650
1    93  3425        3389   6926
2   193  4354        3890   8474
3   276  3483        4167   7985
4    67  1613        1824   3515
5   433  5322        5795  11590
6   391  2906        2215   5540
7   683  1620        1978   4302
8   180  1608        1229   3029
9   177  2246        2776   5227
10  721   804        1962   3502
11  288  2793        1493   4590
12  421  5648        7752  13910
13  191  2517        1633   4366
14  296  1754        1688   3763
15  445  2831        2730   6023
16  388  2763        1748   4945
17  959  7457        7042  15554
18  370  2416        1037   3838
19  436  6354        5695  12553
20  660  2582        3488   6786
21  388  3586        3827   7828
22  304  3973        3215   7509
23   51  1375         765   2205
24  223   822        1241   2302
25  601  4344        4891   9897
26  701  5030        5650  11436
27  235  2994        3644   6918

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[568,
 93,
 193,
 276,
 67,
 433,
 391,
 683,
 180,
 177,
 721,
 288,
 421,
 191,
 296,
 445,
 388,
 959,
 370,
 436,
 660,
 388,
 304,
 51,
 223,
 601,
 701,
 235]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[9585,
 3425,
 4354,
 3483,
 1613,
 5322,
 2906,
 1620,
 1608,
 2246,
 804,
 2793,
 5648,
 2517,
 1754,
 2831,
 2763,
 7457,
 2416,
 6354,
 2582,
 3586,
 3973,
 1375,
 822,
 4344,
 5030,
 2994]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[11371,
 3389,
 3890,
 4167,
 1824,
 5795,
 2215,
 1978,
 1229,
 2776,
 1962,
 1493,
 7752,
 1633,
 1688,
 2730,
 1748,
 7042,
 1037,
 5695,
 3488,
 3827,
 3215,
 765,
 1241,
 4891,
 5650,
 3644]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[21650,
 6926,
 8474,
 7985,
 3515,
 11590,
 5540,
 4302,
 3029,
 5227,
 3502,
 4590,
 13910,
 4366,
 3763,
 6023,
 4945,
 15554,
 3838,
 12553,
 6786,
 7828,
 7509,
 2205,
 2302,
 9897,
 11436,
 6918]

In [7]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [8]:
f0 = np.array(f0)
f0

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 1, 2, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0])

In [9]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.002,
       0.004, 0.   , 0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.002,
       0.002, 0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.004, 0.002, 0.   , 0.   , 0.002, 0.004, 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.002, 0.002, 0.   , 0.002, 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ])

In [10]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [11]:
f0_tot=f0.sum()
f0_tot

28

In [12]:
fe = benford*f0_tot

In [13]:
fe 

array([1.1592, 1.0584, 0.9744, 0.9016, 0.84  , 0.784 , 0.7364, 0.6944,
       0.658 , 0.6244, 0.5936, 0.5656, 0.5404, 0.518 , 0.4956, 0.476 ,
       0.4592, 0.4424, 0.4256, 0.4116, 0.3976, 0.3864, 0.3752, 0.364 ,
       0.3528, 0.3416, 0.3332, 0.3248, 0.3164, 0.308 , 0.2996, 0.294 ,
       0.2856, 0.28  , 0.2744, 0.266 , 0.2604, 0.2548, 0.252 , 0.2464,
       0.2408, 0.2352, 0.2324, 0.2268, 0.224 , 0.2184, 0.2156, 0.2128,
       0.2072, 0.2044, 0.2016, 0.1988, 0.1932, 0.1904, 0.1876, 0.1848,
       0.182 , 0.1792, 0.1764, 0.1736, 0.1736, 0.1708, 0.168 , 0.1652,
       0.1624, 0.1624, 0.1596, 0.1568, 0.154 , 0.154 , 0.1512, 0.1484,
       0.1484, 0.1456, 0.1428, 0.1428, 0.14  , 0.14  , 0.1372, 0.1372,
       0.1344, 0.1316, 0.1316, 0.1288, 0.1288, 0.126 , 0.126 , 0.126 ,
       0.1232, 0.1232])

In [14]:
fe.sum()

27.9972

In [15]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0378, -0.0348, -0.0322, -0.03  , -0.028 , -0.0263,
       -0.0228, -0.0215, -0.0183, -0.0212, -0.0202, -0.0173, -0.0165,
       -0.0177, -0.017 , -0.0164, -0.0138, -0.0132, -0.0127, -0.0122,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0096,
       -0.0073, -0.009 , -0.0107, -0.0105, -0.0082, -0.006 , -0.0078,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0086, -0.0064,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0057, -0.0076, -0.0074,
       -0.0073, -0.0052, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0045, -0.0044, -0.0043, -0.0062, -0.0042, -0.0061, -0.004 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0026,
       -0.0046, -0.0025, -0.0045, -0.0045, -0.0044, -0.0044])

In [16]:
diferencia.sum()

-0.9439

In [17]:
f0_fe= (f0-fe)

In [18]:
f0_fe_2 = f0_fe*f0_fe

In [19]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 1.1592    ,  1.0584    ,  0.9744    ,  0.9016    ,  0.84      ,
        0.784     ,  0.7364    ,  0.13449217,  0.17775684,  3.0305499 ,
        0.5936    ,  0.5656    ,  0.39088113,  0.44850193,  0.4956    ,
        0.476     ,  0.4592    ,  0.70279783,  0.77522406,  0.84114325,
        0.91269054,  0.3864    ,  0.3752    ,  0.364     ,  0.3528    ,
        0.3416    ,  0.3332    ,  1.40361773,  8.95862503,  1.55475325,
        0.2996    ,  0.294     ,  1.78700056, 10.56571429,  1.91871487,
        0.266     ,  0.2604    ,  0.2548    ,  0.252     ,  0.2464    ,
        0.2408    ,  2.48690068,  0.2324    ,  0.2268    ,  0.224     ,
        0.2184    ,  2.85381892,  0.2128    ,  0.2072    ,  0.2044    ,
        3.16191746,  0.1988    ,  0.1932    ,  0.1904    ,  0.1876    ,
        0.1848    ,  3.67650549,  3.75955714,  3.84533424,  0.1736    ,
        3.93396866,  0.1708    ,  4.12038095,  0.1652    ,  0.1624    ,
        0.1624    ,  0.1596    ,  0.1568    ,  0.154     ,  0.15

# Partido Liberal

In [20]:
x_2 = f0_fe_2_fe.sum()
x_2 

93.10533002070747

In [21]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [22]:
f0 = np.array(f0)
f0

array([0, 0, 0, 1, 0, 0, 3, 1, 0, 0, 0, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 0,
       0, 0, 2, 1, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0])

In [23]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.006, 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.002, 0.004, 0.   , 0.004,
       0.002, 0.004, 0.   , 0.   , 0.   , 0.   , 0.004, 0.002, 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.004, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.002, 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ])

In [24]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [25]:
f0_tot=f0.sum()
f0_tot

28

In [26]:
fe = benford*f0_tot

In [27]:
fe 

array([1.1592, 1.0584, 0.9744, 0.9016, 0.84  , 0.784 , 0.7364, 0.6944,
       0.658 , 0.6244, 0.5936, 0.5656, 0.5404, 0.518 , 0.4956, 0.476 ,
       0.4592, 0.4424, 0.4256, 0.4116, 0.3976, 0.3864, 0.3752, 0.364 ,
       0.3528, 0.3416, 0.3332, 0.3248, 0.3164, 0.308 , 0.2996, 0.294 ,
       0.2856, 0.28  , 0.2744, 0.266 , 0.2604, 0.2548, 0.252 , 0.2464,
       0.2408, 0.2352, 0.2324, 0.2268, 0.224 , 0.2184, 0.2156, 0.2128,
       0.2072, 0.2044, 0.2016, 0.1988, 0.1932, 0.1904, 0.1876, 0.1848,
       0.182 , 0.1792, 0.1764, 0.1736, 0.1736, 0.1708, 0.168 , 0.1652,
       0.1624, 0.1624, 0.1596, 0.1568, 0.154 , 0.154 , 0.1512, 0.1484,
       0.1484, 0.1456, 0.1428, 0.1428, 0.14  , 0.14  , 0.1372, 0.1372,
       0.1344, 0.1316, 0.1316, 0.1288, 0.1288, 0.126 , 0.126 , 0.126 ,
       0.1232, 0.1232])

In [28]:
fe.sum()

27.9972

In [29]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0378, -0.0348, -0.0302, -0.03  , -0.028 , -0.0203,
       -0.0228, -0.0235, -0.0223, -0.0212, -0.0202, -0.0173, -0.0185,
       -0.0157, -0.013 , -0.0164, -0.0118, -0.0132, -0.0107, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0086, -0.0102, -0.0119, -0.0116,
       -0.0113, -0.009 , -0.0107, -0.0105, -0.0102, -0.006 , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.009 , -0.0088, -0.0066, -0.0084,
       -0.0083, -0.0061, -0.008 , -0.0078, -0.0057, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0048, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0038, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0034, -0.0053, -0.0033, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0025, -0.0045, -0.0045, -0.0044, -0.0044])

In [30]:
diferencia.sum()

-0.9439

In [31]:
f0_fe= (f0-fe)

In [32]:
f0_fe_2 = f0_fe*f0_fe

In [33]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 1.1592    ,  1.0584    ,  0.9744    ,  0.01073931,  0.84      ,
        0.784     ,  6.95801869,  0.13449217,  0.658     ,  0.6244    ,
        0.5936    ,  0.5656    ,  0.39088113,  0.518     ,  0.51335626,
        4.87936134,  0.4592    ,  5.48399132,  0.77522406,  6.12977298,
        0.3976    ,  0.3864    ,  0.3752    ,  0.364     ,  7.69066848,
        1.26900047,  0.3332    ,  0.3248    ,  0.3164    ,  1.55475325,
        0.2996    ,  0.294     ,  0.2856    , 10.56571429,  0.2744    ,
        0.266     ,  0.2604    ,  0.2548    ,  0.252     ,  0.2464    ,
        2.39362392,  0.2352    ,  0.2324    ,  2.63597108,  0.224     ,
        0.2184    ,  2.85381892,  0.2128    ,  0.2072    ,  0.2044    ,
        0.2016    ,  0.1988    ,  0.1932    ,  3.44250084,  0.1876    ,
        0.1848    ,  0.182     ,  0.1792    ,  0.1764    ,  0.1736    ,
        0.1736    ,  0.1708    ,  0.168     ,  0.1652    ,  4.32003547,
        0.1624    ,  0.1596    ,  0.1568    ,  0.154     ,  0.15

# Partido Nacional

In [34]:
x_2 = f0_fe_2_fe.sum()
x_2 

97.84553298225772

In [35]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [36]:
f0 = np.array(f0)
f0

array([1, 1, 2, 0, 1, 0, 2, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [37]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.002, 0.002, 0.004, 0.   , 0.002, 0.   , 0.004, 0.002, 0.002,
       0.004, 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.004,
       0.   , 0.   , 0.   , 0.   , 0.002, 0.002, 0.002, 0.   , 0.002,
       0.   , 0.004, 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.004, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [38]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [39]:
f0_tot=f0.sum()
f0_tot

28

In [40]:
fe = benford*f0_tot

In [41]:
fe 

array([1.1592, 1.0584, 0.9744, 0.9016, 0.84  , 0.784 , 0.7364, 0.6944,
       0.658 , 0.6244, 0.5936, 0.5656, 0.5404, 0.518 , 0.4956, 0.476 ,
       0.4592, 0.4424, 0.4256, 0.4116, 0.3976, 0.3864, 0.3752, 0.364 ,
       0.3528, 0.3416, 0.3332, 0.3248, 0.3164, 0.308 , 0.2996, 0.294 ,
       0.2856, 0.28  , 0.2744, 0.266 , 0.2604, 0.2548, 0.252 , 0.2464,
       0.2408, 0.2352, 0.2324, 0.2268, 0.224 , 0.2184, 0.2156, 0.2128,
       0.2072, 0.2044, 0.2016, 0.1988, 0.1932, 0.1904, 0.1876, 0.1848,
       0.182 , 0.1792, 0.1764, 0.1736, 0.1736, 0.1708, 0.168 , 0.1652,
       0.1624, 0.1624, 0.1596, 0.1568, 0.154 , 0.154 , 0.1512, 0.1484,
       0.1484, 0.1456, 0.1428, 0.1428, 0.14  , 0.14  , 0.1372, 0.1372,
       0.1344, 0.1316, 0.1316, 0.1288, 0.1288, 0.126 , 0.126 , 0.126 ,
       0.1232, 0.1232])

In [42]:
fe.sum()

27.9972

In [43]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0394, -0.0358, -0.0308, -0.0322, -0.028 , -0.028 , -0.0223,
       -0.0228, -0.0215, -0.0183, -0.0212, -0.0202, -0.0173, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0118, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0114, -0.011 , -0.0106, -0.0122, -0.0099, -0.0116,
       -0.0073, -0.011 , -0.0107, -0.0085, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.007 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0037, -0.0056, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0042, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0037, -0.0036, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [44]:
diferencia.sum()

-0.9439

In [45]:
f0_fe= (f0-fe)

In [46]:
f0_fe_2 = f0_fe*f0_fe

In [47]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.18639061e-02, 3.22237339e-03, 1.07949031e+00, 9.01600000e-01,
       3.04761905e-02, 7.84000000e-01, 2.16823053e+00, 1.34492166e-01,
       1.77756839e-01, 3.03054990e+00, 5.93600000e-01, 5.65600000e-01,
       3.90881125e-01, 5.18000000e-01, 4.95600000e-01, 4.76000000e-01,
       4.59200000e-01, 5.48399132e+00, 4.25600000e-01, 4.11600000e-01,
       3.97600000e-01, 3.86400000e-01, 1.04044520e+00, 1.11125275e+00,
       1.18726712e+00, 3.41600000e-01, 1.33440048e+00, 3.24800000e-01,
       8.95862503e+00, 3.08000000e-01, 2.99600000e-01, 1.69536054e+00,
       2.85600000e-01, 2.80000000e-01, 2.74400000e-01, 2.66000000e-01,
       2.60400000e-01, 2.54800000e-01, 2.22025397e+00, 2.46400000e-01,
       2.40800000e-01, 2.35200000e-01, 2.32400000e-01, 2.26800000e-01,
       2.24000000e-01, 2.18400000e-01, 1.47684757e+01, 2.91204812e+00,
       2.07200000e-01, 2.04400000e-01, 2.01600000e-01, 1.98800000e-01,
       1.93200000e-01, 1.90400000e-01, 1.87600000e-01, 1.84800000e-01,
      

# Partido Libre

In [48]:
x_2 = f0_fe_2_fe.sum()
x_2 

77.70586741746288

In [49]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [50]:
f0 = np.array(f0)
f0

array([0, 2, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 2, 0, 1, 1, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0])

In [51]:
fre_relativa = np.array(fre_relativa)
fre_relativa 

array([0.   , 0.004, 0.002, 0.002, 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.002, 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.004, 0.   ,
       0.002, 0.002, 0.   , 0.   , 0.   , 0.   , 0.004, 0.   , 0.002,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.004, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.002, 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   ])

In [52]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [53]:
f0_tot=f0.sum()
f0_tot

28

In [54]:
fe = benford*f0_tot

In [55]:
fe 

array([1.1592, 1.0584, 0.9744, 0.9016, 0.84  , 0.784 , 0.7364, 0.6944,
       0.658 , 0.6244, 0.5936, 0.5656, 0.5404, 0.518 , 0.4956, 0.476 ,
       0.4592, 0.4424, 0.4256, 0.4116, 0.3976, 0.3864, 0.3752, 0.364 ,
       0.3528, 0.3416, 0.3332, 0.3248, 0.3164, 0.308 , 0.2996, 0.294 ,
       0.2856, 0.28  , 0.2744, 0.266 , 0.2604, 0.2548, 0.252 , 0.2464,
       0.2408, 0.2352, 0.2324, 0.2268, 0.224 , 0.2184, 0.2156, 0.2128,
       0.2072, 0.2044, 0.2016, 0.1988, 0.1932, 0.1904, 0.1876, 0.1848,
       0.182 , 0.1792, 0.1764, 0.1736, 0.1736, 0.1708, 0.168 , 0.1652,
       0.1624, 0.1624, 0.1596, 0.1568, 0.154 , 0.154 , 0.1512, 0.1484,
       0.1484, 0.1456, 0.1428, 0.1428, 0.14  , 0.14  , 0.1372, 0.1372,
       0.1344, 0.1316, 0.1316, 0.1288, 0.1288, 0.126 , 0.126 , 0.126 ,
       0.1232, 0.1232])

In [56]:
fe.sum()

27.9972

In [57]:
diferencia = fre_relativa - benford
diferencia 

array([-0.0414, -0.0338, -0.0328, -0.0302, -0.03  , -0.026 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0182, -0.0173, -0.0165,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0122,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0082, -0.0119, -0.0096,
       -0.0093, -0.011 , -0.0107, -0.0105, -0.0102, -0.006 , -0.0098,
       -0.0075, -0.0093, -0.0091, -0.009 , -0.0068, -0.0086, -0.0084,
       -0.0063, -0.0081, -0.008 , -0.0058, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0052, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0044, -0.0063, -0.0022, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0038, -0.0057, -0.0056, -0.0035, -0.0035,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0031, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0024, -0.0044])

In [58]:
diferencia.sum()

-0.9438999999999999

In [59]:
f0_fe= (f0-fe)

In [60]:
f0_fe_2 = f0_fe*f0_fe

In [61]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.15920000e+00, 8.37689494e-01, 6.72577997e-04, 1.07393079e-02,
       8.40000000e-01, 5.95102041e-02, 7.36400000e-01, 6.94400000e-01,
       6.58000000e-01, 6.24400000e-01, 5.93600000e-01, 3.33633946e-01,
       3.90881125e-01, 4.48501931e-01, 4.95600000e-01, 4.76000000e-01,
       4.59200000e-01, 4.42400000e-01, 4.25600000e-01, 4.11600000e-01,
       9.12690543e-01, 3.86400000e-01, 3.75200000e-01, 3.64000000e-01,
       3.52800000e-01, 8.05120187e+00, 3.33200000e-01, 1.40361773e+00,
       1.47695626e+00, 3.08000000e-01, 2.99600000e-01, 2.94000000e-01,
       2.85600000e-01, 1.05657143e+01, 2.74400000e-01, 2.02539850e+00,
       2.60400000e-01, 2.54800000e-01, 2.52000000e-01, 2.30484156e+00,
       2.40800000e-01, 2.35200000e-01, 2.53532599e+00, 2.26800000e-01,
       2.24000000e-01, 2.79715458e+00, 2.15600000e-01, 2.12800000e-01,
       2.07200000e-01, 2.04400000e-01, 3.16191746e+00, 1.98800000e-01,
       1.93200000e-01, 1.90400000e-01, 1.87600000e-01, 1.84800000e-01,
      

# Total

In [62]:
x_2 = f0_fe_2_fe.sum()
x_2 

104.03221185278531